Shopify/tapioca

- lib/tapioca/compilers/symbol_table/symbol_generator.rb
- spec/tapioca/compilers/symbol_table_compiler_spec.rb
The usage of `ActiveSupport::Deprecation::DeprecatedConstantProxy` results in:
```
[1] pry(main)> class B; end
=> nil
[2] pry(main)> A = ActiveSupport::Deprecation::DeprecatedConstantProxy.new("A", "B")
=> B
[3] pry(main)> A.name
DEPRECATION WARNING: A is deprecated! Use B instead. (called from <main> at (pry):3)
=> "B"
[4] pry(main)> Module.instance_method(:name).bind(A).call
=> "A"
```
thus breaking our assumptions about treating aliases as constants which are modules whose name do not match the constant name.
So this PR adds a specific check for `ActiveSupport::Deprecation::DeprecatedConstantProxy` usages and gets the `name` of the `target` class as the "real" name of the constant.
> Fix `ActiveSupport::Deprecation::DeprecatedConstantProxy` instances

- README.md
- lib/tapioca/cli.rb
Hi, just a quick typo fix in README.md
And thanks for building this awesome gem.👍
> Fix typo in README.md

- lib/tapioca/compilers/symbol_table/symbol_generator.rb
fixes https://github.com/Shopify/tapioca/issues/10
> filter out T::Private modules

- Gemfile.lock
- lib/tapioca/version.rb
Git tag: https://github.com/Shopify/tapioca/tree/v0.2.4
Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>
> Bump gem to v0.2.4

- .travis.yml
Everything is fine locally, let's see what Travis think about this.
> Enables CI for Ruby 2.7

- Gemfile
- Gemfile.lock
- resolving https://github.com/Shopify/tapioca/issues/71
bundle install went ok.
Test
- dev test
> Fix for insecure git protocol

- lib/tapioca/compilers/dsl/active_record_enum.rb
- spec/tapioca/compilers/dsl/active_record_enum_spec.rb
Resolves: Shopify/sorbet-issues#196
- dev test Test=spec/tapioca/compilers/dsl/active_record_enum_spec.rb
- dev style 
-  dev tc
> Extract ActiveRecord::Enum RBI generator into Tapioca

- lib/tapioca/compilers/dsl/active_record_scope.rb
- spec/tapioca/compilers/dsl/active_record_scope_spec.rb
resolves https://github.com/Shopify/sorbet-issues/issues/159
Done these points for the generator so far
1. A Shop::GeneratedRelationMethods module
2. Generate all the methods on the module.
- Test
- dev test  
- dev style
> Add Rails Model scope RBI generator

- README.md
Copied Ufuk's answer from this issue https://github.com/Shopify/tapioca/issues/79 into a wiki https://github.com/Shopify/tapioca/wiki/How-does-tapioca-compare-to-%22srb-rbi-gems%22-%3F
This PR creates a new header in the README.md to link to the wiki answer
> Link wiki response in README.md

- lib/tapioca/compilers/dsl/action_controller_helpers.rb
- lib/tapioca/compilers/dsl/action_mailer.rb
- lib/tapioca/compilers/dsl/active_record_associations.rb
- lib/tapioca/compilers/dsl/active_record_columns.rb
- lib/tapioca/compilers/dsl/active_record_enum.rb
- lib/tapioca/compilers/dsl/active_record_identity_cache.rb
- lib/tapioca/compilers/dsl/active_record_scope.rb
- lib/tapioca/compilers/dsl/active_record_typed_store.rb
- lib/tapioca/compilers/dsl/active_resource.rb
- lib/tapioca/compilers/dsl/active_support_current_attributes.rb
- lib/tapioca/compilers/dsl/base.rb
- lib/tapioca/compilers/dsl/frozen_record.rb
- lib/tapioca/compilers/dsl/smart_properties.rb
- lib/tapioca/compilers/dsl/state_machines.rb
- lib/tapioca/compilers/dsl/url_helpers.rb
- lib/tapioca/compilers/dsl_compiler.rb
- lib/tapioca/compilers/requires_compiler.rb
- lib/tapioca/constant_locator.rb
- lib/tapioca/core_ext/class.rb
- lib/tapioca/sorbet_config_parser.rb
- sorbet/rbi/shims/activerecord_typedstore.rbi
- sorbet/rbi/shims/generated_path_helpers_module.rbi
- sorbet/rbi/shims/generated_url_helpers_module.rbi
- sorbet/rbi/shims/sorbet.rbi
- sorbet/tapioca/require.rb
This PR makes a few fixes to ensure everything works properly on Core. I've also taken the opportunity to increase strictness of DSL compilers to `strict`.
It is best to review commit-by-commit
> Various fixes based on testing on Core

- lib/tapioca/compilers/symbol_table/symbol_generator.rb
I didn't explicitly test this solves the error as that work was already done
> Remove method shorthand syntax

- lib/tapioca/gemfile.rb
This is necessary for the cases where the location of the loaded file could end up being different from the gem path indicated by the spec file.
The solution is to walk up the parent folder hierarchy for a given file, until the desired gemspec file is matched. This is only performed for git gems.
> Start searching parent paths for gemspec in git gems

- lib/tapioca/cli.rb
- spec/tapioca/cli_spec.rb
Port of https://github.com/Shopify/spoom/pull/12.
> Add a `--version` option

- lib/tapioca/compilers/requires_compiler.rb
I pushed a change to cache bundler installed gems on `master` which ended up breaking tests. The change installs gems into the `vendor/bundle` folder. Even though `/vendor` is an `--ignore` flag in `sorbet/config`, our tests were somehow still being affected by the existence of the `vendor` folder.
I investigated the cause to Sorbet ignore matching not exactly working exactly like a regular expression match. Instead, it tries to match whole path segments unless the ignore path starts with a `/` character in which case it tries to match the prefix of relative paths.
The new implementation first tries to get the relative path of each found file to the working path. All matches are done against this relative path. For each ignore string, if it starts with a `/`, the first segment of the …
> Fix Sorbet ignore matching

- README.md
Add a few commands we forgot to add in previous changes.
> Update `--help` output in README

- Gemfile.lock
> Bump spoom

- README.md
Updates documentation for `-c` and `--cmd` flag to advise of deprecation. Also, adds a disclaimer at the top of the README
to warn that changes may occur before a v1.0.0 release.
> Add disclaimer and updates to README.md

- Gemfile.lock
- lib/tapioca/version.rb
> Bump version to v0.4.20

- Gemfile.lock
> Bump spoom to v1.1.2

- Gemfile.lock
- lib/tapioca/compilers/symbol_table/symbol_generator.rb
- sorbet/rbi/gems/rbi@0.0.3.rbi
- spec/support/repo/Gemfile.lock
> Bump rbi to v0.0.3

- lib/tapioca/compilers/dsl/sidekiq_worker.rb
- spec/tapioca/compilers/dsl/sidekiq_worker_spec.rb
If the various perform methods are overridden by a class then they will be statically available and there is no need to generate RBI for them. This pattern is used by some internal projects:
```ruby
class SomeWorker
include Sidekiq::Worker
def self.perform_async(repository_id:, after:, before:, ref:)
super
end
end
```
Also: Add a few more tests for sidekiq_worker generator
Don't generate the methods unless the owner is Sidekiq::Worker::ClassMethods
> Do not generate static artefacts for methods that are overriden

- Gemfile.lock
- lib/tapioca/generator.rb
- spec/support/repo/Gemfile
- spec/support/repo/config/application.rb
- spec/tapioca/cli/require_spec.rb
Propagate fix for https://github.com/Shopify/rbi/issues/78.
> Bump RBI to 0.0.4 and fix `rake` dependency

- Gemfile.lock
Update to v0.5.9152
Signed-off-by: Cory Hutchison <cory.hutchison@shopify.com>
> Bump `sorbet` and `sorbet-runtime`

- lib/tapioca/compilers/symbol_table/symbol_generator.rb
Increase strictness in this file to make it easier to maintain going forward.
> Move symbol_generator to typed strict

- Gemfile.lock
Signed-off-by: Cory Hutchison <cory.hutchison@shopify.com>
> Bump `rbi` to v0.0.5

- README.md
Looks as though the `README.md` usage docs haven't been updated since prior to migrating to the `gem` command. Updated the usage docs and removed references to `generate` and `sync`.
Updated `README.md`.
> Update `README.md` usage docs

- lib/tapioca/generators/base.rb
- lib/tapioca/generators/dsl.rb
- lib/tapioca/generators/gem.rb
- spec/tapioca/cli/dsl_spec.rb
- spec/tapioca/cli/gem_spec.rb
Closes: #551
Maintain consistency with our file IO in the application. Since we use `Thor` helpers for creating files, we should do the same for deleting files.
Removed custom logic for removing files and instead updated to use `Thor::Actions#remove_file` in its place.
> Replace `remove` method and use `remove_file`

- README.md
I wasn't a big fan of having a single note for one command about an option and neglecting the others. 
I removed the NOTE for the `gem` command and instead included the help docs for each individual command.
> Add command help docs to `README.md`

- .github/dependabot.yml
When adding a new label in #596, the default labels are no longer being applied.
Manually apply the default labels for Dependabot PRs to make them easy to discover.
> Re-add default labels for Dependabot PRs

- Gemfile.lock
Combines #601, #602
Upgrade Sorbet to 0.5.9318
> Upgrade Sorbet to 0.5.9318

- .spin/bootstrap
`spin`-ify the `tapioca` gem for development on Shopify's internal environment.
Add a `.spin/bootstrap` script to pull down the `libsqlite3-dev` library and install dependencies.
N/A
> Add spin bootstrap script

- Gemfile.lock
- sorbet/rbi/gems/rbi@0.0.8.rbi
- spec/tapioca/compilers/dsl/aasm_spec.rb
- spec/tapioca/compilers/dsl/active_record_enum_spec.rb
This new version of `rbi` fixes a bug in RBI sorting.
> Bump `rbi` to v0.0.8

- lib/tapioca/compilers/dsl/active_record_associations.rb
- spec/tapioca/compilers/dsl/active_record_associations_spec.rb
Fixes #603 
We were wrongly assuming that constantizing the class name of the reflection would be enough to find the target constant of the reflection. However, it turns out that what AR does is to call `compute_type` on the original model class, which ends up discovering the reflection target class by walking out of the namespaces of the original model.
We were not matching that behaviour in our check and thus generating the wrong RBI file as reported in #603.
Since the code to discover the correct class for the given reflection target is too complex to replicate in our codebase, I decided to catch the failure of calling `reflection.klass` and reporting a `NameError` raised by that call to mean that the target constant doesn't exist.
In order to do this properly, I had to refactor the …
> Fix reflection target class existence check

- lib/tapioca/generators/init.rb
Just a small refactor to encapsulate the decision of if the binstub is going to be created forcefully or not inside the method that does the work.
Refactor to merge two methods into one and make it decide on how to perform its operation internally.
Relies on existing tests.
> Simplify and encapsulate binstub creation logic

- lib/tapioca/compilers/dsl/base.rb
- lib/tapioca/compilers/symbol_table/symbol_generator.rb
Parameter name sanitization was not matching the whole parameter when it found an invalid portion in the name, so the replacement was getting spliced into the overall parameter name. Moreover, the code to check valid parameter name was not even consistent, which creates problems.
Extracted parameter name validation into a common method and started using it instead. The extracted method checks to see if the whole name is a series of alphanumeric or `_` characters to validate a parameter name.
Existing tests should catch regressions.
> Fix and improve method parameter sanitization

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- lib/tapioca/gemfile.rb
- spec/tapioca/compilers/dsl/action_mailer_spec.rb
- spec/tapioca/compilers/symbol_table_compiler_spec.rb
- spec/tapioca/gemfile_spec.rb
Now that Ruby 3.1 is released, we should start targeting it.
Add Ruby 3.1 to test matrix and fix problems.
No added tests.
> Start testing against Ruby 3.1

- lib/tapioca/rbi_ext/model.rb
Remove things that have been upstreamed.
> Clean useless things

- .rubocop.yml
- Gemfile
- Gemfile.lock
- spec/tapioca/cli/gem_spec.rb
- spec/tapioca/compilers/dsl/aasm_spec.rb
- spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
- spec/tapioca/compilers/dsl/action_mailer_spec.rb
- spec/tapioca/compilers/dsl/active_job_spec.rb
- spec/tapioca/compilers/dsl/active_model_attributes_spec.rb
- spec/tapioca/compilers/dsl/active_record_associations_spec.rb
- spec/tapioca/compilers/dsl/active_record_columns_spec.rb
- spec/tapioca/compilers/dsl/active_record_enum_spec.rb
- spec/tapioca/compilers/dsl/active_record_fixtures_spec.rb
- spec/tapioca/compilers/dsl/active_record_scope_spec.rb
- spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb
- spec/tapioca/compilers/dsl/active_resource_spec.rb
- spec/tapioca/compilers/dsl/active_storage_spec.rb
- spec/tapioca/compilers/dsl/active_support_concern_spec.rb
- spec/tapioca/compilers/dsl/active_support_current_attributes_spec.rb
- spec/tapioca/compilers/dsl/config_spec.rb
- spec/tapioca/compilers/dsl/frozen_record_spec.rb
- spec/tapioca/compilers/dsl/identity_cache_spec.rb
- spec/tapioca/compilers/dsl/mixed_in_class_attributes_spec.rb
- spec/tapioca/compilers/dsl/protobuf_spec.rb
- spec/tapioca/compilers/dsl/rails_generators_spec.rb
- spec/tapioca/compilers/dsl/sidekiq_worker_spec.rb
- spec/tapioca/compilers/dsl/smart_properties_spec.rb
- spec/tapioca/compilers/dsl/state_machines_spec.rb
- spec/tapioca/compilers/dsl/url_helpers_spec.rb
- spec/tapioca/compilers/requires_compiler_spec.rb
Addresses https://github.com/Shopify/tapioca/pull/729#issuecomment-1022476138.
> Add rubocop rules for RSpec

- .rubocop.yml
Handle https://github.com/Shopify/tapioca/pull/747#discussion_r793907161.
> Remove MFA cop rule

- lib/tapioca/compilers/symbol_table_compiler.rb
Address https://github.com/Shopify/tapioca/pull/769#pullrequestreview-868301915.
> Rename symbol_ignored? -> symbol_in_payload?

- Gemfile.lock
- lib/tapioca/compilers/gem/listeners/yard_doc.rb
- spec/tapioca/compilers/symbol_table_compiler_spec.rb
> Also generate Yard @annotations

- lib/tapioca/dsl/compiler.rb
- lib/tapioca/dsl/compilers/aasm.rb
- lib/tapioca/dsl/compilers/action_controller_helpers.rb
- lib/tapioca/dsl/compilers/action_mailer.rb
- lib/tapioca/dsl/compilers/active_job.rb
- lib/tapioca/dsl/compilers/active_model_attributes.rb
- lib/tapioca/dsl/compilers/active_model_secure_password.rb
- lib/tapioca/dsl/compilers/active_record_associations.rb
- lib/tapioca/dsl/compilers/active_record_columns.rb
- lib/tapioca/dsl/compilers/active_record_enum.rb
- lib/tapioca/dsl/compilers/active_record_fixtures.rb
- lib/tapioca/dsl/compilers/active_record_relations.rb
- lib/tapioca/dsl/compilers/active_record_scope.rb
- lib/tapioca/dsl/compilers/active_record_typed_store.rb
- lib/tapioca/dsl/compilers/active_resource.rb
- lib/tapioca/dsl/compilers/active_storage.rb
- lib/tapioca/dsl/compilers/active_support_concern.rb
- lib/tapioca/dsl/compilers/active_support_current_attributes.rb
- lib/tapioca/dsl/compilers/config.rb
- lib/tapioca/dsl/compilers/frozen_record.rb
- lib/tapioca/dsl/compilers/identity_cache.rb
- lib/tapioca/dsl/compilers/mixed_in_class_attributes.rb
- lib/tapioca/dsl/compilers/protobuf.rb
- lib/tapioca/dsl/compilers/rails_generators.rb
- lib/tapioca/dsl/compilers/sidekiq_worker.rb
- lib/tapioca/dsl/compilers/smart_properties.rb
- lib/tapioca/dsl/compilers/state_machines.rb
- lib/tapioca/dsl/compilers/url_helpers.rb
Make it more obvious what this type member is about.
> Rename `Dsl::Compiler::Elem` into `ConstantType`

- lib/tapioca/commands/dsl.rb
Left over from https://github.com/Shopify/tapioca/pull/792.
> Fix path to dsl extensions

- Gemfile.lock
https://github.com/sparklemotion/nokogiri/releases/tag/v1.13.3 Release notes, there was a regression, likely won't effect us. But easy update.
`bundle update nokogiri`
> Bump `nokogiri` to v1.13.3

- Gemfile.lock
- lib/tapioca/helpers/sorbet_helper.rb
- sorbet/rbi/gems/spoom@1.1.9.rbi
So we also get the [`exit_code` for free](https://github.com/Shopify/spoom/blob/main/lib/spoom.rb#L18) and can act accordingly.
> Run Sorbet using Spoom's helper

- .vscode/extensions.json
Add our extension pack as a recommended extension in Tapioca.
> Add the extension pack as a recommended extension

- README.md
- lib/tapioca/cli.rb
https://www.merriam-webster.com/dictionary/suppress
> Fix typo in `--quiet` option description

- lib/tapioca/compilers/dsl/protobuf.rb
- spec/tapioca/compilers/dsl/protobuf_spec.rb
fixes #604
include the enum modules in list of constants, and generate rbi files for them
added additional assertions to existing protobuf tests
> Generate enum module definitions, and use symbols as then return value for methods which get/set enums

- spec/tapioca/gem/pipeline_spec.rb
A recent [change in Rails][0] has stopped loading core extensions to `String` very early. These tests were failing because of that change on Rails main builds.
[0]: https://github.com/rails/rails/commit/0170745b376acd150fec5f8cc57253cc1ffe0cf2
The best solution to this is to filter those constants in the compiled output, since these constants are not primary things being tested in those tests anyway.
Just updates to existing tests.
> Filter ActiveSupport `String` extensions in tests

- dev.yml
We're using GitHub Actions, not Travis CI.
Deleted the lines
Not applicable.
> Remove Travis CI mention in `dev.yml`

- spec/tapioca/dsl/compilers/active_record_delegated_types_spec.rb
Simplifying tests as mentioned here: https://github.com/Shopify/tapioca/pull/1241#discussion_r1047262873
Remove unneeded `describe` and `before` blocks
Already test changes
> Simplify test by removing unnecessary describe/before blocks

- lib/tapioca/loaders/loader.rb
Fix #1391 
It is simpler to iterate over all the engines and add their eager load directories to a fresh Zeitwerk::Loader instance.
When doing this, we need to be careful to not add a directory to our loader that is already managed by another loader. So, we collect all the directories that are already managed by all existing loaders and skip those directories when adding them to our loader.
Existing tests pass.
I asked @tonybruess who reported #1391 to test this branch and confirmed that it fixes his problem. I've also asked @jeffcarbs to test it on Gusto and tested it myself on Core, without any problems during loading.
> Stop trying to mimic Rails and do the simpler Zeitwerk autoloading

- .vscode/launch.json
Closes https://github.com/Shopify/ruby-dev-exp-issues/issues/746
Configure for easy debugging using the VS Code UI.
> Add launch config for debugging in VS Code

- Gemfile
I'm not sure why the Tapioca Gemfile was formatted this way, but it's bit unusual, let's use the normal style?
n/a
n/a
> Format Gemfile

- .github/workflows/ci.yml
We've stopped testing against Ruby HEAD, and it is always good practice to catch any failures on Ruby HEAD early.
Add `head` to the build matrix and mark it as experimental.
No new tests.
> Starting testing against Ruby Head again

- lib/tapioca/gem/pipeline.rb
Our Ruby head builds had been failing since https://github.com/ruby/ruby/pull/8070 was merged.
https://bugs.ruby-lang.org/issues/19755 introduced adding caller location as the default source location for `eval` and `class_eval` calls. Tapioca was not using this new extra information to disambiguate between different `eval` calls, which caused it to generate incorrect RBI files on Ruby 3.3 dev.
The implementation tries to parse out the caller location from the new `(eval at /path/to/file.rb:123)` format and uses that information to check if the constant is defined by file or not.
No added tests, fixes existing ones.
> Fix evals with automatic source location in Ruby 3.3

- lib/tapioca/dsl/compilers/active_record_relations.rb
- spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Fixes https://github.com/Shopify/tapioca/issues/1841.
> Fix ActiveRecordRelations compiler

- lib/tapioca/dsl/compilers/active_record_relations.rb
- spec/tapioca/dsl/compilers/active_record_relations_spec.rb
Similar to https://github.com/Shopify/tapioca/pull/1830 and https://github.com/Shopify/tapioca/pull/1844
Based on examples from https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-count
Updated tests.
> Update Active Record count sig to allow a block

- README.md
- lib/tapioca/dsl/compilers/action_controller_helpers.rb
- lib/tapioca/dsl/compilers/active_model_secure_password.rb
- lib/tapioca/dsl/compilers/active_record_relations.rb
- lib/tapioca/dsl/compilers/active_record_typed_store.rb
- lib/tapioca/dsl/compilers/config.rb
- lib/tapioca/dsl/compilers/protobuf.rb
- lib/tapioca/runtime/generic_type_registry.rb
- lib/tapioca/static/requires_compiler.rb
- manual/compiler_activerecordrelations.md
- manual/compiler_activerecordtypedstore.md
- spec/tapioca/cli/dsl_spec.rb
- spec/tapioca/dsl/compilers/active_record_columns_spec.rb
- spec/tapioca/dsl/compilers/smart_properties_spec.rb
- spec/tapioca/dsl/compilers/url_helpers_spec.rb
- spec/tapioca/gem/pipeline_spec.rb
> Fix various typos

- .vscode/settings.json
We wanted to experiment with having this setting always enabled but it's no longer necessary.
> Remove sorbet.highlightUntyped setting

- lib/ruby_lsp/tapioca/addon.rb
- lib/ruby_lsp/tapioca/server_addon.rb
- lib/tapioca/cli.rb
- lib/tapioca/commands/abstract_dsl.rb
- lib/tapioca/dsl/compiler.rb
- lib/tapioca/dsl/pipeline.rb
- lib/tapioca/loaders/dsl.rb
- tasks/readme.rake
Cleaned up and brought changes from https://github.com/Shopify/tapioca/compare/main...ko/tapioca-lsp
Tested briefly manually, not extensive.
> [Tapioca add-on] Generate DSL RBIs in add-on mode

- lib/tapioca/dsl/compilers/active_record_relations.rb
- spec/tapioca/dsl/compilers/active_record_relations_spec.rb
https://github.com/Shopify/tapioca/pull/2153#issuecomment-2596322153
> Return a Hash from `GroupChain#size`

- Gemfile
- Gemfile.lock
- sorbet/rbi/gems/ruby-lsp-rails@0.4.0.rbi
- sorbet/rbi/gems/ruby-lsp@0.23.9.rbi
We no longer need to point to the GitHub repo, the gem is already released.
> Point Rails add-on to released version

- lib/ruby_lsp/tapioca/addon.rb
Includes a bug fix for crashing when no eligible constants were found for DSL generation
> Bump add-on version to v0.1.3

- lib/tapioca/loaders/loader.rb
See https://github.com/Shopify/tapioca/pull/2283#issuecomment-2898943369
> Improve engine loading with Zeitwerk

- README.md
Resolves https://github.com/Shopify/tapioca/issues/2294
> Mention ability to supply local annotations in README

- lib/tapioca/bundler_ext/auto_require_hook.rb
- lib/tapioca/commands/abstract_dsl.rb
- lib/tapioca/commands/abstract_gem.rb
- lib/tapioca/commands/command.rb
- lib/tapioca/commands/command_without_tracker.rb
- lib/tapioca/dsl/compiler.rb
- lib/tapioca/gem/events.rb
- lib/tapioca/gem/listeners/base.rb
- lib/tapioca/helpers/cli_helper.rb
- lib/tapioca/helpers/config_helper.rb
- lib/tapioca/helpers/env_helper.rb
- lib/tapioca/helpers/rbi_files_helper.rb
- lib/tapioca/helpers/test/content.rb
- lib/tapioca/helpers/test/dsl_compiler.rb
- lib/tapioca/helpers/test/isolation.rb
- lib/tapioca/helpers/test/template.rb
- lib/tapioca/loaders/loader.rb
- lib/tapioca/runtime/attached_class_of_legacy.rb
- lib/tapioca/runtime/trackers/tracker.rb
Result of running `spoom srb sigs translate`
> Translate class helpers to RBS comments
