lib/tapioca/compilers/symbol_table/symbol_generator.rb

It is sometimes the case that `pry` returns a match that does not live in the gem folder, but our `ConstantLocator` can locate it to the correct file. A case in point is `ActiveStorage::Current`, which, as far as `pry` is concerned is defined in the file `activesupport/lib/active_support/current_attributes.rb` but is actually defined in `activestorage/app/models/active_storage/current.rb`, which is properly located by our `ConstantLocator` (thanks to `TracePoint`).
Thus, instead of falling back from one to the other, we need to consider the whole set of results as one and see if any of them match a file under the current gem folder.

Make file matching more accepting

---

README.md
lib/tapioca/cli.rb
lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

- Make the default post-require script `sorbet/tapioca/require.rb`
- Add an `init` command to create a basic `sorbet` folder structure with:
- `sorbet/config` with contents `--dir=.`
- `sorbet/tapioca/require.rb` with empty contents

Pre-release minor refinements

---

lib/tapioca/loader.rb
spec/tapioca/cli_spec.rb

We had a problem where the default post-require script `sorbet/tapioca/require.rb` was creating a problem with `require` since `require("sorbet/tapioca/require.rb")` was searching for a file in the include path. Converting the require path to an absolute path fixes this problem.
The tests have been updated to perform a `tapioca init` before each run to ensure a `sorbet/tapioca/require.rb` file exists so that we actually do test this case and catch the error.

Convert pre/post-require paths to absolute paths

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
lib/tapioca/gemfile.rb
lib/tapioca/generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

This fixes API differences between ruby 2.4 and >= 2.5. I'm not too happy about the hack to remove the self.inspect differences between 2.4 and others but it seemed like a small contained hack.
Let me know what you think.

These are the changes I needed to make to get it to work on 2.4.6

---

spec/tapioca/cli_spec.rb

While testing locally with the `rake` command, I noticed that some artefacts were not cleaned after the tests:
* `spec/support/repo/sorbet/config`
* `spec/support/repo/sorbet/tapioca/require.rb`
This PR removes them after each test.
Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>

Remove support artefacts before and after all tests

---

spec/tapioca/compilers/symbol_table_compiler_spec.rb

Using ERB templates when matching RBI generation output allows us to change the output matching depending on some external conditions  like Ruby version, if a constant is defined in a certain type or if a certain module is included in a certain class, etc.
This PR adds this functionality.

Turn RBI generation test case outputs to templates

---

Gemfile.lock
lib/tapioca.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb
tapioca.gemspec

From [Zeitwerk documentation:](https://github.com/fxn/zeitwerk#supported-ruby-versions)
> Zeitwerk works with MRI 2.4.4 and above.
This make it difficult to use `tapioca` on Ruby 2.3.
After discussing with @paracycle, seems like Zeitwerk is not absolutely mandatory for this project and we can do manual requires since there are only a few files. This is the goal of this PR.

Remove dependency to Zeitwerk so we can support Ruby 2.3

---

spec/spec_helper.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

We also need it from `cli_spec.rb` for variations with Ruby 2.3.
Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>

Move templating features to `RSpec::Matchers` so it can be used from any test file

---

.travis.yml
spec/tapioca/cli_spec.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb
tapioca.gemspec

This PR contains the few tweaks needed to support Ruby 2.3.x.
Please disregard the first commit as it's coming from #19.

Add support for Ruby 2.3(.7)

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

This addresses https://github.com/Shopify/tapioca/issues/23
This works around the case where a gem has defined a `singleton_class`
method with a different method signature (and potenitally different visibility) to the one that's defined on `Object`
This is an approach that is sometimes used to allow access to the singleton class of an object in Rubies pre 2.1.0
When generating `rbi` files we always want to use the result of `Object#singleton_class`

Call `singleton_class` on Object explicitly

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb

Avoid crash caused by frozen string modification.
For example while trying to update the `graphql-metrics` gem RBI to 3.0.0 in this branch https://github.com/Shopify/shopify/pull/226539.
The error is:
```
-> Moving: sorbet/rbi/gems/activemerchant@1.99.0.rbi to sorbet/rbi/gems/activemerchant@1.103.0.rbi
Compiling activemerchant, this may take a few seconds... bundler: failed to load command: tapioca (/Users/chris/.gem/ruby/2.6.5/bin/tapioca)
FrozenError: can't modify frozen String
/Users/chris/.gem/ruby/2.6.5/gems/tapioca-0.2.3/lib/tapioca/compilers/symbol_table/symbol_generator.rb:403:in `prepend'
/Users/chris/.gem/ruby/2.6.5/gems/tapioca-0.2.3/lib/tapioca/compilers/symbol_table/symbol_generator.rb:403:in `compile_method'
/Users/chris/.gem/ruby/2.6.5/gems/tapioca-0.2.3/lib/tapioca/compiler …
```

Avoid modifying the frozen string `method_name`.

---

Gemfile.lock
tapioca.gemspec

Remove thor dependency requirement upperbound:
- ### Problem
Rails made thor 1.0 a dependency requirement. Application
using Rails HEAD and taopica can't have their dependencies resolved
since there is a version conflict.
I couldn't find a reason in the history on why we added a upperbound
requirement on thor so I'm just removing it. It will make things
easier for applications next time thor release a new version.

Remove thor dependency requirement upperbound:

---

README.md

It's only a cosmetic/documentation change.
As both syntaxes are already recognized by `thor` no further changes are needed.
Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>

Use elegant dashes instead of ugly underscores in options documentation

---

lib/tapioca/gemfile.rb

Tapioca ignores gems that live under the application folder since those gems should get type-checked along with other application code. However, that assumption breaks if developers have installed gems into a `vendor` folder inside application directory.
In that case, Sorbet would not (or should not) be type-checking those gem files but would still need their RBIs. Thus, we should only ignore gems that live in the application folder but are not in the Bundler install path.
This PR implements that new behaviour.

Stop ignoring gems if they are vendored into the application folder

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
lib/tapioca/gemfile.rb
spec/support/repo/Gemfile

@rafaelfranca observed a case with a non-Nixified repo where the path to the `psych` gem as it was supplied by `Bundler`, was a non-existent path. This obviously breaks the `File.realpath` lookup and fails the run.
The fix is to check for path existence before attempting to convert the path to a realpath. If the path does not exist, we fallback to the old flow.
- This change was tested and verified by @rafaelfranca on the repo he ran into problems
- I've also added `psych` to the test repo `Gemfile` to make sure that we run into the same problem and verified that this change fixes tests.

Fix realpath problems with some gems

---

lib/tapioca/cli.rb
lib/tapioca/config.rb
lib/tapioca/config_builder.rb
lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

It is sometimes desirable to exclude certain gems from the RBI generation process. This PR adds the `--exclude` flag to both `generate` and `sync` commands to cater for this use case.

Add `--exclude` option

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Fixes: #33 
We should not be generating constants of types or mixins exported by `sorbet-runtime` in RBI files. First of all, those constants and mixins have no additional signal value in the generated RBI file (since RBI files are only processed by the static checker) and they create conflicts with the actual definitions of the types, like in #33.

Filter Sorbet related types from constants and mixins

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

The current state of `mixes_in_class_methods` discovery is subpar and can only detect ones coming from the usage of `ActiveSupport::Concern`. However, there is a chance to do better and this PR is an attempt to implement that.
The basic idea is to have a temporary empty class template that we include any `module` we find. The empty class template does two things:
1. It defines `method_missing` both on the instance and class level so that we can ignore calls to some expected methods on the including class coming from some modules as they are being includes/extended. For example, `IdentityCache` just plain assumes that it will be able to call some AR methods in the `self.included` block. Implementing an empty `method_missing` allows those calls to happen in a no-op manner.
2. It hooks the …

Better `mixes_in_class_methods` detection

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Since Rails 6.1, the `delegate` [implementation](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/delegation.rb#L204-L205) uses the Ruby 2.7 `...` passthrough syntax to define the delegation method.
The method using the `...` is then eval'ed in the module context which end up being represented as:
```ruby
def delegator(*, &); end
```
Which in turn produces the following RBI with `tapioca`:
```ruby
def delegator(**, &&); end
```
This PR fixes the generated RBI by sanitizing the parameter names.
Note: I didn't add any test for the non-metaprogrammed following code
```ruby
class Foo
def foo(...); end
end
```
as Sorbet doesn't support it yet and it's never loaded in the symbol table thus generating an empty RBI. This will be handled later.

Sanitize parameter names

---

lib/tapioca/compilers/symbol_table/symbol_loader.rb
spec/support/repo/Gemfile
spec/tapioca/cli_spec.rb

When used with the [extras](https://rubygems.org/gems/extras/versions/0.3.0) gem, `tapioca` crashes with:
```
/gems/extras-0.3.0/lib/extras/shell.rb:43:in `escape': undefined method `gsub' for #<Pathname:0x00007fb523a32840> (NoMethodError)
```
This actually hides two problems.
1. What happens is that `extras` aliases the `shellescape` method for [its own](https://github.com/envygeeks/extras/blob/master/lib/extras/shell.rb#L49) that doesn't support `Pathname`.
This is fixed by this PR by only escaping the filename only and not all the other arguments we control.
2. Extras also [redefines the escaped value for the empty string](https://github.com/envygeeks/extras/blob/master/lib/extras/shell.rb#L27) which ends up running sorbet with no argument at all and produce an error.
This PR fixes it …

Be *extras* careful

---

lib/tapioca/compilers/dsl/smart_properties.rb
spec/spec_helper.rb
spec/tapioca/cli_spec.rb
spec/tapioca/compilers/dsl/frozen_record_spec.rb
spec/tapioca/compilers/dsl/smart_properties_spec.rb

calling `expect` inside a child process prevents rspec from reporting any failures

fix rspec failure reporting

---

spec/spec_helper.rb
spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
spec/tapioca/compilers/dsl/action_mailer_spec.rb
spec/tapioca/compilers/dsl/frozen_record_spec.rb
spec/tapioca/compilers/dsl/smart_properties_spec.rb
spec/tapioca/compilers/dsl/state_machines_spec.rb

continuation of https://github.com/Shopify/tapioca/pull/59 where we were having problems with rspec reporting the test failures. This PR removes the `expect` call out of the child process.
In order to more easily extract output from the child processes they are parsed as YAML and then outputted as an array of strings using `YAML#load`

Report test failures correctly

---

lib/tapioca/compilers/dsl/active_record_associations.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

This PR aims to extract our RBI generator for ActiveRecord DSL's from shopify core into tapioca. Specifically the DSL for associations.
Added tests to the existing generator
resolves Shopify/sorbet-issues#189

Extract ActiveRecordAssociations DSL Generator

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

There have been cases where signature generation was erroring out due to unloadable constants in some gem. Since signature generation is not an essential part of the operation, we can easily silence the exceptions we are getting during the process and act like there were no signatures.

Make signature generation safer

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/cli_spec.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Currently, `tapioca` is not generating `protected` or `private` class methods of modules/classes. However, that ends up being a problem when a user type is inheriting from or mixing in a class/module and tries to use its protected/private methods. In those cases, Sorbet would complain about missing methods since `tapioca` would not have generated the methods used. For example:
```ruby
class Base
class << self
private
def activate!
end
end
end
class Sub < Base
activate!
end
```
would cause a `Method activate! does not exist on T.class_of(Sub)` error.
The solution is to also generate the protected and private class methods too. However, we can't do that and still continue to generate methods using the visibility sections, since they don't apply to class methods defined using `self.`.
Thus, …

Improve method generation

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Fixes: https://github.com/Shopify/tapioca/issues/91
We were checking that the `constant` under examination was subclassing from `T::Struct`. However, other use cases where classes `extend T::Props::ClassMethods` are also possible, like the usage in https://github.com/Shopify/maestro/blob/master/lib/maestro/base.rb#L15
The fix is to explicitly check that the class extends from `T::Props::ClassMethods` and that the method is one of the `const` or `prop` methods.

Start checking for props using `T::Props::ClassMethods`

---

README.md

This PR resolves [issue #194](https://github.com/Shopify/sorbet-issues/issues/194)
Add a description on `tapioca` support for strict type and the usage of `StongTypeGeneration` module.

Add documentation for strict type support

---

lib/tapioca/compilers/dsl/active_record_columns.rb
sorbet/rbi/shims/sorbet.rbi
spec/tapioca/compilers/dsl/active_record_columns_spec.rb

As I was testing the generators on Core, I ran into two problems with the custom column type mapping:
1. The column type definitions are passed as object instances and not classes. We were not handling them correctly.
2. If columns are mapped to generic types, we can't do the mapping correctly since type parameter information is lost.
This PR fixes these problems.

A few fixes for custom column type mapping

---

lib/tapioca/compilers/dsl/base.rb
lib/tapioca/gemfile.rb

We now have some runtime components in the form of RBI generators, so we need to start generating an RBI file for tapioca itself.

Start generating tapioca RBI

---

lib/tapioca/gemfile.rb
spec/support/repo/Gemfile
spec/tapioca/cli_spec.rb

Git gems usually do not change version numbers but they might still have changes if not fixed to a specific SHA. Thus, it makes more sense to track those gems' versions as the gem version plus the git revision they are at as installed on the system.

Add revision for git gems

---

lib/tapioca/compilers/dsl/url_helpers.rb
spec/tapioca/compilers/dsl/url_helpers_spec.rb

`ActionDispatch::IntegrationTest` and `ActionView::Helpers` bring url helpers with them but don't necessarily include the url helper modules themselves (they either delegate to the actual modules or mix them into includers dynamically). Thus, we cannot discover that these modules include any url helpers.
However, we do want these modules to act like they include url helper modules, so we have to add them to the gathered constants list manually and also make sure that we generate the module includes for them unconditionally.
So far, we had been adding `ActionDispatch::IntegrationTest` to the gathered constants list manually, but we hadn't been checking if the appropriate module includes were being generated for it (surprise: they weren't). So, this commit adds tests to make sure that we …

Generate proper url helper RBIs for non-discoverable modules

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Normally `attr_writer` generated methods do not have a name for the single parameter that the method accepts. However, if the `attr_writer` has a signature, then the parameter name should be the name of the attribute.
We have been defaulting the parameter name to `_` if the parameter name didn't exist. But, as outlined above, if the writer method has a signature, that ends up meaning that the parameter name in the signature does not match the one in the method definition.
This commit fixes that by trying to detect writer methods with a signature and naming the parameter properly in those cases.
I fixed the test we have for signature generation to ensure that we generate the correct thing.

Fix parameter names for attr writers with signature

---

lib/tapioca/cli.rb
spec/tapioca/cli_spec.rb

The sigil order don't comply with our Rubocop rule. Since this project and the Rubocop-sorbet one are both owned by Shopify, I'd like to have some consistency as otherwise running `tapioca generate rbis` would fail ruby lint out of the box.
Ref https://github.com/Shopify/rubocop-sorbet/blob/7cc2c9fbfd1f4fb4f2e052726e5b745e0235cbae/lib/rubocop/cop/sorbet/sigils/enforce_sigil_order.rb

Modify sigil order in the `config/tapioca/require.rb` to comply with our own Ruby styleguide

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

As reported by @Edouard-chin, `tapioca` produces incorrect RBIs for methods using `T.attached_class` in their signatures: https://buildkite.com/shopify/shopify-rails-canary-app/builds/314#440cc1e8-c24f-4164-876c-344b3b462c9b
For example, with the following code:
```ruby
class Foo
class << self
extend(T::Sig)
sig { returns(T.attached_class) }
def a
Foo.new
end
end
end      
```
Tapioca will produce the following RBI:
```ruby
sig { returns(AttachedClass) } # should be T.attached_class
def a; end
```
This is actually the value returned by sorbet-runtime itself:
```ruby
require 'sorbet-runtime'
class Foo
class << self
extend T::Sig
sig { returns(T.attached_class) }
def foo
Foo.new
end
end
end
m = Foo.method(:foo)
puts T::Private::Methods.signature_for_method(m).return_type # AttachedClass
``` …

Fix RBI generation for T.attached_class

---

lib/tapioca/compilers/dsl/active_record_columns.rb
spec/tapioca/compilers/dsl/active_record_columns_spec.rb

All the ActiveRecord methods used to access the previous change state of a column can actually return `nil`.
For example:
```ruby
class Foo < ApplicationRecord; end
foo = Foo.new(name: "foo")
foo.name_previous_change # => nil
```
This pull-request uses `T.nilable` as return type for all the impacted methods.

ActiveRecord changes return nilable types

---

lib/tapioca/compilers/dsl/active_record_associations.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

Active Record model objects exhibit different type behaviour in different contexts. For an Active Record model that is created in memory, the attributes and associations can all be `nil`. The strict typing on the object properties are only applied when a model is read from the database.
The signature generation code was looking at the database column nilability to understand if the association property returns a nilable type or not. It turns out that that is not the correct way to represent the association method return types, since this is totally valid Ruby on Rails code:
```ruby
class Model < ActiveRecord::Base
belongs_to :foo
end
model = Model.new
model.foo #=> nil
```
even when the database column that the `foo` association maps to is strictly not nilable.
Thus, the solution is to …

Make all `belongs_to` associations return nilable types

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Fixes #116
There were a couple of problems with parameter handling in signatures:
1. We were messing up the parameter ordering in the signature which sometimes ended up not matching with the order in which parameters were declared in the method parameter list. 
2. We were skipping `keyrest` arguments completely. :facepalm:
The main problem is fixed by iterating over the actual method parameters and only using signature parameter mapping as a lookup table to get the relevant type for the parameter. I had to keep a sanitized version of the parameter list to pass to the signature compile step, since we end up modifying the parameter names while generating the method definition. The parameter name in the signature should match that changed name, so the sanitized parameter list should be used …

Fix parameter handling in signatures

---

.github/dependabot.yml

This uses Dependabot version 2. Which seems to slightly differ from version 1 in terms of the config. I also didn't have to enable Shopify's dependabot in this repo since it's acquired by Github it's available to everyone for free. I assume this is an acceptable way of enabling Dependabot within Shopify.
Validated the config with https://dependabot.com/docs/config-file-beta/validator/ 
I'll keep an eye out and modify the config if it's not working as intended in the next week.
resolves https://github.com/Shopify/sorbet-issues/issues/72

Add dependabot to trigger CI run against new versions of Sorbet

---

.github/dependabot.yml

Specifying `sorbet` already pulls in changes for `sorbet-static` therefore it's unnecessary to specify both

Remove unnecessary dependency from dependabot config

---

lib/tapioca/compilers/dsl/active_record_identity_cache.rb
spec/tapioca/compilers/dsl/active_record_identity_cache_spec.rb

This is a leftover from #112.
As we can see [here](https://github.com/Shopify/tapioca/blob/master/lib/tapioca/compilers/dsl/active_record_identity_cache.rb#L146) this will create a method for each field `def fetch_X` that [still returns a non-nilable value](https://github.com/Shopify/tapioca/blob/master/lib/tapioca/compilers/dsl/active_record_identity_cache.rb#L129).
This PR fixes this problem and updates the tests.

Fix IdentityCache `fetch_X` method return to be nilable

---

lib/tapioca/compilers/dsl/active_record_associations.rb
manual/generator_activerecordassociations.md
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

The return value of ActiveRecord singular builder methods
(`build_#{name}`, `create_#{name}`, `create_#{name}!`) were incorrectly
considered nilable. Their actual value is always of the association's class,
never nil.
[`ActiveRecord::Associations::ClassMethods`](https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to)'s documentation never mentions `nil`.

Make AR association builder non-nilable

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

In its current state, Tapioca does not produce default values for `T::Struct` in gems RBI.
So for the following code in a gem:
```rb
class Foo < T::Struct
const :a, String, default: "a"
end
```
Tapioca will generate the following RBI:
```rbi
class Foo < T::Struct
const :a, String
end
```
Which will make valid uses of the `Foo` struct in clients wrongly invalid:
```rb
Foo.new # error: missing parameter `:a`
```
This PR allows Tapioca to produce default values when needed by the original implementation:
```rbi
class Foo < T::Struct
const :a, String, default: T.unsafe(nil)
end
```
We use `T.unsafe(nil)` because the `default` field in the struct can contains anything from a primitive data type to a complex statement but since we explore the gem through meta-programming we only see the …

Add support for T::Struct default values in gem RBI generation

---

lib/tapioca/compilers/dsl/active_record_identity_cache.rb
spec/tapioca/compilers/dsl/active_record_identity_cache_spec.rb

IdentityCache has a valid use case where classes only include `IdentityCache::WithoutPrimaryIndex` https://github.com/Shopify/identity_cache/blob/master/lib/identity_cache/without_primary_index.rb
We should support this in the generator as well

Gather IdentityCache::WithoutPrimaryIndex classes

---

lib/tapioca/compilers/dsl/base.rb

To prevent duplicate hash key parameters such as this: https://buildkite.com/shopify/shopify-sorbet/builds/196718#9ec135db-8b8d-4d8c-94f2-4ccdb6279f10/28-29
I tested the change in core:
```
sig { params(_0: T.untyped, _1: T.untyped).returns(::ActionMailer::MessageDelivery) }
def self.method(*_0, &_1); end
```
I contemplated between keeping an extra counter: 
```
pattern = /&|\*/
if pattern.match?(name)
name = name.to_s.gsub(pattern, "_#{i}") # avoid incorrect names from `delegate`
end
```
So that we don't end up in situations such as `def foo(a, b, *_2, &_3)`. I don't have a preference I can do this one too if it's better.

Append index to splat and block parameters

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

These empty `.params()` calls are now causing type-checking errors in more recent versions of Sorbet. For `sig` blocks, we never generate empty params calls, but since `T.proc` calls end up serializing
themselves, we need to remove all such empty params calls.

Start filtering empty params calls

---

lib/tapioca/compilers/dsl/base.rb
lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/dsl/action_mailer_spec.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

The previous PR has changed the parameter names to `_0`, `_1`, etc but there is a risk that these will conflict with numbered parameters introduced in Ruby 2.7. Instead, naming them `_arg0`, `_arg1`, etc seems more explicit and more readable.
We also need to do the same fallback mechanism in the symbol table generator code as well, so this PR adds that too.
I have added explicit delegation tests (both the Rails kind and Ruby 2.7 kind) in Action Mailer generator to make sure we don't regress. I have also updated the relevant tests in symbol table compiler.

Improve fallback parameter names

---

Gemfile.lock
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Bump spoom to https://rubygems.org/gems/spoom/versions/1.0.6

Bump spoom to v1.0.6

---

lib/tapioca/compilers/dsl/active_record_associations.rb

We've got reports of `tapioca dsl` failing with:
```
undefined method constructable?' for #<ActiveRecord::Reflection::BelongsToReflection> (NoMethodError)`
```
This seems to be related to an API change on Rails master: https://github.com/rails/rails/commit/371b4800266cbf1c659a9068f58412cb7a88e244
This PR uses `polymorphic?` instead of the now removed `constructable?` method.

Use `polymorphic?` instead of `constructable?`

---

.rubocop.yml

Rubocop should target the minimum ruby version required by the gem.
Updated `.rubocop.yml` to match the minimum required by `tapioca.gemspec`.
None, but this can be enforced by enabling `Gemspec/RequiredRubyVersion`. I recommend doing so in https://github.com/Shopify/ruby-style-guide

Make Rubocop TargetRubyVersion match gemspec

---

lib/tapioca/compilers/dsl/action_controller_helpers.rb
spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb

```
$ bundle exec tapioca dsl
Loading Rails application... Done
Loading DSL generator classes... Done
Compiling DSL RBI files...
bundler: failed to load command: tapioca (/Users/jeffreygoldsmith/.gem/ruby/2.6.6/bin/tapioca)
NameError: wrong constant name #<Class:0x00007f84c8f15550>
/Users/jeffreygoldsmith/.gem/ruby/2.6.6/gems/parlour-2.1.0/lib/parlour/rbi_generator/namespace.rb:101:in `const_get'
/Users/jeffreygoldsmith/.gem/ruby/2.6.6/gems/parlour-2.1.0/lib/parlour/rbi_generator/namespace.rb:101:in `block in path'
/Users/jeffreygoldsmith/.gem/ruby/2.6.6/gems/parlour-2.1.0/lib/parlour/rbi_generator/namespace.rb:100:in `times'
/Users/jeffreygoldsmith/.gem/ruby/2.6.6/gems/parlour-2.1.0/lib/parlour/rbi_generator/namespace.rb:100:in `each' …
```

Ignore ActionControllerHelpers DSL generation for anonymous classes

---

lib/tapioca/compilers/dsl/action_controller_helpers.rb
lib/tapioca/compilers/dsl/action_mailer.rb
lib/tapioca/compilers/dsl/active_record_associations.rb
lib/tapioca/compilers/dsl/active_record_columns.rb
lib/tapioca/compilers/dsl/active_record_enum.rb
lib/tapioca/compilers/dsl/active_record_scope.rb
lib/tapioca/compilers/dsl/active_record_typed_store.rb
lib/tapioca/compilers/dsl/active_resource.rb
lib/tapioca/compilers/dsl/active_support_current_attributes.rb
lib/tapioca/compilers/dsl/frozen_record.rb
lib/tapioca/compilers/dsl/identity_cache.rb
lib/tapioca/compilers/dsl/state_machines.rb
lib/tapioca/compilers/dsl/url_helpers.rb
manual/generator_actioncontrollerhelpers.md
manual/generator_activerecordassociations.md
manual/generator_activerecordcolumns.md
manual/generator_activerecordenum.md
manual/generator_activerecordscope.md
manual/generator_frozenrecord.md
manual/generator_statemachines.md
spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb
spec/tapioca/compilers/dsl/active_record_columns_spec.rb
spec/tapioca/compilers/dsl/active_record_enum_spec.rb
spec/tapioca/compilers/dsl/active_record_scope_spec.rb
spec/tapioca/compilers/dsl/frozen_record_spec.rb
spec/tapioca/compilers/dsl/state_machines_spec.rb
spec/tapioca/compilers/dsl/url_helpers_spec.rb

Since Sorbet has started checking for accessing private constants and erroring out on referencing a private constant off of its parent, our generated DSL RBI files have started raising errors.
If the declaration of `Bar` was:
```ruby
module Foo
class Bar
end
private_constant :Bar
end
```
then it is illegal to reference `Bar` as `Foo::Bar`. But we had been generating things like:
```ruby
module Foo
class Bar
include Foo::Bar::GeneratedMethods
end
end
module Foo::Bar::GeneratedMethods
end
```
which raises the following error on recent Sorbet versions:
```
Non-private reference to private constant Foo::Bar referenced https://srb.help/5061
3 |     include Foo::Bar::GeneratedMethods
^^^^^^^^
```
The fix is to generate everything in a nested way, which actually ended up making the code simpler …

Generate nested definitions for synthetic modules

---

lib/tapioca/compilers/dsl/active_record_columns.rb
manual/generator_activerecordcolumns.md
spec/tapioca/compilers/dsl/active_record_columns_spec.rb

Contrary to what the documentation of `ActiveRecordColumns` generator says, we actually generate strong types for models if `StrongTypeGeneration` is not defined in the user application as a constant.
We only generate weak types if a constant named `StrongTypeGeneration` is defined in the user application and the current model does not extend from it.
Because of this disconnect, we were never really testing cases where we didn't have `StrongTypeGeneration` defined. However, that is usually our default state, so most test cases should have really be testing that.
Added separate test cases that test default behaviour and behaviour when `StrongTypeGeneration` is defined.
Tests are updated to reflect the true state of affairs.

Fix ActiveRecordColumns spec wrt StrongTypeGeneration

---

spec/content_helper.rb
spec/dsl_spec.rb
spec/spec_helper.rb
spec/tapioca/cli_spec.rb
spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
spec/tapioca/compilers/dsl/action_mailer_spec.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb
spec/tapioca/compilers/dsl/active_record_columns_spec.rb
spec/tapioca/compilers/dsl/active_record_enum_spec.rb
spec/tapioca/compilers/dsl/active_record_scope_spec.rb
spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb
spec/tapioca/compilers/dsl/active_resource_spec.rb
spec/tapioca/compilers/dsl/active_support_current_attributes_spec.rb
spec/tapioca/compilers/dsl/frozen_record_spec.rb
spec/tapioca/compilers/dsl/identity_cache_spec.rb
spec/tapioca/compilers/dsl/protobuf_spec.rb
spec/tapioca/compilers/dsl/smart_properties_spec.rb
spec/tapioca/compilers/dsl/state_machines_spec.rb
spec/tapioca/compilers/dsl/url_helpers_spec.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb
spec/template_helper.rb

The motivation is to separate test file creation operations from the test mechanism so that
test helpers can depend on less context.
In the new setup, tests are responsible for declaring Ruby files they want as part of their setup using `add_ruby_file` which creates and requires the file by default. To add non-Ruby files, tests can call `add_content_file` which creates the file under the given path in the temp directory.
All test operations operate on files in the temp directory, by default, and the content helper removes the temp directory during teardown.
This allows for a more declarative test style and we don't have to keep passing around hashes of loosely structured data into test helper methods.
Existing tests are refactored.

Refactor test helpers

---

Gemfile
Gemfile.lock
spec/dsl_spec.rb
spec/isolation_helper.rb
spec/spec_helper.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Get rid of the parallel fork executor, so that we can provide a test helper for user code that is trying to write a test for their own custom DSL generator. This commit just adds the `IsolationHelper` module to optionally provide the isolation to the test classes that want it. A future change will add a test helper that consumers of Tapioca can import into their test code as well.
Mostly copied the `ActiveSupport::Testing::Isolation` module, with slight modifications to adhere to our code style.
No tests for `IsolationHelper` (yet), since it is not a library file (yet).

Copy IsolationHelper from ActiveSupport

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Fixes #191
If a constant overrides the `hash` method at the constant level in an incompatible way by returning a value that is not an `Integer`, then `Set` stops working for that constant.
However, we were using a `Set` for filtering out ignorable ancestors when discovering mixins, which was failing with a cryptic error message if it ever came across a constant that did such a thing.
~The solution is to use array difference rather than sets and enumeration, which actually makes the code simpler in the process.~
The new implementation uses a `Set` of `object_id`s to compare the inherited ancestors against the ancestors of the `constant` or the singleton class of the `constant` to find interesting ancestors. This allows us to not depend on `==`, `eql?`, `equal?` or `hash` for comparing …

Stop assuming that constants will have sensible hashes

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Tapioca is compiling RBI files that contain syntax errors in some cases where a class ends up overwriting its own superclass by aliasing that superclass to itself.
We can fix this by having `resolve_constant` take an optional `inherit` parameter which defaults to `false`. In the codepath where this comes up, we're comparing the name of the constant we see with the name of the constant returned by calling `Object.const_get` with that name. It seems like sort of a sanity check. Like, checking that this constant does in fact exist and we can find it, I guess? So we don't mind passing `inherit: true` to const_get here _I don't think_. Correct me if I'm wrong.
@paracycle was wondering if we even needed this `are_equal?` check in this case at all, and I think he was going to look into that.
If …

Fix RBI compile for constant aliases

---

lib/tapioca/compilers/dsl/base.rb

This is the fix from https://github.com/Shopify/tapioca/pull/203, but without all the changes to try to make the suite pass on 3.0.
THere is a pile of dependency issues to run CI on 3.0:
- Bundler is too old
- Rails etc is too old
- google-protobuf won't install on 3.0 right now
- probably other stuffs I haven't figured yet.
So I'm thinking in the meantime we can simply merge the fix without testing it on CI.

Fix Ruby 3.0 compat

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Fixing an RBI typo I found. When compiling, there is a chance the constant name that we want to use for an alias doesn't match because that name has itself been overwritten with something.
```ruby
class MyClient
end
module MyModule
OriginalClient = ::MyClient
end
class MockClient < MyClient
end
MyClient = MockClient
```
In this case, we do a `name_of` on `OriginalClient` which is pointing to `MyClient` but `resolve_constant` results in a `MockClient` because of the last line there. So `are_equal?(constant, resolve_constant(name, inherit: true))` is false and we end up with an empty assignment like `MyModule::OriginalClient =`
~Remove the equality check... It seems to work just fine when running it on my project also.~
~**I don't actually know if this is OK**. So I defer to y'all. …

Fix bug in compile_alias when constant names are mismatched

---

lib/tapioca/compilers/dsl/active_record_associations.rb
manual/generator_activerecordassociations.md
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

Add support for [Active Record Nested Attributes](https://api.rubyonrails.org/v6.1.0/classes/ActiveRecord/NestedAttributes/ClassMethods.html)
Each nested attribute definition [adds an entry in the `nested_attributes_options` attribute of the AR model class](https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activerecord/lib/active_record/nested_attributes.rb#L343-L345). Thus, enumerating the keys of the `nested_attributes_options` hash gives us all the attribute values for which `accepts_nested_attributes_for` was called. For each of these association names, the name of the generated setter method can [easily be generated](https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activerecord/lib/active_record/nested_attributes.rb#L370). …

Add support for AR nested attributes for associations

---

Gemfile
Gemfile.lock
lib/tapioca/gemfile.rb
lib/tapioca/generator.rb
spec/support/repo/Gemfile
spec/tapioca/cli_spec.rb
spec/template_helper.rb
tapioca.gemspec

Fix #208.
`Bundler::SpecSet#materialize` has an optional extra parameter that can be supplied an array, which will be used to collect the names of the missing gem specs when materializing. This prevents missing gem specs from raising errors, so by passing an empty array for this parameter, we can prevent Tapioca from crashing when it runs into missing specs for dependencies that don't make sense for the current platform.
Added a `nokogiri` dependency on the test repo and added a test to ensure that its optional dependency does not get processed.

Fix problem with missing gem specs

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

The code to generate module helpers currently assumes that a module can have a single helper. For example, it's either an `interface!` or `abstract!` or `sealed!`, etc. But Sorbet allows a module to have multiple. For example, algebraic data types often use `interface!` and `sealed!` together.
We modify the `compile_module_helpers` method to assemble all possible helpers instead of picking the first that matches.
I updated the test for signatures and structs to check for an algebraic data type example.

Support for modules with multiple helpers

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

A `prop` can be a `Proc`; if the return type of the `Proc` is `void`, the current code generates `returns(<VOID>)`, which is incorrect.
I reused the approach used elsewhere in the same file, which simply `gsub`s the string from `.returns(<VOID>)` to `.void`.
Included a `prop` with the issue in the test cases.

Adjust void return for props

---

sorbet/rbi/shims/bundler.rbi
spec/tapioca/cli_spec.rb

Removes the deprecation warnings for `.with_clean_env`.
Use the recommended change as provided by `Bundler`. Switch from `.with_clean_env` to `.with_unbundled_env`.
Only changed within the `cli_spec.rb` file.

Change with_clean_env to with_unbundled_env

---

lib/tapioca/gemfile.rb
spec/tapioca/cli_spec.rb

Resolves https://github.com/Shopify/tapioca/issues/229
Using @paracycle's solution from [here](https://github.com/rubygems/rubygems/issues/4394#issuecomment-782417889).
We are now passing dependencies to `materialize` as the method expects rather than specs.
Skipped an existing test failure since it's not crucial to RBI generation.

Pass dependencies to materialize

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
sorbet/rbi/shims/sorbet.rbi
spec/tapioca/compilers/symbol_table_compiler_spec.rb

With sorbet's `T::Enum` the enum values themselves are actually instances of the class that inherits from `T::Enum`. Tapioca doesn't handle these specially which affects sorbet's ability to perform exhaustiveness checking. Here's a repro [on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0A%23%20Normal%20enum%20defintion%0Aclass%20Foo%20%3C%20T%3A%3AEnum%0A%20%20enums%20do%0A%20%20%20%20A%20%3D%20new%0A%20%20end%0Aend%0A%0A%23%20What%20tapoica%20generates%0Aclass%20TapiocaFoo%20%3C%20T%3A%3AEnum%0Aend%0ATapiocaFoo%3A%3AA%20%3D%20T.let(T.unsafe(nil)%2C%20TapiocaFoo)%0A%0A%23%20Test%20normal%0Asig%20%7B%20params(arg0%3A%20Foo).void%20%7D%0Adef%20test_normal(arg0)%0A%20%20case%20arg0%0A%20%20when%20Foo%3A%3AA%0A%20%20else%0A%20%20%20%20T.absurd(arg0)%0A%20%20en …

Compile T::Enum with the `enums` block

---

lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

Do a better job of keeping DSL RBI files in sync by removing stale RBI files during generation.
We collect the set of existing DSL RBI files in the filesystem before we start any DSL RBI generation. We then remove items from the set as RBI files are generated. Whatever we are left with in that set should be RBI files that are no longer needed.
The only complication for this strategy is the fact that the user can supply a list of requested constant names, in which case, we need to build the initial list as the filenames of the RBIs that those constant names would have generated.
See included tests.

Purge stale DSL RBI files during `dsl` operation

---

lib/tapioca/compilers/sorbet.rb
spec/tapioca/compilers/sorbet_spec.rb

Fixes #245. Allows users to specify an alternative installation path for `sorbet-static` via `TPC_SORBET_EXE`, similar to the `SRB_SORBET_EXE` used by `srb`.
The path to `sorbet-static` was hardcoded in `lib/tapioca/compilers/sorbet.rb`. I added a conditional to check if `TPC_SORBET_EXE` is set, and if so use that value instead. If `TPC_SORBET_EXE` is not set, behavior should be unchanged.
I wasn't sure where/if I should add documentation to let users know `TPC_SORBET_EXE` exists. Open to suggestions!
Unit tests added in `spec/tapioca/compilers/sorbet_spec.rb`. I also ran my fork of tapioca on my system with my custom sorbet executable, to confirm it works. Not sure if it makes sense to add any integration or e2e tests for this change.

Allow for custom sorbet executables via TPC_SORBET_EXE env var

---

lib/tapioca/loader.rb
spec/support/repo/config/application.rb

Fixes: #239
`Rails.autoloaders` did not exist in Rails pre-6.0, so we should not assume that it will be there. We were faking this by defining an `autoloaders` method on the fake `Rails` module defined in our test repo, but we really should not be doing that.
Moreover, we were not actually trying to eager load a Rails app in a way that is compatible with pre-6.0 versions, which this commit aims to add as well.
Mostly extra checks to see if methods are defined as we expect and a simplification of the test repo.
I've also added an eager loading method via `config.eager_load_namespaces` that should work in pre-6.0 apps as well. However, I am assuming that `Rails.application.config` will always exist in a sensible Rails app.
No extra tests.

Change loader behaviour to support pre-Rails 6 apps

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/support/repo/Gemfile
spec/tapioca/compilers/symbol_table_compiler_spec.rb

The `T::Enum` detection code was giving us a false-positive match for the [`XPath` constant from the `xpath` gem that defines a custom `<` class method](https://github.com/teamcapybara/xpath/blob/9860a6b20b31be97f6bd23a42ff6573c35f910c3/lib/xpath/dsl.rb#L122). Since `XPath` does not also have a `values` method, we were getting a hard failure.
Since `constant < X` actually means `constant.<(X)`, when we try to run `constant < T::Enum`, if `constant` has a custom `<` (class) method defined, then the check would not mean what we want to detect, i.e. inheritance.
On the other hand, we are pretty much guaranteed `T::Enum > constant` will work since we don't expect `T::Enum` to have an overridden `>` method.
Added a test to trigger this case explicitly to make sure we don't regress.
/cc …

Properly handle types that override `<`

---

lib/tapioca/cli.rb
lib/tapioca/config_builder.rb
lib/tapioca/generator.rb
spec/support/repo/config/application.rb
spec/support/repo/lib/comment.rb
spec/support/repo/lib/post.rb
spec/support/repo/lib/user.rb
spec/tapioca/cli_spec.rb

We need an easy way to check whether or not the RBI files are out-of-date after updates are made to files, Gems are bumped, etc. This adds a `check` command to `tapioca` that will re-generate the DSL (excluding Gems) to diff against to determine whether or not `tapioca dsl` needs to be run. 
Create a `tmpdir` using [`Dir.mktmpdir`](https://ruby-doc.org/stdlib-2.7.2/libdoc/tmpdir/rdoc/Dir.html), generate the DSL in the temp directory, and diff against that to determine if RBIs are out of sync.
The command returns with an exit status of `0` if no changes are detected, and `1` if changes are detected. This will allow for it to be used in CI pipelines.
Adds two additional tests that ensure that the command returns the correct exit code as well as messaging to advise on correct next steps.

Add check command

---

exe/tapioca
lib/tapioca.rb
lib/tapioca/compilers/dsl/active_record_scope.rb
lib/tapioca/compilers/dsl/base.rb
lib/tapioca/compilers/dsl/url_helpers.rb
lib/tapioca/compilers/symbol_table/symbol_generator.rb
lib/tapioca/internal.rb
spec/spec_helper.rb

Tapioca should have never really been exporting its internal types from the gem. All the compilers, etc are for the CLI to operate properly and should not be exported by default.
Moved all the internal requires to `tapioca/internal.rb`. Also, moved the `sorbet-runtime` initialization and configuration to `tapioca/cli.rb` since that is the application which should be configuring the runtime.
Moving the Sorbet runtime configuration to CLI entrypoint also meant that we are running runtime typechecking during test runs now. That surfaced a few type errors that are fixed in this PR as well.
No extra added tests.

Stop exporting internals from the gem

---

lib/tapioca/cli/main.rb
spec/tapioca/cli_spec.rb

We haven't been showing any output for binstub generation.
Add output that `bin/tapioca` was created or force created depending the existence of `bin/tapioca`
Updated tests to check for the `bin/tapioca` output. Also changed test to run `bundle exec tapioca` and not `bundle exec bin/tapioca` since (a) we cannot rely on the binstub existing and (b) if running the binstub, it is meaningless to prepend a `bundle exec` to it.

Improve binstub generation with output

---

lib/tapioca/generic_type_registry.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Our current generic patch was failing with `initialize` methods on generic types with signatures. The reason is that given a generic type `Foo`, its `initialize` method would be wrapped in a Sorbet signature wrapper with an ultimate `bind(self).call` to the original method in the wrapper.
However, if we have something like `Foo[Bar].new` then, the `self` in that wrapper would be an instance of a clone of the `Foo` class, and will not be an instance of the `Foo` class. Thus, `self.is_a?(Foo)` would not be true in the wrapper, and the `bind` call would fail with a `TypeError`.
This was happening because we were cloning the constants that were given to us, which is fine for modules that don't have instances but fail like above for classes that will have instances. The fix is to create a …

Refactor generic patch to work properly with instance creation

---

lib/tapioca/generic_type_registry.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Sealed classes refuse to be subclassed in any file outside the original file they were declared in, but we use subclassing to represent concrete generic types at runtime. So for a generic sealed type, we need to jump through extra hoops to trick Sorbet runtime into thinking that what we are doing is safe.
Just some hacky state changing wrt the internals of how `sealed!` operates when doing the subclassing.
Added an extra test that fails in the absence of the new code path.

Make generic type creation safe for sealed classes

---

lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

Make the logic less dependent on hard-coded paths and make it possible to print the files that were added to the output.
Instead of dealing with absolute filenames when comparing file lists, if we just handle relative filenames, then we can have two lists that are easy to diff using array difference and intersection operations.
That way, we can print added, removed and changed files, where we can use the `output` path for printing the file names. This makes the code much easier to read and less brittle.
I've added a case for removed RBI files, even though we don't expect that to ever be triggered. I thought it would be good future-proofing if we ever change the auto-removal for stale RBI files.

Improve verify logic

---

lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

I realized that we can keep a file name to constant name lookup table as we are doing DSL generation and then we can use that when reporting the diff in a verify run to report the exact command they can run to make RBI files complete.
- Maintain a filename to constant name lookup table as we are doing DSL generation.
- Change the diff output to be a filename to cause lookup.
- When reporting the error, build a list of the constant names from the files in the diff and print them at the end of the `bin/tapioca dsl` command.
- Print the diff by grouping the filename to cause lookup by the cause and printing all the files for a given cause in the output.
Updates existing tests for changed expectations.

Print full command line for `tapioca dsl` in verify

---

lib/tapioca/compilers/dsl/protobuf.rb
spec/tapioca/compilers/dsl/protobuf_spec.rb

Was reviewing a PR that involved using protobuf objects directly and saw that they could not be properly typed.
Fields in protobuf can be marked as "repeated" or "map", which loosely correspond to arrays and hashes, respectively. This commit extends our support for protobuf by correctly marking the types of these fields. It also adds an initialize method to each of the protobuf classes so that creating them can be typed.
Basically, when you have `repeated` fields (https://developers.google.com/protocol-buffers/docs/reference/ruby-generated#repeated-fields), it looks like:
```ruby
repeated :examples, :string, 1
```
which corresponds to:
```ruby
sig { returns(Google::Protobuf::RepeatedField[String]) }
def examples; end
sig { params(value: …
```

Extend protobuf support for map and repeated

---

lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

A [previous PR](https://github.com/Shopify/tapioca/pull/275) had tried to make the command that was output when the `--verify` step failed to be more surgical so that users can run a command that would potentially be faster.
However, the constants that we collect as Tapioca is generating DSL RBI files do not necessarily map to real constants inside the application. Some of the constants are synthetic, for example `GeneratedUrlHelpersModule`, and would not work if supplied on a `tapioca dsl` command line. Thus, the verbose output ends up doing more harm than good.
Just removing the list of "constants" from the command line that is output.
Updated tests.

Revert verbose command output upon verify failure

---

sorbet/config
spec/content_helper.rb

Use `requires_ancestor` instead of `include Kernel`.

Use requires_ancestor in ContentHelper

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
lib/tapioca/rbi/rewriters/group_nodes.rb
lib/tapioca/rbi/rewriters/sort_nodes.rb
spec/tapioca/cli_spec.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb
spec/tapioca/rbi_spec.rb

My previous PR on RBI generation (#297) broke two things:
1. Grouping the include and extend in separate groups meant I changed the [order in which they were generated](https://github.com/Shopify/tapioca/commit/2ad440590e747403012cdbba7b49c2baa0aae072#diff-3e55697f4d9bb01a769a76f008853abea864fdb0c8de83956ee0303bfddc1764L1556-R1561) and includes were always printed before extends which is actually incorrect. So the first commit (2bb2a7e) groups them together to get the right order again.
2. Both params types and return types need to be sanitized for weird types such as `<VOID>`. It was done on the [whole signature string before](https://github.com/Shopify/tapioca/commit/d2107da489c440ae655226b33d8fee10a7051688#diff-6c17c60032864d0164ef50591234ad8238992fb3dad7d6ac33158f333ea61190L680-L684) …

Fix RBI generation for gems

---

lib/tapioca/compilers/dsl/active_job.rb
manual/generator_activejob.md
manual/generators.md
spec/tapioca/compilers/dsl/active_job_spec.rb

Need this to properly type `perform_later` and `perform_now` methods, as their arguments change based on the signature of the `perform` method.
Very similar to the ActionMailer one. If there's a perform method, it grabs the signature off of it and puts it onto the `perform_now` and `perform_later` methods.
Yup!

Generator for ActiveJob::Base descendants

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

We're have a `T.type_alias` defined in an internal gem that we want to use inside a consuming application. Seems like it ought to come over in the RBI since the constant is available at runtime.
Currently tapioca ignores `T.type_alias` since it starts with `T::Private::Types::`. This PR updates the spot where that bailout happens and adds a special case to handle it.
Extended one test and added another.

Compile T.type_alias

---

lib/tapioca/gemfile.rb

When Bundler is configured to cache gems inside the `vendor/cache` folder in the app directory, for source gems, it creates git clones in that folder. Those gems are consumed from those git clones, so they look like they are part of the application code, as far as Tapioca is concerned.
By adding an explicit check for the source files coming from `Bundler.app_cache` folder, we can make sure we treat those source locations are gem sources.
I am afraid we don't have a good way to test these yet. But, this was tested on a real Shopify app which was using `vendor/cache` folder as default. The current install of Tapioca ended up not generating any RBI files for source gems. We debugged it with @leoncustodio to this issue and confirmed that with this patch, we were able to make Tapioca produce …

Fix app cache folder source gems

---

lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

There seems to be a bit of confusion around the workflow of a failure in the `dsl --verify` command.
Lay out a little clearer what people need to do with slightly more thorough messaging.
Updated! 🎉

Improve dsl --verify failure message a bit

---

.rubocop.yml
Gemfile

While doing other work, I noticed that there was some inconsistencies in `Gemfile` and `.rubocop.yml` that were irking my OCD. 
Synchronize and use \" for string formatting in both files. Also, re-organized the `Gemfile` so that similarly scoped gems
were grouped together.
N/A

Style fixes for `Gemfile` and `.rubocop.yml`

---

lib/tapioca/compilers/dsl/active_job.rb
manual/generator_activejob.md
spec/tapioca/compilers/dsl/active_job_spec.rb

For Active Job classes, we were generating the signatures wrong in two ways:
1. `perform_later` returns an instance of the job class, or [`false` if the job couldn't be enqueued](https://github.com/rails/rails/blob/5aaaa1630ae9a71b3c3ecc4dc46074d678c08d67/activejob/lib/active_job/enqueuing.rb#L68).
2. `perform_now` returns the return value of `perform` immediately. It does not return an instance of the job class.
Make relevant updates.

Fix ActiveJob generator

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

The generic serialization code is serializing generic types with unspecified type variables incorrectly. Sorbet currently allows one to type `Foo.new` even if `Foo` is a generic type that expects type variables, and treats `Foo.new` as if it was `Foo[T.untyped].new` or similar.
However, Sorbet complains about `T.let(T.unsafe(nil), Foo)` usage, with the error message saying that `Foo` is a generic class without type arguments.
Thus, if the user code has a constant definition like `FOO = Foo.new` (where `Foo` is a generic class), then the generated RBI code for it, `FOO = T.let(T.unsafe(nil), Foo)` would end up raising a type checking error.
The fix is to treat generic types differently when grabbing their name. If their name does not already have the type variables, then we add `T.untyped` …

Serialize generic types with unspecified type variables

---

lib/tapioca/gemfile.rb
sorbet/rbi/shims/bundler.rbi
spec/tapioca/compilers/symbol_table_compiler_spec.rb

If the version of a default gem specified in the `Gemfile` is the version of that default gem that is bundled with the Ruby version, then Bundler just uses the default gem from the Ruby library directory.
But Bundler still acts like the gem is installed in where it would have been, which prevents Tapioca from generating a proper RBI for the gem and we end up generating an empty gem.
This PR makes sure that if a gem is marked as a default gem, we check against the files listed in its gemspec inside the Ruby library folder instead of looking inside what the gem install folder would have been.
No added tests.

Treat default gems properly

---

exe/tapioca

The way we modify generic types means we sometimes are not able to properly validate inline checks or call signatures. For that reason, Tapioca tries to run with most stuff turned off.
However, there is a call validation that happens inside `T::Props::Private::SetterFactory#build_setter_proc` which does not respect the `default_checked_level` value.
To suppress those errors from being raised at runtime in production, we need to explicitly suppress call validation errors by setting a no-op handler.
No tests.

Suppress call validation errors during CLI run

---

lib/tapioca/rbi/model.rb
lib/tapioca/rbi/printer.rb
spec/tapioca/rbi/printer_spec.rb

Includes and extends can take multiple names:
```rb
class Foo
include A, B
extend A, B
end
```
This PR reflect this on the RBI model and printer.

Mixins accept multiple names

---

lib/tapioca/rbi/model.rb
lib/tapioca/rbi/printer.rb
spec/tapioca/rbi/printer_spec.rb

Sorbet's RBIs support attributes definitions.
This PR adds them to the RBI model so we can actually generate them if needed (and later parse them when used in shims).

Add attributes accessors to RBI model

---

lib/tapioca/rbi/model.rb
lib/tapioca/rbi/printer.rb
spec/tapioca/rbi/printer_spec.rb

A signature accept the sig builder `checked`.
This PR adds it to the RBI model so we can generate them (and later parse them).

Add `checked` signature builder

---

lib/tapioca/compilers/dsl/smart_properties.rb
manual/generator_smartproperties.md
spec/tapioca/compilers/dsl/smart_properties_spec.rb

Fixes https://github.com/Shopify/sorbet-issues/issues/372
If a smart property is not required but has a default value guaranteed to not be nil, then for all intents and purposes that field will never be `nil`, so we should not mark it as a nilable type.
Added checks for `default` field of properties. While I was doing that, I found a better way of fetching property field via `to_h` and then fetching the desired keys.
I also inverted the logic of detecting if the type should be nilable. I think it made the code more readable.
Added relevant extra test cases and updated the documentation for the generator.

Use non-nil default value for property type inference

---

lib/tapioca/compilers/dsl/active_job.rb
spec/tapioca/compilers/dsl/active_job_spec.rb

If an Active Job class has not implemented a `perform` method, we should not be generating an empty class definition for it in an RBI file. Instead, we should completely skip generating anything for that class.
Move the check outside the class declaration.
Updated tests.

Do not generate empty Active Job classes

---

.github/workflows/ci.yml

Now that we've dropped support for [Ruby 2.4](https://github.com/Shopify/tapioca/pull/339), [2.5](https://github.com/Shopify/tapioca/pull/351) and [updated all dependencies](https://github.com/Shopify/tapioca/pull/352) to latest versions, we can start testing the library on Ruby 3.
Add Ruby 3.0 to build matrix
No new tests.

Start testing on Ruby 3

---

lib/tapioca/rbi/model.rb
spec/tapioca/rbi/model_spec.rb

Right now when you work with a RBI tree, if you print a node to know what you're dealing with, all you get is the default Ruby `to_s` implementation like `#<Tapioca::RBI::Class:0xXXXXXX>` or `#<Tapioca::RBI::Module:0xXXXXXX>` which is not super user-friendly (especially if you're debugging).
This PR adds various printing methods to nodes so when you do `puts my_rbi_node` you get `::Foo::Bar` instead of `#<Tapioca::RBI::Class:0xXXXXXX>`.
This is particularly useful if you want to use a node in a log message or error without having to visit it's content recursively with the tree printer.
1. Add `fully_qualified_name` for uniquely identifiable nodes such as `Module`, `Class`, `Const`, `Method`
2. Add `fully_qualifed_names` for nodes referring to multiple entities such as `attr_reader :a, :b` …

Allow to print a RBI node by its qualified name / to_s representation

---

lib/tapioca/compilers/dsl/active_support_concern.rb
manual/generator_activesupportconcern.md
manual/generators.md
spec/tapioca/compilers/dsl/active_support_concern_spec.rb

Sorbet currently does not provide a way of indicating that a module mixes in class methods from its ancestors. Through this RBI generator we can figure out which of its ancestors contain a `ClassMethods` module and provide that information to Sorbet using `mixes_in_class_methods`.
In order to pull this off, we first identify all named modules in the `ObjectSpace` that are not singleton classes, that extend `ActiveSupport::Concern` and have dependencies (i.e. include other concerns).
For those modules, we iterate over their linearized dependencies and pick out all modules that define a `ClassMethods` constant.
Finally we append these `ClassMethods` modules in a `mixes_in_class_methods` call in the correct order.
Added new tests.

Add ActiveSupport::Concern DSL generator

---

lib/tapioca/compilers/dsl/active_support_concern.rb
lib/tapioca/compilers/sorbet.rb
spec/tapioca/compilers/sorbet_spec.rb

We sometimes want to generate different code depending on which version of Sorbet is in play. For that we need to check which version of Sorbet we are working against.
In order to achieve this, we've added a query method for "features" for Sorbet that does a minimum version check against the version of Sorbet that Tapioca is running against. That allows features to turn themselves on or off based on feature detection.
The first use of this query is in the ActiveSupport::Concern generator, so that we don't end up generating `mixes_in_class_methods` calls with multiple parameters on older versions of Sorbet.
Added tests for the new method.

Add ability to query Sorbet features

---

lib/tapioca/cli/main.rb
lib/tapioca/generator.rb
spec/tapioca/cli_spec.rb

`tapioca dsl` has a `--verify` flag that will "exit 1" if your DSL RBI is not up-to-date. This makes it easy to add a CI check to prevent stale RBI. We're starting to use `tapioca sync` and I found myself wanting something similar to ensure gem RBI is up-to-date.
Followed a similar pattern as verification for DSL.
See added test cases

Support `tapioca sync --verify`

---

lib/tapioca.rb
lib/tapioca/active_record_column_type_helper.rb
lib/tapioca/column_type_helper.rb
lib/tapioca/compilers/dsl/active_record_columns.rb
lib/tapioca/compilers/dsl/identity_cache.rb
spec/tapioca/compilers/dsl/identity_cache_spec.rb

Closes #322 
Identity cache provides two mechanisms for caching: `cache_index` and `cache_attribute`.
When invoking [cache_index](https://github.com/Shopify/identity_cache/blob/01e90ed9fffe960ff96e9e54eaa7a03fa47a4d85/lib/identity_cache/with_primary_index.rb#L55), it invokes `cache_attribute_by_alias` which will create the alias methods for `cache_index` that we are not currently generating. After that, `cache_index` generates other methods of its own, which are not created by `cache_attribute`.
When invoking [cache_attribute](https://github.com/Shopify/identity_cache/blob/771b0f98324274c8fd79bf2d2094ca9545f3af45/lib/identity_cache/configuration_dsl.rb#L124), it only invokes `cache_attribute_by_alias` and generates the methods with aliases. These …

Handle identity_cache aliases

---

lib/tapioca/rbi/printer.rb
spec/tapioca/rbi/printer_spec.rb

Avoid printing a trailing space on empty comments lines
Be the following sequence of comments:
```rb
tree = RBI::Tree.new(comments: [
RBI::Comment.new("typed: true"),
RBI::Comment.new(""),
RBI::Comment.new("Some comment")
])
```
Before this PR, the rendering included a trailing space on the second line:
```rb
```
With this PR, no trailing space is rendered:
```rb
#<-- no trailing space
```
This plays better with cops.

Do not print trailing spaces with empty comments

---

lib/tapioca/rbi/parser.rb

Get the real file path instead of `-` ...

Actually pass file location to parser

---

spec/tapioca/rbi/index_spec.rb

This test should have been nested under the `describe` block.
See changed file.

Fix RBI::Index specs nesting

---

lib/tapioca/cli.rb
lib/tapioca/generator.rb
spec/tapioca/cli/dsl_spec.rb

Closes: https://github.com/Shopify/tapioca/issues/281
Adds a `--verbose` flag to the `dsl` command. The output will now show which constant we're processing at runtime, so that if errors were to arise, we can pin point where the problem occurred.
Added a `verbose` option to the `dsl` command in `cli.rb`. The information is then printed based on whether or not that flag is set to true.
Added additional test case ensuring that output is as expected.

Adds a `verbose` flag to the `dsl` command

---

lib/tapioca/cli.rb

Trying to clean the command line interface a bit.
These options are tied to gems RBI generation and shouldn't be available as class options since `tapioca -x Foo dsl` doesn't make sense for example.
This PR is only touching the options that can safely be moved. Other options are used by default by our different tests harnesses and will need some more love to be moved around.
No functional changes.

Options only related to RBI generation should not be class_option

---

lib/tapioca.rb
lib/tapioca/compilers/dsl/action_controller_helpers.rb
lib/tapioca/compilers/dsl/active_record_associations.rb
lib/tapioca/compilers/dsl/active_support_concern.rb
lib/tapioca/compilers/dsl/base.rb
lib/tapioca/compilers/dsl/sidekiq_worker.rb
lib/tapioca/compilers/dsl/smart_properties.rb
lib/tapioca/compilers/dsl/state_machines.rb
lib/tapioca/compilers/dsl/url_helpers.rb
lib/tapioca/compilers/symbol_table/symbol_generator.rb
lib/tapioca/constant_locator.rb
lib/tapioca/generator.rb
lib/tapioca/generic_type_registry.rb
lib/tapioca/loader.rb
lib/tapioca/rbi_ext/model.rb
lib/tapioca/reflection.rb
lib/tapioca/sorbet_ext/name_patch.rb
spec/tapioca/compilers/dsl/smart_properties_spec.rb
spec/tapioca/reflection_spec.rb

We use reflection helper methods throughout the codebase, but they kept being replicated and we ended up having lots of copies of how to grab the actual name of a constant, etc. We need a more unified central way to do that.
This implementation extracts said reflection helper methods into a helper module that can be mixed into a class (done for `SymbolGenerator` and `Dsl::Base`) or can have the helper methods called on the module itself.
I've also unified some other patterns wrt reflection in the codebase as well.
Added an extra test to validate that we get expected results for a lying class. Also some changes to existing tests.

Extract reflection methods into a module

---

README.md
lib/tapioca/generator.rb
spec/tapioca/cli/gem_spec.rb
spec/tapioca/cli/sync_spec.rb

Link to a wiki page about manual gem requires rather than the README on the main branch.
See [this comment](https://github.com/Shopify/tapioca/pull/426#pullrequestreview-727780528) for the suggestion.
- I migrated the "Manual gem requires" section of the README to a new wiki page which you can see at the following link: https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
- Note that I didn't edit any of the content.
- I modified `generator.rb` so empty RBI files would be generated with a wiki link rather than the README link.
- ~I linked the README to the wiki to be complete and so anyone with the previous link will be referred to our wiki.~
See included automated tests.

Link to a wiki page rather than README from empty RBI

---

spec/support/repo/.gitignore
spec/support/repo/Gemfile.lock

Our tests started failing because `smart_properties` made a new version release with breaking changes (for us, at least). We should be committing the `Gemfile.lock` file of the support repo so that versions don't move from underneath us.
Add `Gemfile.lock`
No added tests

Add `Gemfile.lock` for support repo

---

.github/workflows/ci.yml
lib/tapioca/gemfile.rb

Add support for Bundler 2.2.25 and up.
Fix https://github.com/Shopify/tapioca/issues/413
- Keep support for < 2.2.25 by leaving that codepath mostly unchanged.
- Use the current version of the `materialize` method for bundler versions 2.2.25 and up.
- I refactored a bit. If this makes it more confusing, let me know and I can rearrange some things. Also: naming variables is hard.
- I added a 2.2.22 and 2.2.25 bundler versions to the test matrix, otherwise relying on the tests that were there.

Add support for bundler 2.2.25+

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Reverts Shopify/tapioca#247
It turns out that there are too many edge cases in the wild which makes this unfeasible.
The errors I have ran into:
1. AWS SDK declares an empty struct which it keeps subclassing from. It does that by declaring the struct as `Foo = Struct.new("EmptyStruct")`, thus giving it only a name but no members. However, Tapioca currently does not generate "named structs". Even if we did, the Sorbet rewriter for structs does not rewrite something like that into a class definition, so [this is plain broken](https://sorbet.run/#%23%20typed%3A%20true%0A%0ABroken%20%3D%20Struct.new%28%22name%22%29%0A%0Aclass%20Bar%20%3C%20Broken%0Aend%0A%0AStillBroken%20%3D%20Struct.new%28%22name%22%2C%20%3Afoo%29%0A%0Aclass%20Quux%20%3C%20StillBroken%0Aend%0A%0AWorks%20%3D%20Struct.new%28%3A …

Revert "Generate better Struct definitions"

---

lib/tapioca/compilers/dsl/identity_cache.rb
spec/tapioca/compilers/dsl/identity_cache_spec.rb

We are generating `fetch_enabled_by_shop_id_and_market_id(keys)` instead of `fetch_enabled_by_shop_id_and_market_id(shop_id, market_id)` for aliased IDC fields and thus
we end up having the wrong arity for these generated methods.
The following changes are made to the generated method definitions:
1. `fetch_multi_by_xxx` methods get an enumerable as their `index_values` or `keys` parameter, so making that more specific.
2. It is better for `fetch_xxx` alias methods to declare their single key parameter with the name of the `key_field` instead of as just `key`.
3. `fetch_xxx_and_yyy` alias methods should declare each key value as a separate parameter, and the names of these parameters should match the `key_field` names.
Updated tests

Improve IDC generator

---

lib/tapioca/compilers/dsl/smart_properties.rb
manual/generator_smartproperties.md
spec/tapioca/compilers/dsl/smart_properties_spec.rb

Mostly reverts #338.
The problem with the approach we took in #338 was that even though the properties would have an initial default value, Smart Properties has no protections against those properties being assigned a `nil` value.
For example:
```ruby
class Foo
include SmartProperties
property :bar, default: "42"
end
foo = Foo.new
foo.bar # => "42"
foo.bar = nil
foo.bar # => nil
```
I've seen a few places in Core that explicitly check for `nil` even though the property had a default value, so I think a nilable type is safer overall.
/cc @samuelgiles 
Got rid of the default check for deciding on nilability. Left the other changes that simplified the code path from #338.
Updated tests.

Revert non-nil default value inference for SmartProperties

---

lib/tapioca/compilers/dsl/active_model_attributes.rb
manual/generator_activemodelattributes.md
spec/tapioca/compilers/dsl/active_model_attributes_spec.rb

ActiveModel provides no protections against someone assigning a `nil` value to an attribute and will return `nil` as the value of those attributes, even if they have a default value defined.
The most type-safe thing to do is to make all types nilable.
/cc @adrianna-chang-shopify 
Make all types in `ActiveModelAttributes` nilable except `T.untyped`.
Updated existing tests

Make all `ActiveModel` attribute types nilable

---

lib/tapioca/gemfile.rb
lib/tapioca/generator.rb
lib/tapioca/loader.rb

Tapioca was failing during the processing of an internal gem on Core with an error about require failing for a folder path. Investigating the failure closer, it was obvious that it was related to how Zeitwerk autovivifies implicit namespaces which are not declared in the source of the gem. What Zeitwerk does for those cases is to add an autoload for the folder path corresponding to the constant name. Now, an autoload for a folder does not normally work in Ruby, but it still calls `Kernel.require` internally. Since Zeitwerk overrides `Kernel.require`, when the constant is autoloaded Zeitwerk is able to intercept these calls and create anonymous modules for those namespaces based on the folder path. Zeitwerk never delegates those calls to the actual `require` method, so nothing fails. …

Rename method to be more descriptive about what it does

---

lib/tapioca.rb
lib/tapioca/internal.rb
spec/tapioca/cli/gem_spec.rb

Fixes https://github.com/Shopify/tapioca/issues/492.
Require `ConstantLocator` earlier in the process so it's loaded before `rbi`.
See included test.

Load ConstantLocator earlier

---

lib/tapioca/loader.rb
spec/support/gems/bar/lib/bar.rb

Sometimes gems depends on things that will be loaded by the Rails application so we need to make sure we load the application before the gems.

Load the Rails application before loading the gems

---

Gemfile.lock

Let's use the most recent version we use in CI: https://github.com/Shopify/tapioca/blob/main/.github/workflows/ci.yml#L15

Update the Bundler version used to bundle the main Gemfile.lock

---

lib/tapioca/cli.rb
lib/tapioca/compilers/dsl/base.rb
lib/tapioca/config.rb
lib/tapioca/generator.rb
lib/tapioca/generators.rb
lib/tapioca/generators/dsl.rb

We want to extract each generator from the current Generator, because:
better design: later we'll be able to introduce a common ancestor to all generators
easier testing: we will be able to unit test each generator in isolation
better separation of concerns: by breaking the coupling between generators
* Extract `build_dsl` from `Generator` class into isolated class
* Decouple parameters from `Config` file
* Update `Cli` to use new `Dsl` class
See automated tests (no changes).

Extract `Dsl` generator from `Generator` class

---

Gemfile.lock
tapioca.gemspec

Dependency to `unparser` was introduced in https://github.com/Shopify/tapioca/pull/337 to get the default values of sig parameters. Since this code has been moved to the [`rbi` gem](https://github.com/Shopify/rbi) it can be removed from Tapioca's Gemspec.
cc. @mbj

Remove unparser as a direct dependency

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
lib/tapioca/compilers/symbol_table_compiler.rb
lib/tapioca/generators/gem.rb
lib/tapioca/rbi_ext/model.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

This was a blocker for migrating all generators to use `RBI::File`.
`SymbolGenerator` and `SymbolTableCompiler` will now generate `RBI::Tree`s as opposed to `String`s.
Update the `sig`s and modify the implementation so that the transformations on the `RBI::Tree` take place in the
generator rather than the compiler.
Taken from Mojan's in-progress PR (see https://github.com/Shopify/tapioca/pull/453/commits/3543e3973cea81dad744465d710952a653758ab4)
See automated tests (minor updates).

Update `Symbol(TableCompiler|Generator)` to use `RBI::File` over `String`

---

lib/tapioca/compilers/dsl/active_record_associations.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

See also: #238, #536, #558
Based off the feedback received on #558, I've simplified it to a more concrete case which simply adds an error message for missing `ActiveRecordAssociations`. 
Reimplements a `SourceReflectionError` taken from @paracycle's [branch](https://github.com/Shopify/tapioca/compare/uk-add-errors-for-generators). Also, slightly reorganizes the `ActiveRecordAssociationsSpec` tests to nest ` #decorate` calls that have errors and those without.

Add error message for missing `ActiveRecordAssociations`

---

lib/tapioca/compilers/dsl/active_record_enum.rb
spec/tapioca/compilers/dsl/active_record_enum_spec.rb

ActiveRecord::Enum can be defined on abstract classes. Also [ActiveRecord::Enum can be inherited](https://github.com/rails/rails/blob/v6.1.4.1/activerecord/test/cases/enum_test.rb#L481), extending the list of potential values for the attribute.
Remove the guard against abstract class.
Tweak test showing that abstract classes were ignored. Add test confirming inherited enums have methods declared for the values they define.

Support ActiveRecord::Enum for abstract classes

---

lib/tapioca/compilers/dsl/identity_cache.rb
spec/tapioca/compilers/dsl/identity_cache_spec.rb

If the `config` DSL generator was loaded after `identity_cache` DSL generator, then we had a failure because `Rails::Railtie` would be loaded but there wouldn't be a properly configured application around.
The problem was because `identity_cache` was requiring `rails/railtie` explicitly, which it shouldn't do. Any proper installation of IDC should be inside of a properly configured Rails application or, alternatively, it would be loaded inside a non-Rails application which would not trigger the IDC Railtie anyway.
The best fix is to move the require of `rails/railtie` to IDC generator tests instead.
No new tests.

Fix doc generation on CI

---

lib/tapioca/constant_locator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Fixes #537 
For `eval`'ed classes/modules, the `path` attribute of the TracePoint object ends up being `"(eval)"`, which does not help us figure out where the class/module is being defined.
Instead, we can look back up the call stack until we find the first caller location that has a `path` that is not equal to ` (eval)"` which is where the call is ultimately being made from.
Added a failing test that passes after the fix.

Fix eval'ed constants not being generated in gem RBI generation

---

lib/tapioca/compilers/dsl/active_record_associations.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

Part of: #238
We want to advise the end user when associations cannot be generated due to a missing constant in the defined association.
See also: https://discourse.shopify.io/t/bin-tapioca-dsl-yields-uninitialized-constant/22411
Capture the raised `MissingConstantError` during `populate_association` and add a clearer error message to the error buffer.

Add `MissingConstantError` messaging

---

lib/tapioca/compilers/dsl/active_record_typed_store.rb
manual/generator_activerecordtypedstore.md
spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb

As to better represent the real behaviour here: https://github.com/rails/rails/blob/57fe7dfce9fc751dd521ec8e175924eb1480b5d5/activerecord/lib/active_record/store.rb#L131.
One problem with the current implementation occurs when models redefine the method to change its type. The type used by Sorbet then depends on the load order (last loaded wins):
```rb
class MyModel
sig { returns(TypeB) }
def value; end
end
class MyModel
sig { returns(TypeA) }
def value; end
end
T.reveal_type(MyModel.new.value) # TypeA, because loaded last wins
```
By using a included module we avoid this indeterministic behaviour:
```rb
class MyModel
sig { returns(TypeB) }
def value; end
end
class MyModel
include StoreAccessors
module StoreAccessors
sig { returns(TypeA) }
def value; end
end
end …
```

Generate typed store accessors in their own module

---

lib/tapioca/cli.rb
lib/tapioca/compilers/dsl_compiler.rb
lib/tapioca/executor.rb
lib/tapioca/generators/dsl.rb
lib/tapioca/helpers/test/isolation.rb
spec/cli_spec.rb
spec/executor_spec.rb
spec/tapioca/cli/dsl_spec.rb

Closes #577 
In order to run the `dsl` generator in parallel, we need some way of keeping track of which files we should not purge.
By commit:
1. Allow the parallelized block by executor to return a value. That value is serialize using `Marshal` and written/read through a pipe so that the workers can return something from the block. The executor then returns an array of all of the values that were returned by each iteration in the block
2. Revert the commit that removed parallelization from DSL #573
3. Make the changes to return the filenames from the parallelized block, so that we can have the right information and purge them later
See included tests.

Add support for dsl parallelization

---

.github/dependabot.yml

Label Dependabot PRs with the `ignore-for-release` label to avoid it showing up in the release notes.
Add the label `ignore-for-release` to Dependabot PRs.

Ignore Dependabot updates in release notes

---

lib/tapioca/compilers/dsl_compiler.rb
spec/support/repo/lib/job.rb

Fix #592
The whole idea of DSL generation revolves around being able to generate files that are named after the constants that are being decorated, so it makes sense to filter out any constants that were collected that are anonymous.
Moreover, while we enforce that the constants that we expect to be collected are supposed to be classes/modules, we never actually enforce that at runtime, in the absence of Sorbet runtime, so I've added a filter to exclude value constants from the list of collected constants as well.
No added tests, but I added an anonymous Sidekiq Worker class in the test repo to trigger a failure if we don't filter anonymous classes.

Exclude anonymous or value constants from DSL generation

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Because we weren't sanitizing type alias values, a proc type alias that returns void would be printed as `<VOID>`.
```ruby
MyType = T.type_alias { T.proc.params(val: T.untyped).void }
MyType = T.type_alias { T.proc.params(val: T.untyped).returns(<VOID>) }
```
We already handle such cases in other parts of the symbol generator, but we simply didn't do it for type aliases.
Use our method for sanitizing types before inserting the type alias value.
See included tests.

Sanitize type aliases

---

lib/tapioca/cli.rb
lib/tapioca/config.rb
lib/tapioca/config_builder.rb

Until we can figure out a way of fixing #618, we should default to sequential RBI generation and warn users that using more than one worker can cause trouble.
Just changed the defaults and added a warning when using a different number of workers.
Current tests are enough.

Set default number of workers to one

---

sorbet/tapioca/config.yml

So I'll stop forgetting to pass `--doc` when I regenerate the RBIs.
No functional changes.

Generate RBIs with documentation by default

---

Gemfile.lock
tapioca.gemspec

Given that we are likely to break API compatibility often in RBI or Spoom, we need a way for Tapioca to not allow people to install incompatible versions of those gems. For that reason, we should add pessimistic version dependencies on those gems (as described here: https://guides.rubygems.org/patterns/#pessimistic-version-constraint), so that RBI and Spoom can bump the minor version when they make an incompatible release and Tapioca will not automatically allow end users to install those versions.
**Note:** This is PR against the `0-5-stable` branch for now. I will cherry-pick this on `main` afterwards.

Add pessimistic version dependencies on our gems

---

lib/tapioca/compilers/dsl/active_record_associations.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

This follows up https://github.com/Shopify/tapioca/pull/634 to properly load reflections for namespaced has_many relations (vs just has_one relations).
It's a pretty straightforward port of the logic from #634.
Updated the test suite to cover the new functionality.

Properly load reflections for namespaced has_many relations

---

lib/tapioca/autoload_tracker.rb
spec/tapioca/cli/gem_spec.rb

After #639 was merged, we noticed there were 2 problems:
1. In projects with Bootsnap installed, we were getting into an infinite loop and exiting with a stack overflow exception. This was happening because `AutoloadTracker` used prepending a module to intercept `Kernel#autoload` but Bootsnap was using alias-method-chain. The two approaches are not exactly compatible and by the time Bootsnap is loaded, the method it was aliasing was becoming the `AutoloadTracker#autoload` method, thus an infinite loop was entered.
2. I noticed that the eager load method was sometimes exiting the process with the message: ``webrick is not found. You may need to `gem install webrick` to install webrick.``. I followed that message into [RDoc calling an …

Stop intercepting `Module#autoload` with a prepend

---

Gemfile.lock
lib/tapioca/cli.rb
lib/tapioca/config.rb
spec/tapioca/cli/clean_shims_spec.rb
tapioca.gemspec

As we get more precise content generated from the `gem` and `dsl` commands, we can expect that some shim definition are not useful anymore.
This PR adds a `clean-shims` command that remove the definitions that are no longer required from the shim RBI files.
Closes #435:
This work is mostly based on the [`RemoveKnownDefinitions tree rewriter`](https://github.com/Shopify/rbi/pull/100):
1. We parse the gem RBIs and index their content
2. We parse the DSL RBIs and index their content
3. We parse the shim RBIs then for each definition in the shims
* If the definition is present in the index we remove it from the tree
* Then, if a scope is already present in the index and is empty in the shim, we remove it from the tree
* Then, if a file is empty we delete it
Some considerations about what we …

Add a command to clean shim files automatically

---

lib/tapioca/autoload_tracker.rb
spec/tapioca/cli/gem_spec.rb

Fixes #648.
Part of the previous autoload tracker PR (#642) was actually broken and the test that was exercising that code path was broken in that it wasn't catching the fact that the implementation was broken.
Since `Kernel#abort` and `Kernel.exit` both expect parameters, our override with no expected parameters was failing but the failure was being caught by the autoload process and silently swallowed. So while it looked like we were successfully preventing the process from exiting, we weren't really doing the correct thing.
I pulled out the noop method used for both `Kernel#abort` and `Kernel#exit` to a constant and made sure it handles any kind of parameters that could be given to it.
Improved the test to handle trivial errors that could happen while calling `Kernel#abort` and …

Improve autoload `Kernel` hooks so that they actually work now

---

lib/tapioca/compilers/dsl/active_record_associations.rb
lib/tapioca/compilers/dsl/active_record_scope.rb
lib/tapioca/compilers/dsl/base.rb
lib/tapioca/compilers/dsl_compiler.rb
lib/tapioca/generators/dsl.rb
spec/dsl_spec_helper.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb
spec/tapioca/compilers/dsl/active_record_scope_spec.rb

If we release Tapioca in its current state, we will have to deal with 1000s of type errors, all related to the new `ActiveRecordRelations` change, before we can bump the version in Core. In order to decouple the Tapioca version bump from clearing all those errors, the best way forward is to be able to disable the `ActiveRecordRelation` generator.
However, the existence of that generator has changed the behaviour of other generators as well.  Primarily, whereas `ActiveRecordAssociations` generator was generating collection association method returns as the fake generic `CollectionProxy`, it is now doing it using the internal `PrivateCollectionProxy`. Similarly, whereas `ActiveRecordScope` generator was generating `T.untyped` as the return value of scope method, it is not generating them as …

Allow DSL generators to change behaviour based on if `ActiveRecordRelations` is enabled or not

---

lib/tapioca/cli.rb
lib/tapioca/generators/init.rb
spec/tapioca/cli/init_spec.rb

Now that Tapioca config is documented and can easily be supported going forward, we should start generating a skeleton Tapioca config file during `tapioca init`.
Add and call a method to create a Tapioca config file with commented out example content.

Make `init` create a skeleton Tapioca config

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

It seems mixin filtering is not mature enough yet, and the way we are filtering mixins will end up resulting in RBIs that have some critical mixins missing completely. So in order to not block the 0.6.0 release, I've decided to revert the mixin filtering instead and to focus on implementing it more completely after 0.6.0.
Partial revert of #569
Reverting the test changes in #569

Remove mixin filtering

---

lib/tapioca/compilers/dsl/active_record_relations.rb
spec/tapioca/compilers/dsl/active_record_relations_spec.rb

Bug fix for v0.6.0
It appears that we're generating the signature for `find` twice while missing the signature for `find_by!`, was probably accidentally left on one line during the refactoring.
- Deleted the duplicate `find` signature in the spec expectation
- Moved the `find_by!` to its only condition and generated the correct type for it
Included

Add typing for find_by!

---

Gemfile
Gemfile.lock
lib/tapioca/compilers/dsl/rails_generators.rb
lib/tapioca/compilers/dsl/url_helpers.rb
spec/tapioca/compilers/dsl/rails_generators_spec.rb
spec/tapioca/compilers/dsl/url_helpers_spec.rb

Fixes #676
[`XPath`](https://github.com/teamcapybara/xpath/blob/9860a6b20b31be97f6bd23a42ff6573c35f910c3/lib/xpath.rb) is a strange module that overloads a lot of the common methods that we use for type checking, especially `<` and `==`. That makes it surreptitiously match some of our DSL compilers and ends up causing problems.
Make sure we don't rely on the `<` and `==` of types that are not under our control.
Add explicit tests to make sure we don't match `XPath` for the two generators that were gathering it.

Fix various DSL compilers matching `XPath`

---

lib/tapioca/compilers/dsl/smart_properties.rb
spec/tapioca/cli/dsl_spec.rb
spec/tapioca/compilers/dsl/smart_properties_spec.rb

We were generating `SmartProperties` methods on the constant definition itself, but this is not how things are implemented in Smart Properties and it makes it hard to decide which method to generate.
By generating Smart Properties defined methods in an inner module, we model the actual operation of what really happens at runtime better. Moreover, we don't need to keep doing checks to see if the method was overridden in the constant itself, to decide if we should generate the method or not.
Updated existing tests and add an extra test for overridden methods.

Refactor how `SmartProperties` methods are generated

---

.github/workflows/ci.yml
spec/helpers/mock_project.rb
spec/tapioca/cli/gem_spec.rb

- Fix Ruby 3.0 being resolved as 3.1 unless quoted: https://bibwild.wordpress.com/2021/12/28/github-action-setup-ruby-needs-to-quote-3-0-or-will-end-up-with-ruby-3-1/
- Remove Bundler version matrix from CI, in favour of a test that runs with Bundler 2.2.22 explicitly.
Read commit by commit
One extra test case for Bundler 2.2.22 added.

Update CI workflow

---

spec/tapioca/cli/gem_spec.rb

Our default gem test and missing gem tests were brittle and, in some cases, were not working at all.
- The missing gem tests were depending on a gem with other dependencies including one of our own dependencies (i.e. `minitest`) which could end up being problematic.
- The default gem test was assuming the version of the default gem that it was testing against. However, that assumption is not always correct, since default gem versions generally change with every release of Ruby.
- For the missing gem test, I changed the gem to be `ruby2_keywords` which is a super small gem with no other dependencies. I also changed the platform from `truffleruby` to `rbx` since it is less likely that we will ever be tested on Rubinius than TruffleRuby.
- For the default gem test, I made it easy to change …

Improve default gem test

---

lib/tapioca/compilers/requires_compiler.rb

When trying tapioca on a large codebase I noticed that the `require` subcommand would run for a very long time (more than 40 minutes).  When I profiled to investigate I found that almost all of time was spent running `File.basename` in a tight loop.
Looking closer, I found that most of [these calls](https://github.com/Shopify/tapioca/blob/fc1445a84a2f2287ae1c380140fb469d4ffc3a2f/lib/tapioca/compilers/requires_compiler.rb#L90) were redundant since `RequiresCompiler#name_in_project?` always receives the same `files` argument, so in all but the first call it is spending most of its time repeating previously done work.
I've inlined the helper method `RequiresCompiler#name_in_project?` and converted it to a set to speed up the large number of inclusion checks to be performed.  In the …

Improve RequiresCompiler performance

---

lib/tapioca/compilers/requires_compiler.rb
spec/tapioca/compilers/requires_compiler_spec.rb

While using tapioca, I noticed that `tapioca require` fails with an encoding error if it encounters certain valid ruby source files with encodings other than UTF-8.  See [this commit](https://github.com/brasic/tapioca/commit/f38ce3f1031455872b5e1617b1ded810e10f9578) for an example.  Since `File.read` assumes UTF-8 encoding by default, its output is not safe to match against regular expressions since it may not have `valid_encoding?`.
```
irb(main):003:0> "やあ".encode("sjis").force_encoding("UTF-8").match(/require/)
(irb):3:in `match': invalid byte sequence in UTF-8 (ArgumentError)
from (irb):3:in `match'
```
The simplest way to fix this is to use `File.binread` so that the regular expression operates in binary mode and drops all multibyte-aware behavior.  That's what I've done here.  It …

RequiresCompiler: handle ruby source files with alternate encodings

---

lib/tapioca/compilers/requires_compiler.rb
spec/tapioca/compilers/requires_compiler_spec.rb

If a require uses an interpolated argument it should not be included in the compiled file for the following reasons:
- The output of `collect_requires` is later filtered by `name_in_project?`, which compares require arguments with file paths.  This strategy won't work with interpolated strings.
- The regular expression isn't smart enough to correctly handle the full semantics of interpolated strings, which allows for things like interior quotes.  That means that an instance of e.g. `require "#{ENV["SOMETHING"]}"` will be transformed into `require "#{ENV["` which is invalid syntax.
I considered altering the regular expression to use a negative lookahead assertion against the sequence `#{` but the regex is already fairly obscure.  It seemed simpler to add a post-processing step to remove …

Ignore interpolated strings in RequiresCompiler

---

lib/tapioca/compilers/symbol_table/symbol_generator.rb
lib/tapioca/generic_type_registry.rb
lib/tapioca/sorbet_ext/generic_name_patch.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

A test case submitted by @jeffcarbs in #697 surfaced the weakness of how we were doing late name binding for type variables. I was not satisfied with the changes I made on that PR, and wanted to find a better way, which is this PR that improves type variable detection immensely.
There are 2 main changes made in this PR to properly run the added test:
1. We add a `<=` implementation for the generic types that we create to act like they are always covariant or contravariant. Sorbet runtime asserts co/contravariance of types in `in` and `out` positions, and fails with an error if the assertions are not satisfied. Since we are not interested in detecting these case, but more in getting the code to run, we act like everything is fine to pass these checks.
2. One of the problems we've had was …

Improve generic type variable tracking

---

lib/tapioca/helpers/config_helper.rb
spec/tapioca/cli/config_spec.rb

Fixes #704
The first time `options` method is hit, we validate the Tapioca configuration. The validation makes sure that all top level keys match to some command, all command options match to one of the flags for that command and that all values for command options are of the expected type.
Add new tests for configuration failures.

Add configuration validation

---

lib/tapioca/compilers/dsl/active_record_columns.rb
lib/tapioca/generic_type_registry.rb
lib/tapioca/helpers/active_record_column_type_helper.rb
spec/tapioca/compilers/dsl/active_record_columns_spec.rb

We seem to have cases in Shopify Core where we define a generic custom Active Record column type, where the actual attribute type ends up being the generic type variable the column type is instantiated with.
Since #701, we seem to be generating the types of those columns as the name of the type member, which obviously does not type-check. Even worse than this, before #701, we were silently generating badly typed RBI files like:
```ruby
class Model
extend T::Sig
include GeneratedAttributeMethods
module GeneratedAttributeMethods
sig { returns(T.nilable()) }
def details; end
sig { params(value: T.nilable()).returns(T.nilable()) }
def details=(value); end
sig { returns(T::Boolean) }
def details?; end
sig { returns(T.nilable()) }
def details_before_last_save; end
sig { returns(T.untyped) }
def …
```

Make generic AR column types `T.untyped`

---

Gemfile.lock
tapioca.gemspec

We previously bumped our Thor dependency but neglected to update our runtime dependency requirement that is now on Thor version 1.2.0 or greater (since `say_error` was added in that version).

Bump Thor requirement

---

lib/tapioca/cli.rb
spec/tapioca/cli/gem_spec.rb

I keep typing `bin/tapioca gems foo bar baz` especially when I am about to generate gem RBIs for multiple gems, so I thought that it would be nice to add `gems` as an alias to the `gem` command.
Use built-in Thor command alias mapping.
Add a test to verify that the alias works as intended.

Add `gems` as an alias to the `gem` command

---

Gemfile.lock
lib/tapioca/compilers/symbol_table_compiler.rb
lib/tapioca/trackers.rb
lib/tapioca/trackers/required_ancestor.rb
sorbet/rbi/gems/rbi@0.0.10.rbi
sorbet/rbi/gems/spoom@1.1.5.rbi
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Closes https://github.com/Shopify/tapioca/issues/438.
Following the same implementation as the mixins tracker: we hook on the `requires_ancestor` method to collect the required modules.

Generate `requires_ancestor` helpers in gems RBIs

---

lib/tapioca/compilers/dsl/active_model_attributes.rb
lib/tapioca/compilers/dsl/active_record_associations.rb
lib/tapioca/compilers/dsl/active_record_columns.rb
lib/tapioca/compilers/dsl/active_record_relations.rb
lib/tapioca/compilers/dsl/active_record_typed_store.rb
lib/tapioca/compilers/dsl/base.rb
lib/tapioca/compilers/dsl/identity_cache.rb
lib/tapioca/compilers/dsl/rails_generators.rb
lib/tapioca/compilers/dsl/smart_properties.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb

Fixes #755 
Move `as_nilable_type` to the DSL base class and change all usages of `T.nilable` wrapping on bare unknown types use that utility method instead.
Updated tests to conform to the new reality.

Never generate `T.nilable(T.untyped)` in DSL generators

---

lib/tapioca/compilers/symbol_table_compiler.rb

Remove useless method `mixed_in_by_gem?` from SymbolTableCompiler

---

lib/tapioca/compilers/symbol_table_compiler.rb
lib/tapioca/generators/gem.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Those methods don't need to pass around the tree since the nodes are always created at the root level.

SymbolTableCompiler returns a new tree each time called

---

.vscode/settings.json

- Disable the Ruby extension intellisense and formatting (these might end up conflicting with Sorbet and RuboCop LSP)
- Make RuboCop-LSP the default formatter
- Enable format on save for Ruby files

Improve workspace settings for VSCode

---

lib/tapioca/helpers/test/dsl_compiler.rb
lib/tapioca/helpers/test/template.rb
spec/dsl_spec_helper.rb
spec/tapioca/compilers/dsl/aasm_spec.rb
spec/tapioca/compilers/dsl/action_controller_helpers_spec.rb
spec/tapioca/compilers/dsl/action_mailer_spec.rb
spec/tapioca/compilers/dsl/active_job_spec.rb
spec/tapioca/compilers/dsl/active_model_attributes_spec.rb
spec/tapioca/compilers/dsl/active_record_associations_spec.rb
spec/tapioca/compilers/dsl/active_record_columns_spec.rb
spec/tapioca/compilers/dsl/active_record_enum_spec.rb
spec/tapioca/compilers/dsl/active_record_fixtures_spec.rb
spec/tapioca/compilers/dsl/active_record_scope_spec.rb
spec/tapioca/compilers/dsl/active_record_typed_store_spec.rb
spec/tapioca/compilers/dsl/active_resource_spec.rb
spec/tapioca/compilers/dsl/active_storage_spec.rb
spec/tapioca/compilers/dsl/active_support_concern_spec.rb
spec/tapioca/compilers/dsl/active_support_current_attributes_spec.rb
spec/tapioca/compilers/dsl/config_spec.rb
spec/tapioca/compilers/dsl/frozen_record_spec.rb
spec/tapioca/compilers/dsl/identity_cache_spec.rb
spec/tapioca/compilers/dsl/mixed_in_class_attributes_spec.rb
spec/tapioca/compilers/dsl/protobuf_spec.rb
spec/tapioca/compilers/dsl/rails_generators_spec.rb
spec/tapioca/compilers/dsl/sidekiq_worker_spec.rb
spec/tapioca/compilers/dsl/smart_properties_spec.rb
spec/tapioca/compilers/dsl/state_machines_spec.rb
spec/tapioca/compilers/dsl/url_helpers_spec.rb

We currently have too much magic inside the `DslSpec` test superclass which makes it hard for other projects to write tests for their own DSL compilers, and it also makes it hard to understand what is going on inside that superclass as well.
Extract logic to a reusable module that should work independently of the testing framework used. This module provides helper methods to setup DSL compiler under test and possibly collaborating DSL compilers that should also be activated. Moreover it provides convenience methods like `rbi_for` and `gathered_constants` that tests can use for assertions.
While I was refactoring tests, I also took the opportunity to make sure our "no errors raised" assertions didn't end up being intrusive across the whole test suite.
No new tests.

Expose DSL compiler test helper as a reusable unit

---

lib/tapioca/compilers/dsl/base.rb
lib/tapioca/compilers/dsl/helpers/active_record_column_type_helper.rb
lib/tapioca/reflection.rb

I noticed tapioca was using `T::Private::Methods.signature_for_method` which is a "private" module (private in quotes because it's not actually private, just named to try to discourage use). https://github.com/sorbet/sorbet/pull/4041 introduced a utility method that just calls that private method so this PR updates to use that.
- Replace usages of `T::Private::Methods.signature_for_method` with `Reflection.signature_of` where possible
- In `Reflection.signature_of`, switch to using `T::Utils.signature_for_method`
No tests since there should be no behavior change.

Replace usage of `T::Private::Methods.signature_for_method` with public equivalent

---

Gemfile.lock
tapioca.gemspec

So we can use the patch from https://github.com/Shopify/rbi/pull/121.

Bump rbi to v0.0.12

---

lib/tapioca/compilers/gem/listeners/sorbet_signatures.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb

Fixes #766.
Use the new `is_final` flag in `rbi` gem and set it to true for methods that have a signature marked as final.
Added an extra test case with final signatures.

Implement support for final method signatures

---

lib/tapioca/compilers/symbol_table_compiler.rb
lib/tapioca/sorbet_ext/name_patch.rb
spec/tapioca/compilers/symbol_table_compiler_spec.rb
spec/tapioca/dsl/compilers/action_controller_helpers_spec.rb
spec/tapioca/dsl/compilers/action_mailer_spec.rb
spec/tapioca/dsl/compilers/active_job_spec.rb
spec/tapioca/dsl/compilers/active_record_columns_spec.rb
spec/tapioca/dsl/compilers/active_support_current_attributes_spec.rb
spec/tapioca/dsl/compilers/sidekiq_worker_spec.rb

Came across a subtle bug in tapioca RBI generation where absolute namespacing get dropped (e.g. `::String` comes out of RBI as `String`). This causes issues when the referenced constant shares a name with both a global constant and one that lives somewhere inside the current namespace. See the test for an example.
~Unsure how to fix, just wanted to send a reproduction.~ Use `qualified_name_of` in the Simple type name patch.
Added new tests and also needed to update existing ones.

Use root/absolute namespace in compiled RBI

---

lib/tapioca/dsl/compilers/aasm.rb
spec/tapioca/dsl/compilers/aasm_spec.rb

Hello! I encountered some type errors in a project related to the AASM gem.  More specifically, it appears the DSL generator for AASM only supports one form of their lifecycle callbacks.
```ruby
class Foo
include AASM
aasm do
state :state1
state :state2
event :do_something do
transitions from: :state1, to: :state2
after :some_method
end
def some_method
end
end
end
```
The above code would produce a typeerror along the lines of `after requires a block parameter, but no block was passed https://srb.help/7021`.  However, [this is in fact valid usage](https://github.com/aasm/aasm#callbacks) of the `after` hook.  Similar to `ActiveRecord` callbacks, they accept either a block or a symbol corresponding to a method name.
This PR updates the generated `sig`s for AASM lifecycle hooks from this: …

Update AASM DSL generator

---

lib/tapioca.rb
lib/tapioca/internal.rb
lib/tapioca/sorbet_ext/generic_name_patch.rb

The split between top level `tapioca.rb` requires and `tapioca/internal.rb` requires was creating an ordering problem. Also, the default require of Tapioca might be pulling into the requiring much more than we intended, and since we do messy things with Sorbet runtime, that could end up being distruptive.
It is best to not load anything from the default require (we basically define the top-level `Tapioca` namespace and some constants under it, only) and to load everything for the CLI using `tapioca/internal.rb`. This allows us to order the requires so that all the trackers and other runtime patches get loaded before things that depend on them.
**NOTE:** This implies that people who write their own DSL compilers will have to explicitly do a `require "tapioca/dsl/compiler"`.
No new tests.

Load nothing from Tapioca by default

---

lib/tapioca/runtime/generic_type_registry.rb
spec/tapioca/gem/pipeline_spec.rb

Fixes #838 
The `GenericNamePatch` is [using string interpolation to serialize the names of `fixed`, `lower` and `upper` arguments](https://github.com/Shopify/tapioca/blob/9297b51bcf560c1416f27c0523a6cd15822cc59d/lib/tapioca/sorbet_ext/generic_name_patch.rb#L158-L160) but we have been only overriding the `name` method on generic types. Since generic types that we create are actually anonymous, calling `to_s` on them returns something like `#<Class:0x00007fb9d58fdce8>` which is both unexpected and wrong.
The implementation makes sure that whoever calls `to_s` on a generic type also gets the expected generic type name.
Add a failing test based on the report in #838.

Fix generic type variable argument serialization

---

spec/helpers/mock_project.rb

Just a shortcut so we can do:
```rb
puts result
```
Instead of
```rb
puts result.out
puts result.err
puts result.status
```
When debugging tests.

Add an easy way to print `ExecResult` in tests

---

lib/tapioca/dsl.rb
spec/tapioca/cli/dsl_spec.rb

When writing a custom DSL compiler, the client code needs to require a minimal set of files from Tapioca, so that the DSL compiler can be loaded in isolation and tested inside the project. However, we don't have an entrypoint for that minimal require set and clients end up having to do `require "tapioca/internal"` to achieve this, which is not great.
This PR adds a `tapioca/dsl` entrypoint, which DSL compiler classes can add as a require.
The test is super custom, since I wanted to test the experience of a client app declaring and loading a custom DSL compiler in isolation from the Tapioca CLI runner. When we load the Tapioca CLI `dsl` command and, that, in turn, loads custom compilers, everything works regardless of any Tapioca requires, since the CLI already bring everything with it. …

Add `tapioca/dsl` entrypoint for custom DSL compilers

---

lib/tapioca/commands/init.rb
spec/tapioca/cli/init_spec.rb

This directory can be safely ignored and this will avoid a lot of Sorbet type errors out of the box after a `tapioca init`.

Always ignore the `vendor/` directory form the sorbet/config

---

lib/tapioca/dsl/compilers/active_record_fixtures.rb
lib/tapioca/dsl/compilers/url_helpers.rb
spec/tapioca/dsl/compilers/active_record_fixtures_spec.rb

Avoid getting a scary stack trace when running `tapioca dsl` in the wrong kind of app:
```
$ bundle exec tapioca dsl
Loading Rails application... Done
Loading DSL compiler classes... Done
Compiling DSL RBI files...
bundler: failed to load command: tapioca
tapioca/lib/tapioca/dsl/compilers/url_helpers.rb:112:in `gather_constants': undefined method `routes' for nil:NilClass (NoMethodError)
```
Check if we are in a Rails app with `Rails.application`.

Do not crash when trying to generate DSL RBIs on non-rails apps

---

.github/dependabot.yml
.github/workflows/automate_dependabot.yml

Dependency maintenance takes a lot of time. Merging minor and patch version changes is quite safe, especially given that they are not released right away.
Leaning on the automerge feature and branch protection, we can let Github actions take care of it. This will mark dependabot pull requests as automergable if all the CI checks pass.
I scheduled them for daytime ET since a lot of us are around then in case anything is weird.
This will still require human intervention if tests fail, if there are merge conflicts, or if there are major version changes.
In a lot of cases, merge conflicts can be resolved with `@dependabot rebase` or `@dependabot recreate`.

Automerge patch and minor dependency version bumps

---

.github/dependabot.yml
.github/workflows/automate_dependabot.yml

Revisiting https://github.com/Shopify/tapioca/pull/851
The RBI validity check blocked merging the first time around, which makes perfect sense.
What I'm attempting with this one is to bump the RBI in the dependabot PR before queueing it for automerge. CI will run on the latest commit to the PR so if it still fails then it means something was likely wrong.
Thoughts? Worth a try I think.

Dependabot Automerge: Take 2

---

lib/tapioca/dsl/helpers/param_helper.rb
spec/tapioca/dsl/compilers/active_support_current_attributes_spec.rb

The issue occured when running the dsl command for an
ActiveSupport::CurrentAttributes class with a method accepting a block
with type: `T.proc.void`, resulting in the invalid `.params()` being
generated.
The fix is a total shot in the dark, and I have no idea if it's a good approach, or if there's a better one
The test change is almost 1:1 the issue I faced in my own code

Fix block with no param generation

---

lib/tapioca/dsl/compiler.rb
lib/tapioca/dsl/compilers/url_helpers.rb
sorbet/rbi/shims/set.rbi
spec/tapioca/dsl/compilers/url_helpers_spec.rb

When doing a difference of arrays for finding interesting ancestors, we need to be careful in case a constant has overridden `Object#hash`. Since array subtractions use `Object#hash` to determine equality, this operation will fail.
Instead, we need to use a Set with compare-by-identity semantics, so that `Object#hash` is never called.

Start using compared by identity Set operations for `UrlHelpers#includes_helper?`

---

lib/tapioca/dsl/compilers/protobuf.rb
spec/tapioca/dsl/compilers/protobuf_spec.rb

With Protobuf it seems possible to write fields with capitalized names:
```rb
add_message "MyCart" do
optional :ShopID, :int32, 1
optional :ShopName, :string, 2
end
```
In its current state, Tapioca will generate a syntactically incorrect RBI:
```rb
class Cart
sig { params(ShopID: String, ShopName: String).void }
def initialize(ShopID: nil, ShopName: nil); end # Syntax error: formal argument cannot be a constant
end
```
While we do want to generate constructors with named fields, we could fallback on taking a Hash if the name of one of the field is not suitable for a named parameter:
```rb
class Cart
sig { params(fields: T.untyped).void }
def initialize(**fields); end
end
```

Avoid generating syntax errors for capitalized protobuf fields

---

README.md
lib/tapioca/cli.rb
lib/tapioca/helpers/shims_helper.rb
lib/tapioca/helpers/sorbet_helper.rb
sorbet/rbi/shims/bundler.rbi
spec/tapioca/cli/check_shims_spec.rb

Check duplicates between shims files and Sorbet's payload.
It's frequent that we locally fix Sorbet's payload in our shims waiting for the same patch to be merged upstream. The problem is that after a while we forget the local fixes and they stay there for ever. This can even become dangerous when the definition in the payload is later updated and we keep the shadowing local definition.
This PR introduces a way to check for duplicates between the local shims and Sorbet's payload.
This feature uses Sorbet's `--print=payload_sources` to dump the RBIs from its payload so we can index them in the same way we do for gems RBIs and DSL RBIs.
I gated the feature behind a specific Sorbet version like we did for `to_ary_nil_support`.

Check duplicates between shims and Sorbet's RBI payload

---

lib/tapioca/gem/listeners/methods.rb
spec/tapioca/gem/pipeline_spec.rb

This issue was discovered by @paracycle while investigating #890, but it is technically unrelated to mixin generation.
While generating RBIs for a method, tapioca implements a check to determine which constant "owns" or defines that method. We only want to generate RBIs for a method on the module or class that defines it, not any that just happen to inherit it.
Historically, we have been checking the `method.owner` and verifying that it matches the class/module for which we are generating RBIs. However, this check misses one particular case: when a method is also defined on a prepended module, it will always appear as if it belongs to the prepended module, even when it is also defined on the class that prepends the module.
This means that tapioca will not generate RBI for that method on …

More effectively determine method ownership for RBI generation

---

README.md
tasks/readme.rake

Make it obvious where this content is coming from so users can run the commands themselves.
I, for one, am always fighting with Thor:
* `tapioca gem --help`, urgh wrong...
* `tapioca gem help`, damn it!
* `tapioca help gem` ah.

Add help command input in README snippets

---

README.md
lib/tapioca/cli.rb
sorbet/tapioca/config.yml

* This feature makes the whole VS Code experience so much better
* It's been battle tested for quite a long now and works well
* It's slow only for a very limited number of gems, let's have people disable it if needed instead
`!false`

Enable documentation generation by default

---

README.md
misc/tapioca-logo.svg

Closes https://github.com/Shopify/sorbet-issues/issues/248.

Improve README

---

lib/tapioca/runtime/loader.rb

Resolves https://github.com/Shopify/tapioca/issues/517
We utilize `Class#descendants` in tapioca. As reported in the above issue in Rails versions prior to `v6.1.0`, upon loading of a `Rails::Engine` the `Class` [redefinition](https://github.com/rails/rails/blob/v6.0.4.8/activesupport/lib/active_support/core_ext/class/subclasses.rb#L21-L28) that defines `descendants` isn't loaded.
Explicitly load the file using our internal `safe_require` method.
I tested it manually. Automated testing is likely not worth the effort in comparison to the change.

Explicitly load descendants patch in ActiveSupport

---

lib/tapioca/dsl/compilers/protobuf.rb
spec/tapioca/dsl/compilers/protobuf_spec.rb

Google Protobuf messages support `oneof` field types:
```
add_message "MyCart" do
oneof :contact_info do
optional :phone_number, :int32, 1
optional :email, :string, 2
end
end
```
`MyCart` will have a `#contact_info` method that returns the name of the optional that has been used (or nil).
This PR adds a method definition to RBIs for messages with `oneof` fields.
`Descriptor` provides an `each_oneof` method. I iterate over the `oneof` descriptors and create an RBI method for each.
👍

Add support for :oneof fields on protobuf messages

---

lib/tapioca/static/symbol_table_parser.rb

We seem to sometimes not read enough bytes from the Sorbet output, which ends up causing us to get an error from the JSON parser. While we investigate and fix that root cause, we might as well gracefully handle JSON parsing errors.
Rescue JSON parsing errors
No tests, since I don't know how to recreate this situation.

Handle gracefully if we get unparsable JSON

---

lib/tapioca/sorbet_ext/generic_name_patch.rb
spec/tapioca/gem/pipeline_spec.rb

Now that Sorbet syntax for declaring type variables is via a block, code authors can very well refer from that block to types that have not been defined yet. Since the values of `fixed`, `lower` and `upper` are late evaluated, this should work normally.
However, our current attempt to retrofit the new type variable syntax was trying to early evaluate the block that was passed so that we could unify on the old syntax. However, that early evaluation breaks for the case outlined above.
We should instead convert the bounds passed to type variables into the block format, if a block is not passed, and always work with blocks until the point where we need to serialize the type variable. We should be pretty guaranteed that the types referred to from the block will be defined by the time we get to …

Fix type variable patch to respect references to late defined types

---

spec/helpers/mock_project.rb

Following https://github.com/Shopify/tapioca/pull/920, running the test suite increased from 10 to 40 minutes because we spend a lot of time parsing and generating the documentation in the gem RBIs.
Always pass `--no-doc` unless `--doc` is passed explicitly.

Always run tests with `--no-doc` unless specified otherwise

---

README.md

Closes https://github.com/Shopify/tapioca/issues/945.

Improve README documentation about `tapioca gem --all`

---

README.md
lib/tapioca/gemfile.rb

These 2 gems are dev/test only gems and have been proven to be
disrupting to RBI generation. So instead of telling every users to skip
them manually, Tapioca should just skip them by default.
Just add them to the `IGNORED_GEMS` constant.
I'm not sure if we want to add tests for this the ignored gems list? 
Closes #946

Skip debug and fakefs gems

---

README.md

Fix the generated help documentation for the `check-shims` command.
There was a typo in the macro name: `START_HELP_COMMAND_CHECK-SHIMS` instead of `START_HELP_COMMAND_CHECK_SHIMS`.

Fix command documentation for check-shims

---

lib/tapioca/dsl/compiler.rb
lib/tapioca/gem/listeners/methods.rb
lib/tapioca/helpers/rbi_helper.rb
lib/tapioca/rbi_ext/model.rb
sorbet/rbi/gems/rbi@0.0.14.rbi
spec/tapioca/helpers/rbi_helper_spec.rb

Fixes #969.
Closes #973.
Use the fix proposed [here](https://github.com/Shopify/tapioca/pull/973#issuecomment-1153129896) and factorize it under `RBIHelper`.
Also tighten the parameter name validation while at it.
See included tests.

Better name validation for methods and parameters

---

Gemfile
Gemfile.lock

It's already specified in `gemspec` under `sorbet-static-and-runtime` gem.https://github.com/Shopify/tapioca/blob/7f18930a1cc587bdc0a291e0493e580d16199ad2/tapioca.gemspec#L31
A gem being specified as both runtime and development dependency seems unnecessary. I also wanted to see a dependabot PR title for `sorbet-static-and-runtime` instead of `sorbet`: https://github.com/Shopify/tapioca/pull/1005
Removed it from the gemfile.
Existing tests should be enough.

Remove duplicate sorbet dependency

---

lib/tapioca/gemfile.rb
lib/tapioca/helpers/gem_helper.rb
lib/tapioca/internal.rb
lib/tapioca/runtime/loader.rb
spec/tapioca/cli/gem_spec.rb

Solves: https://github.com/Shopify/tapioca/issues/993
Also fixes an internal Shopify/shopify issue 
As Rafael suggested in https://github.com/Shopify/tapioca/issues/993#issuecomment-1156876059, add a filter to reject engines that are part of the application directory 
Change is part of the application loading - can this be tested?

Filter engines in application directory so they are not loaded

---

lib/tapioca/cli.rb
lib/tapioca/commands/gem.rb

Some renaming to make things more explicit.
No behavior change.

Rename parameter `doc` into `include_doc`

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

The specs introduced for `sole` and `find_sole_by` in https://github.com/Shopify/tapioca/commit/5f90df17a9d2b6be03f44ad9cf605743cc17cf5a are not quite right.
See https://github.com/kivikakk/rails/blob/9e1cdf27ebaff31005f3d2bf02d97dfb116a3707/activerecord/lib/active_record/relation/finder_methods.rb#L107-L131.
Added logic for each of these to generated the correct signatures.
Tests adjusted.

Dsl::Compilers::ActiveRecordRelations: fix #find_sole_by, #sole

---

lib/tapioca/runtime/loader.rb

For projects that aren't Rails, such as Tapioca itself, `Rails.root` is `nil`, which then breaks when trying to invoke `Rails.root.to_path`.
Add a check for verifying that `Rails.root` is set before continuing down to list engines. This enables Tapioca to generate RBIs for itself again.
I couldn't figure out a way of forcing `Rails.root` to return `nil`. Let me know if you have ideas.

Use default gemfile path instead of Rails root when listing engines

---

spec/tapioca/cli/gem_spec.rb

When errors occurred, some tests weren't doing the appropriate project cleanup, resulting in hard to read failures.
Move cleanup to an `after` block to guarantee that it happens regardless of errors.

Ensure test project cleanup

---

lib/tapioca/runtime/trackers/constant_definition.rb

Based on [this suggestion](https://github.com/Shopify/tapioca/pull/1025#discussion_r911400473).
We need the line numbers where constants were defined in order to add the [original gem source locations](https://github.com/Shopify/tapioca/pull/1025) for jump to definition. This PR saves this information in the `ConstantDefinition` tracker.
Added a `T::Struct` to keep track of path and line number, started populating it in the tracker and used the new method in the only occurrence of `files_for`.
I contemplated adding a new test only for this tracker, but noticed that's not a pattern we're using in tests. Should I create a new one for this tracker?

Add line numbers to the ConstantDefinition tracker

---

lib/tapioca/dsl/compilers/protobuf.rb
spec/tapioca/dsl/compilers/protobuf_spec.rb

In protobuf, when an optional field has a message subtype it is nilable. Suppose I have some protobuf like:
```
Google::Protobuf::DescriptorPool.generated_pool.build do
add_file("cart.proto", :syntax => :proto3) do
add_message "Cart" do
optional :customer_name, :string
optional :notes,  :message, 2, "google.protobuf.StringValue"
end
end
end
```
Primitives like `:string` are not nilable. So the following are invalid:
```
Cart.new(customer_name: nil) # will error
Cart.new.customer_name = nil # will error
Cart.new.customer_name # returns ""
```
However, submessages are nilable:
```
cart = Cart.new(notes: nil)
cart.notes = nil
cart.notes # returns nil
```
When assembling the `Field` struct, I check if the `descriptor` is an `:optional` and it is a `:message`. If it is, I wrap the type in …

Protobuf: Initializer, getter and setter for optional fields with message subtype should be nilable

---

lib/tapioca/dsl/compilers/active_model_attributes.rb
lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
spec/tapioca/dsl/compilers/active_model_attributes_spec.rb
spec/tapioca/dsl/compilers/active_record_columns_spec.rb

From what I can tell, both:
- empirically from a project I'm working on
- the rails [code](https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/date_time.rb) and [spec](https://github.com/rails/rails/blob/main/activemodel/test/cases/type/date_time_test.rb) 
ActiveModel attributes that are a `ActiveModel::Type::DateTime` or a `ActiveModel::Type::Time` end up as a ruby `::Time`, not a ruby `::DateTime`. 
Small change to use `::Time` rather than `::DateTime`
I updated the existing test for the ActiveModel compiler

ActiveModel DateTime Attribute is a Time, not a DateTime

---

lib/tapioca/dsl/compilers/protobuf.rb

We should not blindly use `"T.nilable(#{type})"` interpolation to generate nilable types since `T.nilable(T.untyped)` is illegal now. We should instead use the `as_nilable_type` helper to generate nilable types.
Also simplifying the logic to check for a nilable type here as well.
Existing tests are unchanged

Use `T.untyped` safe nilability

---

lib/tapioca/helpers/rbi_helper.rb
spec/tapioca/dsl/compilers/active_record_columns_spec.rb
spec/tapioca/helpers/rbi_helper_spec.rb

Fixes #1042 
It turns out that `:4_to_5=` is not a valid symbol but `"4_to_5=".to_sym` does not quote it and represents it as `:4_to_5=` instead of `:"4_to_5"`, which throws off our whole method name validation logic.
The behaviour of Ruby was correct on this symbol until `ruby-2.2.0-preview2`, after which it was broken:
```shell
$ docker run --rm -e "ALL_RUBY_SINCE=ruby-2.0" rubylang/all-ruby ./all-ruby -e "puts '4_to_5='.to_sym.inspect"
ruby-2.0.0-p0       :"4_to_5="
...
ruby-2.2.0-preview1 :"4_to_5="
ruby-2.2.0-preview2 :4_to_5=
...
ruby-3.2.0-preview1 :4_to_5=
```
I think it is related to this change: https://github.com/ruby/ruby/commit/986a893d7a420b8472c06b2e36b71b8bf00e9e21
The fix is to check validity of the name after stripping trailing `=` as well. That leaves `==` as an …

Fix method name validation edge-case

---

lib/tapioca/dsl/compilers/frozen_record.rb

Sorbet doesn't know that `::FrozenRecord::Base` will have `::Tapioca::Dsl::Compilers::Extensions::FrozenRecord` prepended to its `singleton_class`. Therefore, it does not allow us to call the method provided by that module.
`T.unsafe` is used to allow the call, which can be improved.
If we tell Sorbet that `ConstantType` will be the union of both types, it allows us to call the method.
I came up with this approach in #1046, which also makes use of an extension. I did not want to use `T.usafe` if possible, so I came up with this approach.
`bundle exec srb tc` is the test 😅

Remove `T.unsafe` from extension method call

---

lib/tapioca/helpers/rbi_files_helper.rb
spec/tapioca/cli/check_shims_spec.rb

Do not index files typed: ignore when running `check-shims`

---

.github/workflows/ci.yml
sorbet/rbi/shims/rdoc.rbi

Let's enable this on CI so we can keep our RBI shims up-to-date (as shown in the second commit of this PR).

Run command `check-shims` on CI

---

.github/CODEOWNERS

I find myself requesting the same group over and over again. As code maintainers it seems that `@Sorbet` should be required for review on every pull-request. 
By adding this file we automate the process.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

Add CODEOWNERS to repo

---

lib/tapioca/commands/annotations.rb
spec/tapioca/cli/annotations_spec.rb

`tapioca annotations` currently removes the final newline from every annotation RBI file. This triggers linting errors in projects where linters expect every file to have a final newline.
See https://github.com/Shopify/rbi-central/issues/83
Don't remove final newlines when splitting up the annotation files to add the header.
Modified existing tests to pass with this change.

Do not remove final newlines from annotations

---

README.md
lib/tapioca/cli.rb
lib/tapioca/commands/check_shims.rb
lib/tapioca/helpers/rbi_files_helper.rb
lib/tapioca/internal.rb
spec/tapioca/cli/check_shims_spec.rb

Running `tapioca check-shims` can take up to 7min in Core (~13 when running on CI). The culprit is parsing the RBI files.
This PR proposes to speed up the process by parallelizing RBI parsing.
I reused `Executor` that we already use to parallelize RBI generation.
No behavior change.
I tested the speed-up on Tapioca itself:
Before:
```shell
$ time bundle exec tapioca check-shims
Loading Sorbet payload...  Done (5.36s)
Loading shim RBIs from sorbet/rbi/shims...  Done (0.01s)
Loading gem RBIs from sorbet/rbi/gems...  Done (17.93s)
Looking for duplicates...  Done (0.02s)
real	0m24.291s
user	0m23.251s
sys	0m0.564s
```
After:
```shell
$ time bundle exec tapioca check-shims -w 10
Loading Sorbet payload...  Done (1.51s)
Loading shim RBIs from sorbet/rbi/shims...  Done (0.21s)
Loading gem RBIs …
```

Parallelize RBI parsing to speed up the `check-shims` command

---

lib/tapioca/internal.rb
lib/tapioca/sorbet_ext/proc_bind_patch.rb
sorbet/rbi/shims/sorbet.rbi
spec/tapioca/gem/pipeline_spec.rb

When we generate gem RBIs, we're not carrying over proc bindings from existing signatures. The reason is because `sorbet-runtime` doesn't actually keep track of the bind and just discards it.
This ends up creating some frustration when generating gem RBIs as proc bindings are ignored.
Add a new Sorbet patch to keep track of the bind and print the `T::Types::Proc` name including it.
Added an example in the pipeline spec.

Track proc bindings of existing signatures

---

lib/tapioca/gem/listeners/source_location.rb
spec/tapioca/gem/pipeline_spec.rb

When methods for gem RBIs come from Ruby itself, we are currently adding the full location. This is not ideal, since each user could have Ruby installed in a different folder, which may also include platform specific labels.
We have to sanitize the `RUBY_ROOT` from the locations printed in order to properly add it in the Ruby LSP and provide navigation to Ruby's original source.
Additionally, we were also adding source locations for native extension files (like `.so` and `.bundle`). I don't think there's value in adding those, since it is not possible to navigate to them.
To address point 1, I have added a new `sub` that changes the Ruby root for the literal `RUBY_ROOT` string, which we can easily replace in the Ruby LSP for the real `ENV["RUBY_ROOT"]` to point to the right URI.
To …

Handle the Ruby root in source locations listener

---

README.md
tasks/readme.rake

The Kramdown block attribute was not working properly on Github and we ended up showing a `{:.no_toc}` on the README page.
This PR fixes that by moving that annotation to an HTML comment on the raw text of the header that we match against to filter it out.
I also took the opportunity to encapsulate some of the operations we were performing into a custom converter class that inherits from the built-in `Toc` converter. This makes the code more readable.
No added tests.

Fix no_toc annotation

---

lib/tapioca/helpers/rbi_files_helper.rb
spec/tapioca/cli/check_shims_spec.rb

While we check scopes and methods duplicated between generated RBIs and shims, we do not check anything about mixins.
Consider this:
```rbi
module Bar; end
class Foo
include Bar
end
```
```rbi
class Foo
include Bar
end
```
The shim file is actually useless and could be deleted without impacting type checking since the include is already known.
We can reuse the indexing mechanism already in place for other properties to check for duplicates. We just need to look for `RBI::Mixin` nodes and `RBI::RequiresAncestor` nodes.
One limitation of the static approach is that we do not resolve constants when checking for duplicates so something like this would not be considered a duplicate:
```rbi
module A
class B
include C
end
end
module A
class B
include ::C
end
end
```
Because we can't really …

Also check duplicated mixins in shims and TODO files

---

lib/tapioca.rb
lib/tapioca/cli.rb
lib/tapioca/runtime/trackers/constant_definition.rb

When profiling why this command was taking so much time, I found out that in the specific application I was working on 37% of the time was spent in the `TracePoint#method_id` method.
Since we don't need this TracePoint enabled in this command, this patch disables it.
Total time went down from 3:50min to 1:20min

Disable TracePoints when running the check-shims command

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb

The method `subtype` was made public in rails 7, but it did exist previously so we can use it via `send`.
With rails < 7, tapioca dsl crashes with: `lib/tapioca/dsl/helpers/active_record_column_type_helper.rb:122:in 'enum_setter_type': private method 'subtype' called for #<ActiveRecord::Enum::EnumType:0x000055c8a8aefb70> (NoMethodError)`
subtype was not public in rails 6, but it did exist since at least 5.0 https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/enum.rb#L143
No idea how to add a test for this.

Don't crash on rails < 7

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Currently the return value of e.g. `Post#find` gets generated as untyped. We could catch some subtle bugs if it was typed.
Imagine a novice Rails dev who's not familiar with which finder method would return `nil` and which would raise exception if no record was found. Sorbet could warn e.g. if we tried to `nil` check on the return value of a `find`.
I first thought that `find` always returns with a model, but it turned out it can be used to [query multiple record at once](https://api.rubyonrails.org/v7.0.3/classes/ActiveRecord/FinderMethods.html#method-i-find) so I went with a union type: either the model or an array of the models is returned.
(Some more background: `rails-sorbet` chose to [support only the one model retrieval for …

Make ActiveRecord#find return value typed

---

.github/workflows/ci.yml
bin/test
gemfiles/Gemfile-rails-6-1
gemfiles/Gemfile-rails-main
spec/tapioca/dsl/compilers/active_record_columns_spec.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Some of our DSL generators depend on Rails code, which might change between versions.
Since Rails is an important dependency and people might be still in an old version. It is better to test against all of them.

Test with supported versions of Rails

---

lib/tapioca/gem/pipeline.rb
spec/tapioca/gem/pipeline_spec.rb

Address https://github.com/Shopify/rbi-central/pull/94 in Tapioca for more resilience.
This PR changes how we get file candidates for a given constant which allows us to attribute the constant to a gem or not. We use the `Pry::WrappedModule` class to help us do that, so that we don't have to reimplement that logic ourselves.
While that's been working really fine so far, it turns out that Pry does a lot of extra work to get a list of candidates for a given wrapped module. One of these extra things is to attribute the methods that are introspected to the constant that defines them in the source file. This is not only a performance issue, but it was also failing for methods added to `Object` by being defined at the top level, and was resolving their `file`s as `nil`.
Since we don't need the …

Properly discover methods added to `<main>` object

---

lib/tapioca/dsl/compilers/active_record_fixtures.rb
lib/tapioca/helpers/test/template.rb
spec/tapioca/dsl/compilers/active_model_secure_password_spec.rb
spec/tapioca/dsl/compilers/active_record_associations_spec.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Our builds against Rails `main` have been failing, so this PR attempts to address all the changes since Rails 7.
Each commit explains what was changed with a link to upstream change that made it necessary.
No additional tests

Fix failures against Rails `main`

---

lib/tapioca/loaders/loader.rb
spec/tapioca/cli/dsl_spec.rb

Resolves https://github.com/Shopify/tapioca/issues/1080
Rescue exceptions thrown during eager loading of the rails application
Added a test

Report Rails load errors and continue generating

---

lib/tapioca/gem/listeners/foreign_constants.rb
lib/tapioca/runtime/reflection.rb
lib/tapioca/runtime/trackers/mixin.rb
spec/tapioca/cli/gem_spec.rb

Closes #1097.
Historically, to identify the attached class of a singleton class, we've parsed the name (result of the`#inspect` method) of the singleton class and then constantized the result. However, this doesn't work when the `#inspect` method of a singleton class is overridden because the return value of `#inspect` no longer conforms to the structure we expected.
We can fix this problem by searching `ObjectSpace` for the class that has the correct singleton class. This is less performant but more correct.
Added a test that fails without the changes and passes with them. Existing tests continue to pass.

New approach to finding attached class

---

README.md
lib/tapioca/cli.rb
lib/tapioca/commands/dsl.rb
lib/tapioca/dsl/pipeline.rb
spec/tapioca/cli/dsl_spec.rb

Since we are now loading all compilers from any loaded gem that exports a DSL compiler, the full set of DSL compilers in play might be a little confusing.
Thus, this PR adds a way to ask Tapioca to list the set of DSL compilers and get a tabular output that shows them as well as their enabled/disabled status.
Added CLI tests for the feature.

Add flag to list compilers for DSL command

---

lib/tapioca/dsl/pipeline.rb
lib/tapioca/gem/listeners/subconstants.rb
lib/tapioca/gem/pipeline.rb
lib/tapioca/runtime/reflection.rb
spec/tapioca/gem/pipeline_spec.rb

I noticed that Tapioca was not generating RBIs for constants that have their value set to nil. E.g.:
```ruby
FOO = nil # => ignored by Tapioca
```
The reason is because inside `constantize`, applying `const_get` will return `nil` and then we skip that constant. I'm not sure if that was intentional, so I appreciate feedback on the implementation.
Basically, moved part of the implementation of `constantize` to only skip constants that are not defined and include the ones that have their value set to `nil`.
Added an example.

Handle constants with nil value

---

lib/tapioca/dsl/compilers/active_record_relations.rb
manual/compiler_activerecordrelations.md

There have been a few PR's attempting to introduce a union type on `ActiveRecord::Base#find` when noticing the untyped declaration in sorbet files. Including my own in https://github.com/Shopify/tapioca/pull/1145. https://github.com/Shopify/tapioca/pull/1101 has some relevant conversation when the union type was originally reverted.
This was a deliberate decision to avoid forcing a union on large codebases. This documents that decision
Updated the manual
Are tests required for markdown?
See #1145 for discussion

Document the reason for keeping find untyped

---

lib/tapioca/dsl/compilers/graphql_input_object.rb
lib/tapioca/dsl/compilers/graphql_mutation.rb
lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/compilers/graphql_input_object_spec.rb

When the class is anonymous, `qualified_name_of` returns `nil`. This
means that `type_for` would raise an exception, causing the rbi generator
to fail.
Return `T.untyped` for the anonymous case
Those commits are already applied to master (I used VSCode to sync the code and it end up pushing the changes), so this is only for the 0-10-stable branch.

Make sure we can type GraphQL object with anonymous input fields

---

Gemfile.lock
lib/tapioca/version.rb

This PR bumps the gem version ahead of releasing 0.10.1
The `VERSION` constant was incremented and `bundle install` was run to update `Gemfile.lock`.
I have drafted [release notes](https://github.com/Shopify/tapioca/releases/edit/untagged-b1110106e7588135b7a8).
Not applicable.

Prepare for 0.10.1 release

---

lib/tapioca/gemfile.rb
lib/tapioca/helpers/gem_helper.rb
spec/spec_with_project.rb
spec/tapioca/cli/gem_spec.rb

Fixes #1174
The simplistic `start_with?` check was not sufficient to match that a given file/folder was under a given folder, since we were not explicitly checking for full folder name matches. For example, if `path = "/foo/bar-gem/baz"` and `folder = "/foo/bar"`, then `path.start_with?(folder)` would return `true`, but `path` is not under the `folder` directory.
This commit fixes the problem by matching `folder` to any of the parent directories of `path` by using the `Pathname#ascend` method to get all parent directory prefixes of a `path`.
Added a test that fails without the fix.

Start matching pathname directory prefixes more rigorously

---

lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/compilers/graphql_mutation_spec.rb

GraphQL deserializes this type into a `Time`, not a `DateTime`.[^1]
[^1]: [See the implementation of `ISO8601DateTime`](https://github.com/rmosolgo/graphql-ruby/blob/2515f2ad938265c7e3adc6d9f127539fd15bd76a/lib/graphql/types/iso_8601_date_time.rb#L55)
The type is updated and the test is too.
I've backported this to `0-10-stable` in #1197.
✅

Use correct type for `GraphQL::Types::ISO8601DateTime`

---

spec/spec_helper.rb

Our test backtrace messages are too noisy and include frames from Sorbet runtime, the Railties runner and our test helpers like the `Isolation` helper module.
This commit filters out those frames from the backtrace, leaving only the frames pertinent to the test failure.
No new tests

Filter backtrace locations in test errors

---

spec/tapioca/dsl/compilers/active_record_scope_spec.rb

Add a test case for #1081, which shows (and ensures) that the scopes are generated.
Added a test case for `ActiveRecordScope` generator that ensures the expected scopes are generated for enum attributes

Add test to ensure scope for enum attributes are generated

---

lib/tapioca/cli.rb
spec/tapioca/cli/dsl_spec.rb

Fixes #1172 
Use the [`check_unknown_options!` method on `Thor::Base`](https://github.com/rails/thor/blob/e4907fdd663d0a1ff51d18eb1827552ee61300a3/lib/thor/base.rb#L150-L154) to enforce option correctness.
Added a CLI test to the DSL spec.

Show error and fail early for unknown options

---

Gemfile.lock
sorbet/rbi/gems/rbi@0.0.16.rbi
spec/tapioca/gem/pipeline_spec.rb
tapioca.gemspec

There was a change in the RBI gem (https://github.com/Shopify/rbi/pull/140) to stop sorting `prop` and `const` attributes on T::Struct objects. This change has broken a test in the tapioca test suite that assumed such fields would be sorted alphabetically by name. See #1201 for the test failing in CI.
I updated the RBI gem to the latest version and fixed the tests in question.
No new tests, existing tests pass CI.

Update RBI gem and fix tests

---

README.md

It's listed in the example and not too hard to deduce by copy-pasting the example and tweaking until it works (or have `srb tc` complain), but it is never actually explained. 
cc @paracycle from our Slack convo

Add explanation in readme what ConstantType is for

---

lib/tapioca/cli.rb

We should wrap all command executions inside `Tapioca.silence_warnings` so that we can suppress warnings in the CLI output, like the ones from the parser gem that fails out 3.2-head tests.
Expect existing tests to pass on 3.2 builds

Silence warnings in all CLI output

---

spec/tapioca/cli/dsl_spec.rb

Address feedback in https://github.com/Shopify/tapioca/pull/1220/files#r993606253
Write the model files directly rather than having to move them.
n/a

Improve DSL test for custom `app_root`

---

.github/workflows/ci.yml

Experimental Ruby 3.2 builds are failing because Nokogiri's precompiled native platform gem only supports up to Ruby 3.1.
Example failure: https://github.com/Shopify/tapioca/actions/runs/3283616191/jobs/5408560879#step:3:41
CI should regenerate the lockfile when running on an unreleased version of Ruby.
Ruby 3.2 should run as expected.

ci: regenerate Gemfile.lock when running on ruby head

---

spec/helpers/mock_project.rb

Currently, our test suites with Ruby 3.2 are failing ([example](https://github.com/Shopify/tapioca/actions/runs/3337789715/jobs/5524586722)). This is because we try to install `bundler` `2.4.0.dev` based on the value of `Bundler::VERSION`, which is not released on rubygems.org yet.
Before installing `bundler` for our mock projects, check if the target bundler version is a prerelease. If it is, skip that version and just install the latest available version.
This PR is to fix CI builds, so it doesn't need extra tests other than existing ones.

Avoid installing prerelease bundler for mock project

---

dev.yml

With the patch, Dev downloads a precompiled binary, but without it seems to choose to compile from source, which seems unnecessary.
The config is updated to Ruby 3.1.2, the latest in the 3.1 releases.
🎩'd locally.

Add patch to Ruby version in `dev.yml`

---

lib/tapioca/helpers/gem_helper.rb

Found by #1287.
The variable `project_path` defined at https://github.com/Shopify/tapioca/blob/main/lib/tapioca/loaders/loader.rb#L85 is actually a `Pathname`.
Let's accept both `String` and `Pathname`.

`GemHelper#gem_in_app_dir?` accepts a Pathname

---

spec/tapioca/cli/dsl_spec.rb

Found with #1287. This one is also very funny.
Since the `dsl --only` [option accepts an array](https://github.com/Shopify/tapioca/blob/main/lib/tapioca/cli.rb#L89), `Post` was considered as the name of a compiler rather than the class to produce the RBI for.
Since we only have one class, passing explicitly `Post` doesn't change much but I inverted the argument and option as to keep the original meaning.

Do not pass `Post` as value to `dsl --only`

---

lib/tapioca/dsl/compiler.rb
spec/tapioca/dsl/compiler_spec.rb

#1288 showed that we have no tests that fully exercise the functionality for the signature handling code that lives inside the `Dsl::Compiler` class.
Added a `CompilerSpec` file that exercises a `PostCompiler` compiler that would always create methods from the definitions of instance methods on a `Post` class. Each test case, then, defines a particular type of `Post` class to test behaviour.
This has already shown that we were not doing full sanitization on return types and would leave things like `T.proc.params.returns(<VOID>)` intact if it was the return type.
This PR is mostly just adding tests

Add test for `Dsl::Compiler` base class

---

lib/tapioca/commands/configure.rb
spec/tapioca/cli/configure_spec.rb

Noticed when working on `ruby-lsp`:
https://github.com/Shopify/ruby-lsp/blob/20f7a9798cc7e0e94d164906e04c0372b7260d20/sorbet/tapioca/require.rb#L4

Fix typo in boilerplate

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Noticed I missed typing for these. https://api.rubyonrails.org/classes/ActiveRecord/SignedId/ClassMethods.html was added in Rails 6.1.
Similar to existing finder methods.
Tests added.

Decorate ActiveRecord::SignedId finder methods

---

.github/workflows/ci.yml
Gemfile.lock

As mentioned in #1306, we'd been observing some tests failures with message `rubygems/specification.rb:2121:in 'method_missing': undefined method 'identifier' for #<Gem::Specification:0x0000562ed629c100> (NoMethodError)`. We investigated this with @Morriar and were not able to reproduce the error locally or on Spin however hard we've tried.
What does not make sense about the whole thing is that at that point in the code where the failures always happen, there shouldn't be any instances of `Gem::Specification` anywhere, all entries should be `Bundler::StubSpecification` instances. So the error is quite unexpected.
We ultimately noticed 2 important things about our CI:
1. Our CI runs for non-main `Gemfile`s do not install a recent enough Bundler version. Since there is no lockfile …

Fix CI flakyness with respect to `Bundler`

---

spec/tapioca/gem/pipeline_spec.rb

Related to #1306 
I have no idea why we've started seeing these creep into our RBI files for some tests on CI, but I can't reproduce it locally, so I'm going to start filtering these out again to make our CI green.
Partially revert the change that was done in [445d9ef5ecee5acb98a835a56d9969a2be2f016d](https://github.com/Shopify/tapioca/commit/445d9ef5ecee5acb98a835a56d9969a2be2f016d#diff-98bc3f9ecbf2cc271100cfb6c25897bbfa5fc8ee53726bb0da2f67a702984facL325).
Updating tests

Start filtering `::PP::ObjectMixin` again

---

lib/tapioca/dsl/compilers/active_record_relations.rb

Fixes #1324 
By making sure that the `SignedId` class is defined, we can support Rails 6.0 and not try to generate any signed id finder methods.
No tests added since we don't test against Rails 6.0. This is a best-effort support for that Rails version with minimal code changes.

Support Rails 6.0 which has no `SignedId` class defined

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
sorbet/rbi/shims/activerecord_postgresql.rbi

A new PR for https://github.com/Shopify/tapioca/pull/1268 because I don't have push permissions to the fork.
When using an hstore column in postgres, tapioca generates "T.untyped". Both keys and values in hstore are strings.
Added a case for hstore to the existing case statement.
Testing this is hard because we can't use postgres columns with sqlite. Open to other testing suggestions

Add types for postgres hstore & arrays

---

lib/tapioca/dsl/compilers/active_record_columns.rb
manual/compiler_activerecordcolumns.md
spec/tapioca/dsl/compilers/active_record_columns_spec.rb

Closes https://github.com/Shopify/tapioca/issues/1351
`_default_attributes` contains the contents of `columns_hash` and virtual attributes, see
- https://github.com/rails/rails/blob/v7.0.4/activerecord/lib/active_record/model_schema.rb#L486-L489
- https://github.com/rails/rails/blob/v7.0.4/activerecord/lib/active_record/attributes.rb#L288
Test added.

Teach ActiveRecordColumns compiler about virtual attributes

---

lib/tapioca/dsl/compilers/active_record_relations.rb
lib/tapioca/rbi_ext/model.rb
sorbet/rbi/gems/rbi@0.0.16.rbi

Relying on lazily evaluated instance variables instead of passing around initialized module scopes makes the code much more readable and easier to understand.
Simple refactor.
No added tests.

Refactor AR relations compiler to pass less parameters around

---

lib/tapioca/gem/pipeline.rb
spec/tapioca/cli/gem_spec.rb
spec/tapioca/gem/pipeline_spec.rb

Fixes #1326 
When we are generating value constants (i.e. constants that have a value that is not a module), we didn't have a good way to filter them based on where they were defined, since we couldn't ask them before.
However, since Ruby 2.7, we have access to `const_source_location` so we can check to see if a value constant has been defined by the current gem or not. So the implementation uses that.
Updated existing tests to test for this specific case where the `bar` gem is reopening a constant defined by the `foo` gem and adds a value constant under it. The expectation is that only the subconstant added in `bar` gem is generated in `bar.rbi` and none of the other subconstants defined in `foo`.
I also tested this against Core and it works without problems (and gets rid of a lot of …

Stop regenerating all value constants for reopened types

---

lib/tapioca/dsl/compilers/active_record_relations.rb
lib/tapioca/dsl/compilers/active_record_scope.rb
spec/tapioca/dsl/compilers/active_record_scope_spec.rb

At the moment sorbet can't figure out that classes, that are marked as abstract, have access to scopes. The following example illustrates this:
```ruby
class A < ApplicationRecord
extend T::Sig
abstract_class = true
scope :deleted, -> { where.not(deleted_at: nil) }
class << self
extend T::Sig
sig { returns(Integer) }
def count_deleted
deleted.count
end
end
end
```
Since those scopes can be used, I think it makes sense to generate the rbi files accordingly.
I removed the filter for abstract classes in `ActiveRecordScope` and did the same thing in `ActiveRecordRelations` to make the generated relation methods work.
Tests for `ActiveRecordScope` have been extended.

Make scopes available for abstract classes

---

lib/tapioca/dsl/compilers/active_record_secure_token.rb
lib/tapioca/dsl/extensions/active_record.rb
lib/tapioca/dsl/helpers/active_record_constants_helper.rb
manual/compiler_activerecordsecuretoken.md
manual/compilers.md
spec/tapioca/cli/dsl_spec.rb
spec/tapioca/dsl/compilers/active_record_secure_token_spec.rb

Found myself having to write a couple of shims for this, so here's a small compiler for https://api.rubyonrails.org/classes/ActiveRecord/SecureToken/ClassMethods.html which was added in Rails 5.
Used the same extension used for delegated types.
Added tests

Add Active Record secure token compiler

---

lib/tapioca/cli.rb
lib/tapioca/commands/dsl.rb
lib/tapioca/dsl/pipeline.rb
lib/tapioca/static/symbol_loader.rb
spec/tapioca/cli/dsl_spec.rb

We often want to generate RBI for every model, worker, etc inside a namespace. Currently the only way to do that involves crawling ObjectSpace in a console or doing grep/sed magic to get the set of constants. We wanted an easier way to do this.
Another future-facing use-case is being able to run `tapioca dsl --verify some/specific/path`.
- Sidenote: At the moment, `--verify` fails unless it's called with no arguments since it thinks there's stale RBI, but that's something that can be fixed separately.
I thought it would be most ergonomic to be able to pass directory/filenames as args to the `tapioca dsl` but currently it's assumed that any non-flag args passed will be class names. Luckily, ruby class names and file names follow disjoint patterns:
- class names must start with a capital …

Support generating DSL RBI by path

---

lib/tapioca/loaders/loader.rb
spec/tapioca/cli/dsl_spec.rb

Tapioca does not show the place where the error happen,
when it tries to load rails application.
Current solution:
```
Loading Rails application... Tapioca attempted to load the Rails application after encountering a `config/application.rb` file, but it failed. If your application uses Rails please ensure it can be loaded correctly before generating RBIs.
undefined method `active_record' for ...
Continuing RBI generation without loading the Rails application.
```
Proposed:
```
Loading Rails application... 
Tapioca attempted to load the Rails application after encountering a `config/application.rb` file, but it failed. If your application uses Rails please ensure it can be loaded correctly before generating RBIs.
undefined method `active_record' for ... …
```

Print backtrace information

---

lib/tapioca/commands/dsl.rb
spec/tapioca/cli/dsl_spec.rb

#968 added support for generating DSL RBI via a path like `bin/tapioca dsl app/models`. The way it works is using `Static::SymbolLoader.symbols_from_paths` to find all constants defined in those paths and then acting as if you called `bin/tapioca dsl <those constants>`.
When testing this out for the first time, I realized that sometimes `symbols_from_paths` found constants that weren't actually loaded (or loadable) and would then raise an exception. Two common examples in our codebase:
1. A constant defined inside an eigenclass, for example
```ruby
class Foo
class << self
BAR = nil
end
end
```
In this example, `Foo::BAR` is a constant returned from `symbols_from_paths` but you can't actually reference it outside the eigenclass.
2. Any constants (e.g. helper modules) defined in test …

Avoid raising when constantizing from paths

---

lib/tapioca/dsl/pipeline.rb
lib/tapioca/loaders/dsl.rb
spec/tapioca/cli/dsl_spec.rb

A point of friction we've experienced is getting blocked from running DSL generation due to pending migration even when we're not generating RBI for ActiveRecord models (e.g. when doing something like `bin/tapioca dsl Some::Sidekiq::Worker Some::Graphql::Mutation`) . The pending migration check is valuable to ensure we don't generate ActiveRecord RBI with a stale schema, but it's irrelevant when generating RBI for things like sidekiq workers, graphql mutations, or other non-ActiveRecord things.
Since we want to conditionalize running the pending migrations check, we need to be at a point where we have the constants we're going to process in memory.  This means we need to pull the pending migrations check out from the `Loaders::Dsl` further down into the `Dsl::Pipeline`. We then check to …

Only run pending migrations check if necessary

---

Gemfile.lock
lib/tapioca/gemfile.rb
spec/tapioca/cli/gem_spec.rb
tapioca.gemspec

This piece of code was brittle and causes an error in the latest bundler version.
Instead of supporting different method arity's which could keep changing in the future we can remove support for the old Bundler API. [v2.2.25](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.25) has been out since July 2021. Users with old versions of Bundler will not be able to use future Tapioca versions.
Locally tested using `BUNDLER_VERSION=2.4.9 bundle exec tapioca gem --verify` and bumped the version used in tapioca to trigger CI run with latest bundler.

Remove support for old Bundler API in materialize_deps

---

lib/tapioca/helpers/gem_helper.rb
spec/tapioca/gemfile_spec.rb

This is similar in spirit to https://github.com/Shopify/tapioca/pull/34, except that it's probably a much less common scenario.
At GitHub we vendor a Ruby build within our app directory, which means that our default gems meet the conditions of the `gem_in_app_dir?` method—they are within the app, but not in the bundle directory. That results in these default gems getting ignored.
We also sometimes generate PRs via GitHub actions, using Ruby from the setup-ruby action. In these scenarios the default gems are not within the app, and are thus not ignored. To get around having PRs that continuously add and remove these rbis, we ended up explicitly excluding them.
This PR aims to make the behavior consistent regardless of where Ruby is installed.
This PR checks if the gem in question is within …

Don't ignore default gems if Ruby vendored in app

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb

Resolves https://github.com/Shopify/tapioca/issues/1437
I was under the assumption if `ActiveRecord::ConnectionAdapters::PostgreSQL` is defined `OID` would be loaded too but that doesn't have to be the case if the connection adapter is loaded manually
Now we check for the exact class we're referencing instead.
Tested locally in a demo application 👍

Check if OID is defined before referencing

---

lib/tapioca/gem/listeners/methods.rb
lib/tapioca/helpers/rbi_helper.rb
lib/tapioca/runtime/dynamic_mixin_compiler.rb

New version of Sorbet will prohibit initialising abstract classes directly ([related PR](https://github.com/sorbet/sorbet/pull/6273)), which means `Param` could not be directly used anymore. And as @Morriar pointed out in https://github.com/Shopify/rbi/pull/160#pullrequestreview-1371602446, we should use `ReqParam` for the current `Param` usages anyway. 
Replace `Param` invocations with `ReqParam`.
I think existing tests should already cover those cases.

Use `ReqParam` instead `Param` because `Param` is an abstract class

---

lib/tapioca/dsl/extensions/active_record.rb

This change fixes running `tapioca dsl` command for Rails 5 based applications: it fixes eager loading Rails applications.
Before the fix, `tapioca dsl` command could not eager load rails applications based on Rails 5.x. The command failed because of an uninitialized constant `ActiveRecord::SecureToken::MINIMUM_TOKEN_LENGTH` (it was added in Rails 6.1). Further, `has_secure_token` has only one parameter in Rails 5.x.
We don't use built-in ActiveRecord related dsl compilers, but we still have the problem. It seems the patch of `has_secure_token` method is loaded always.
The fix changes the definition of `has_secure_token` method inside `Tapioca::Dsl::Compilers::Extensions::ActiveRecord` module: `**` is used for `length` parameter, so the definition could be compatible with Rails 5.x.
No …

Fix running `tapioca dsl` for Rails 5.x based applications

---

lib/tapioca/dsl/compilers/identity_cache.rb
spec/tapioca/dsl/compilers/identity_cache_spec.rb

Following https://github.com/Shopify/identity_cache/pull/534, IdentityCache will define `fetch_multi_by` for `cache_index` invocations regardless of the number of keys included in the index. (Previously only single-index keys were supported.)
We should lift the `field_length` restriction accordingly.
Removes the `field_length == 1` restriction (as well as the `field_length` variable designation, which is now useless).
~Nothing changed.~
Updated a unit test implicitly testing this behavior in https://github.com/Shopify/tapioca/pull/1468/commits/64983d4af1eaaf4b383e1506c617e0cfbac0bbf9.

feat: consistently define `fetch_multi_by`

---

lib/tapioca/dsl/compilers/active_record_scope.rb
spec/tapioca/dsl/compilers/active_record_scope_spec.rb

We encountered a strange situation where CI was reporting that a rbi file has changed and needs to be regenerated, but running `bin/tapioca dsl` locally on the dev environment would not generate any changes.
It seems on the CI build, a method in one of the rbi files is generated twice while on dev environment not, leading to CI failing all the time we regenerate the rbis. It is unclear why this is happening, the same version of tapioca is used in both cases and there is no obvious reason why it is happening.
As a workaround we had to undo the changes to that rbi file on each branch, leading to confusion within the team.
After investigation I found that the ActiveRecordScope Compiler gathers scope methods until it hits "ActiveRecord::Base" and concatenates the methods in an array. The …

Fix ActiveRecordScope Compiler to not duplicate relation methods of superclass

---

Gemfile.lock
lib/tapioca/version.rb

Since the latest release of the 0.11.4 version, many changes have been shipped and are waiting to be deployed (https://github.com/Shopify/tapioca/compare/v0.11.4...main?expand=1), including bug fixes.
In this PR we bump the gem to v0.11.5 to cut a new release.
/
/

Bump tapioca gem version to 0.11.5

---

lib/tapioca/executor.rb
spec/executor_spec.rb

Fixes #1224 by syncing tapioca's parallelism behaviour with [the `Parallel` gem's behaviour](https://github.com/grosser/parallel/blob/39282047b98cb4be7cd738c218513501a55b571b/lib/parallel.rb#L341-L344).
Added a helper to mimic `Parallel`'s behaviour.  The tests are a little more involved than the rest of Tapioca's, so please let me know if those can be simplified 🙏 
✅ There are tests!

Limit parallel work to `PARALLEL_PROCESSOR_COUNT`

---

.github/workflows/ci.yml

To reduce Dependabot noise such as https://github.com/Shopify/tapioca/pull/1478
Specify only the major version, so that GH uses the latest available within the major range.

Relax constraint for `actions/checkout`

---

README.md
lib/tapioca/cli.rb
lib/tapioca/commands/dsl.rb
lib/tapioca/commands/gem.rb
lib/tapioca/loaders/dsl.rb
lib/tapioca/loaders/gem.rb
lib/tapioca/loaders/loader.rb
spec/tapioca/cli/dsl_spec.rb
spec/tapioca/cli/gem_spec.rb

Resolves https://github.com/Shopify/tapioca/issues/1500
Apps that want the previous functionality can use --no-halt-upon-load-error
Current behaviour is hiding legitimate errors and requires inspecting the logs
Raise the exception thrown from `config/application.rb` if the new `halt-upon-load-error` flag is set
Included.

Default to raising exception if Rails app cannot be loaded

---

lib/tapioca/dsl/compilers/protobuf.rb
spec/tapioca/dsl/compilers/protobuf_spec.rb

Fix #1533
The realization is that you can't assign an array type to `Map` fields and that you can't assign a hash type to `Repeated` fields. So we can use that to detect the type of the field.
We try to instantiate a new instance of the constant type, setting the value of the current descriptor field to an empty hash. If the type is `Map`, then it will succeed. If it's `Repeated`, it will fail.
Another small change in this PR makes it so that when we fail to read the type of the descriptor for repeated/map fields, we won't end up generating invalid RBI files, due to the message class not having a name.
Added failing tests that pass after the changes.

Simplify check for `Google::Protobuf::Map` type - redux

---

lib/tapioca/dsl/compilers/protobuf.rb
spec/tapioca/dsl/compilers/protobuf_spec.rb

There is no point in trying to construct elaborate default values for the initializer fields, since in the RBI file, the default value is meaningless. What matters is the type of the field and if the field is optional or not. Thus, we can easily simplify the code and generate default values as `T.unsafe(nil)`.
Change default values to `T.unsafe(nil)`.

Simplify protobuf compiler default field values

---

lib/tapioca/dsl/compilers/graphql_mutation.rb
spec/tapioca/dsl/compilers/graphql_mutation_spec.rb

The generated sig is wrong when a Graphql mutation argument specifies a type that is automatically "loaded".
Check whether each argument uses the loads keyword

Handle arguments with loads in Graphql mutations

---

.github/workflows/ci.yml
.rubocop.yml
lib/tapioca/sorbet_ext/generic_name_patch.rb
tapioca.gemspec

Ruby 2.7 has been EOL since 31 Mar 2023.

Drop Ruby 2.7 support

---

spec/tapioca/dsl/compilers/active_model_secure_password_spec.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Rails HEAD builds have been having some test failures for some time now, but they pass since they are marked as `experimental`.
The behaviour of Tapioca was already correct, it was the tests that were missing some generated methods, so I added missing generated methods to the test cases.
Updated tests

Fix Rails head builds

---

lib/tapioca/dsl/compilers/graphql_mutation.rb
lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/compilers/graphql_mutation_spec.rb

We were generating `T.untyped` for some of the cases we could handle, which became apparent with the recent change to the mutation compiler to support argument with loads in #1556.
/cc @such
This PR does a few things:
1. It extends the `GraphqlTypeHelper#type_for` method to handle `NonNull` types and types that are just plain module references.
2. It simplifies the argument loads type mapping code.
3. It refactors, updates and slightly extends the existing tests.
Updated tests

Improve GraphQL Mutation compiler

---

lib/tapioca/cli.rb
lib/tapioca/commands.rb
lib/tapioca/commands/abstract_gem.rb
lib/tapioca/commands/gem_generate.rb
lib/tapioca/commands/gem_sync.rb
lib/tapioca/commands/gem_verify.rb

We'd been using the `Gem` command to perform three distinct tasks:
1. synchronize RBI files for gems
2. generate RBI files for specified or all gems
3. verify that the gem RBI files are up-to-date
All of this functionality bunched together in a single command was making it hard to change behaviour or to add uniform behaviour to all `Command` classes, since not all of them would call the `execute` method in the end.
This PR extracts an abstact gem command super class and splits the previous `Gem` command into separate commands that each handle one of these three tasks.
There should be no behaviour change.

Extract multiple commands from `Gem` command

---

lib/tapioca/cli.rb
lib/tapioca/commands/annotations.rb
lib/tapioca/commands/check_shims.rb
lib/tapioca/commands/command.rb
lib/tapioca/commands/configure.rb
lib/tapioca/commands/dsl_compiler_list.rb
lib/tapioca/commands/dsl_generate.rb
lib/tapioca/commands/dsl_verify.rb
lib/tapioca/commands/gem_generate.rb
lib/tapioca/commands/gem_sync.rb
lib/tapioca/commands/gem_verify.rb
lib/tapioca/commands/require.rb
lib/tapioca/commands/todo.rb

Finally getting around to https://github.com/Shopify/tapioca/pull/1218#pullrequestreview-1134759632 comment by @Morriar.
By making the abstract `execute` method be a private method, we can ensure that all commands are invoked via the `run` method, which allows us to wrap them in `Tapioca.silence_warnings` today and potentially do more in the future.
Add `Command#run` method that calls `Command#execute` and make `Command#execute` a private method. Encapsulate all `Tapioca.silence_warnings` calls.
There should be no behaviour change.

Refactor `Command` classes to make `run` method the public API

---

README.md
lib/tapioca/loaders/dsl.rb
spec/tapioca/cli/dsl_spec.rb

This PR adds support for loading custom extension classes in addition to Tapioca's built-in extensions. See #1600 for more details.
Updated `Tapioca::Loaders::Dsl.load_dsl_extensions` to behave similarly to `Tapioca::Loaders::Dsl.load_dsl_compilers` and require all Ruby files found in `sorbet/tapioca/extensions`.
No automated tests (there are no existing tests for `load_dsl_compilers` either), but I did test the change manually:
1. create a file `sorbet/tapioca/extensions/test.rb` with the following contents:
```ruby
puts "Custom extension required"
```
2. edit `lib/tapioca/dsl/extensions/active_record.rb` and add the following at the top of the file:
```ruby
puts "Built-in extension required"
```
3. Run `bundle exec ruby exe/tapioca dsl` and check output:
```
Loading DSL extension …
```

Add support for loading custom DSL extensions

---

README.md

It's common to use `check-shims` in CI, so I believe Tapioca should also be in the `test` group.

Docs: Tapioca should also be in `test` group in Gemfile

---

README.md
lib/tapioca/cli.rb
lib/tapioca/commands/abstract_gem.rb
lib/tapioca/gemfile.rb
spec/tapioca/cli/gem_spec.rb

In my project we have huge Gemfile with a lot of gems. We tried to type some of the files, but we do not need all of the gems to be generated. We tried to use `tapioca gems [name_of_the_gem]` but it was generating only this gem (without dependencies). We tried `exclude` but list was huge.
I think we should have `--include-dependencies` flag that generate RBIs for dependencies as well
I added new flag for CLI that will pick gems and dependencies from the list.
I added integration tests

Add support for `--include-dependencies` flag

---

lib/tapioca/dsl/compilers/active_support_concern.rb
spec/tapioca/dsl/compilers/active_support_concern_spec.rb

When you inherit from class that extends `ActiveSupport::Concern` it will break DSL compiler `ActiveSupportConcern`.
This commit modifies the `dependencies_of` method in the ActiveSupport::Concern compiler to ensure it returns an empty array when the concern has no dependencies, preventing potential `nil` errors.
A new test ensures that constants inheriting from a class extending ActiveSupport::Concern are not gathered, ensuring only direct dependencies are included.
I added specs

Handle nil dependencies in case of inheritance

---

README.md
lib/tapioca/cli.rb
spec/tapioca/cli/help_spec.rb

I noticed that the casing of descriptions' initial letters are not unified, so I tried to capitalize them.
```shellsession
$ bundle exec tapioca --version
Tapioca v0.11.8
$ bundle exec tapioca -h
Commands:
tapioca --version, -v      # show version
tapioca annotations        # Pull gem RBI annotations from remote sources
tapioca check-shims        # check duplicated definitions in shim RBIs
tapioca configure          # initialize folder structure and type checking configuration
tapioca dsl [constant...]  # generate RBIs for dynamic methods
tapioca gem [gem...]       # generate RBIs from gems
tapioca help [COMMAND]     # Describe available commands or one specific command
tapioca init               # get project ready for type checking
tapioca require            # generate the list of files …
```

Capitalize descriptions shown in CLI help

---

spec/tapioca/runtime/generic_type_registry_spec.rb

I wrote these unit tests for myself while exploring #1634. They seem worth keeping around.

Add tests for `GenericTypeRegistry`

---

lib/tapioca/commands/annotations.rb
lib/tapioca/commands/dsl_generate.rb
lib/tapioca/commands/gem_generate.rb
lib/tapioca/commands/gem_sync.rb
lib/tapioca/helpers/git_attributes.rb
lib/tapioca/internal.rb
spec/tapioca/cli/annotations_spec.rb
spec/tapioca/cli/dsl_spec.rb
spec/tapioca/cli/gem_spec.rb

Fixes https://github.com/Shopify/ruby-dev-exp-issues/issues/651
The `linguist` gem added support for detecting generated and vendored RBI files in https://github.com/github-linguist/linguist/pull/6143, but it parses the RBI file header comments to understand that, which is quite brittle.
Tapioca can do a better job of this, since it already knows that `dsl` and `gem` commands will create "generated" RBI files in the output directory and the `annotations` command will create "vendored" RBI files. So, Tapioca should be generating the appropriate `.gitattributes` files in the relevant output directories to signal that the RBI files contained are generated/vendored.
1. Added a `GitAttributes` helper module that knows how to create `.gitattributes` files that state the `**/*.rbi` files in the …

Start generating `.gitattributes` file for generated and vendored RBI files

---

lib/tapioca/dsl/compilers/active_record_columns.rb
lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
lib/tapioca/helpers/test/template.rb
spec/tapioca/dsl/compilers/active_record_columns_spec.rb

Support Active Record composite primary keys in `ActiveRecordColumns` compiler.
I imagine using Rails edge may not be ideal, and if it isn't, we can look at merging this closer to when CPK is released. Due to how the compiler works, I would also consider renaming it to `ActiveRecordAttributes` instead.
The implementation inadvertently fixed a bug where the generated attribute methods don't include `id` when using a non-id primary key. Active Record always has an `id` method defined via https://github.com/rails/rails/blob/bc2892ab4557136a959e95c329c2dcc0133c7585/activerecord/lib/active_record/attribute_methods/primary_key.rb.

Support Composite Primary keys in ActiveRecordColumns compiler 

---

.github/dependabot.yml

As seen in https://github.com/Shopify/tapioca/pull/1688, Rails updates often need additional work, so let's exclude that from the grouped updates.

Exclude Rails from grouped updates

---

lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/compilers/graphql_mutation_spec.rb

When trying to update our project to Tapioca v0.11.9, I ran into an issue with our custom scalars: Tapioca currently uses the GraphQL scalar class as the return type even if it defines a `coerce_input` method with a different return type. For example, if I have a scalar `MyScalarType` that inherits from `GraphQL::Schema::Scalar` and has a `coerce_input` that returns `MyScalar`, Tapioca will wrongly use `MyScalarType` in generated signatures for mutations and input objects. This is an attempt at fixing that issue.
I also shoehorned `GraphQL::Types::BigInt` here since I noticed it wasn't working properly either. Happy to separate that into its own PR if needed.
The approach I took is to simply check if a type signature exists on `coerce_input` and use the return type if it does. If not, it …

Add support for custom GraphQL scalar coercion

---

lib/tapioca/dsl/compilers/active_record_relations.rb
manual/compiler_activerecordrelations.md
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

This PR adds support for [`#to_a`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-to_a) to the ActiveRecord relations compiler.
Sorbet can usually infer that `#to_a` returns the same type as `#to_ary`, but because Active Record explicitly aliases `#to_ary` to `#to_a` ([here](https://github.com/rails/rails/blob/v7.1.1/activerecord/lib/active_record/relation.rb#L261)), Sorbet thinks `#to_a` is a separate method with no signature and thus returns `T.untyped`.
Cf. [sorbet.run bug repro](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Module%0A%20include%20%20T%3A%3ASig%0Aend%0A%0Aclass%20ActiveRecord%3A%3AAssociationRelation%0A%20%20include%20Enumerable%0A%0A%20%20def%20each%28%26blk%29%3B%20end%0Aend%0A%0Aclass%20ActiveRecord%3A%3AAssociations%3A%3ACollectionPr …

Add support for `#to_a` in ActiveRecord relations compiler

---

lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/compilers/graphql_mutation_spec.rb

@eapache-opslevel kinda nerd sniped me on this one, I thought "how hard could it be?"
This just tackles the situation where there's a `prepare` method with a signature, there is a default `prepare` method: https://github.com/rmosolgo/graphql-ruby/blob/565b62f13d3cdd7d2cd880e82d189ab64278b1e8/lib/graphql/schema/input_object.rb#L47-L56
I am unsure if there's a way to define a signature if you use the `prepare: -> (input, context) {}` lambda style `prepare` definition though.
By default `prepare` will return the current object, so I kept that behaviour in this MR, if you define a `prepare` method, without a signature, we assumed you're returning the current object.
If you add a signature to the overriden prepare method, we'll use the return type
I'm not a big fan of my weird nesting in …

 Support for custom GraphQL input preparation (Phase one)

---

lib/tapioca/dsl/compilers/graphql_input_object.rb
lib/tapioca/dsl/compilers/graphql_mutation.rb
lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/compilers/graphql_mutation_spec.rb

Second part of https://github.com/Shopify/tapioca/issues/1717
This adds support for prepare method when defined as a method on the constant.
[It uses the same check as GraphQL-Ruby](https://github.com/rmosolgo/graphql-ruby/blob/109c26c5fa9118a9c69ed4c4823048c1ce1aea6d/lib/graphql/schema/argument.rb#L217-L226)
And I use the same fallback behaviour as I did in #1720, where it falls back to the base type if the signature is missing or void (technically this is a bad signature I guess? But I'm not sure what we should really be doing here)
I added `constant` as a param in `Tapioca::Dsl::Helpers::GraphqlTypeHelper#type_for` since that holds the actual method on it, and as such I had to update `GraphqlInputObject` to use it too.
Yes!

Add support for GraphQL Argument prepare methods when defined as a method on the constant

---

lib/tapioca/gem/listeners/sorbet_signatures.rb
lib/tapioca/helpers/sorbet_helper.rb

Context: https://github.com/Shopify/tapioca/pull/1732/files#r1428547394
Instead of maintaining a feature check, we can just use a conditional and reduce complexity.
Got rid of the feature check and switch to a conditional. Also, left a comment with the PR and version it gets introduced since we may want to remove part of the conditional in the future if we make our Sorbet requirement more strict.
Existing tests should continue to pass.

Remove identity comparison feature check in favour of a conditional

---

lib/tapioca/dsl/compiler.rb
lib/tapioca/dsl/pipeline.rb
spec/tapioca/cli/dsl_spec.rb

Fix #1728 
There were a few places where we have not been using `Set`s with `compare_by_identity` properly. This commit fixes those instances so that the test added in the previous commit passes.
Added a failing test that passes with the fix.

Make sure we use compare by identity `Set`s properly

---

lib/tapioca/dsl/compilers/action_text.rb
manual/compiler_actiontext.md
manual/compilers.md
spec/tapioca/dsl/compilers/action_text_spec.rb

Adds a compiler for Action Text.
I based most of this off the Active Storage compiler. Action Text is not very complex internally so the compiler was not too hard to write.
Added tests and confirmed they match our home-made RBIs.

Add Action Text compiler

---

lib/tapioca/dsl/compilers/graphql_input_object.rb
lib/tapioca/dsl/compilers/graphql_mutation.rb
lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/helpers/graphql_type_helper_spec.rb

Following https://github.com/Shopify/tapioca/pull/1622 the function `Tapioca::Dsl::Helpers::GraphqlTypeHelper#type_for` required an `GraphQL::Schema::Argument` (instead of a `GraphQL::Schema::Wrapper`) to be passed.
Though this did make perfectly sense, we actually used that method to explicitly compute types in our DSL process without this being necessarily "for a field". For example it could be for union types.
What I did was:
1. Rework the `type_for` method to be backward compatible with the pre https://github.com/Shopify/tapioca/pull/1622 code (e.g. keep accepting a sole `GraphQL::Schema::Wrapper` argument as a parameter)
2. Introduce an explicit `type_for_argument` which would be redirecting appropriately to keep https://github.com/Shopify/tapioca/pull/1622 feature
I added tests for …

Restore `type_for(type)` function

---

lib/tapioca/dsl/compilers/active_job.rb
spec/tapioca/dsl/compilers/active_job_spec.rb

If an `ActiveJob#perform` contains a `&block` argument, tapioca will generate a duplicate block argument.
```
class TestJob
class << self
sig do
params(
args: T.untyped,
_arg1: T.untyped,
block: T.untyped,
block: T.nilable(T.proc.params(job: TestJob).void)
).returns(T.any(TestJob, FalseClass))
end
def perform_later(*args, **_arg1, &block, &block); end
sig { params(args: T.untyped, _arg1: T.untyped).returns(T.untyped) }
def perform_now(*args, **_arg1); end
end
end
```
```
class TestJob
class << self
sig do
params(
args: T.untyped,
_arg1: T.untyped,
block: T.nilable(T.proc.params(job: TestJob).void)
).returns(T.any(TestJob, FalseClass))
end
def perform_later(*args, **_arg1, &block); end
sig { params(args: T.untyped, _arg1: T.untyped).returns(T.untyped) }
def perform_now(*args, **_arg1); end …
```

Remove duplicate block parameter in ActiveJob#perform_later

---

lib/tapioca/dsl/compilers/identity_cache.rb
spec/tapioca/dsl/compilers/identity_cache_spec.rb

Closes: https://github.com/Shopify/tapioca/issues/1754
While researching this, I noticed that there were some missing methods for the default `cache_index` case as well. So as @KaanOzkan suggested in the issue, removing the `length` check fixed both issues. 
I've added some new tests and fixed old ones to illustrate the cases we are now expecting.

Update IdentityCache compiler to generate correct multi methods

---

lib/tapioca/dsl/helpers/graphql_type_helper.rb
spec/tapioca/dsl/compilers/graphql_mutation_spec.rb
spec/tapioca/dsl/helpers/graphql_type_helper_spec.rb

Leftover from the refactor https://github.com/Shopify/tapioca/pull/1714/files#diff-8b787801eb4d5ed2047d8b5d37043650443fae0500ae270f8d7ededeb311f27cL68. It causes TypeError's when the argument isn't a symbol or a string.
Bring back the previous check, call `to_sym` to please Sorbet.
Added

Check if prepare argument is a symbol or string

---

Gemfile
Gemfile.lock

Was resolved in v2.8.1 of `mail`:
https://github.com/mikel/mail/commit/d9d8dcc6bae1774a033ad488cea6217db3a3ebf3

Remove `net-smtp` dependency

---

lib/tapioca/dsl/compilers/active_support_current_attributes.rb

This makes Tapioca less sensitive to changes in gem code.
In Core, classes that inherit from `CurrentAttributes` were having `block` params added to their attribute getter methods due to [this](https://github.com/rails/rails/commit/2cd4abcc876bdbe3adc2cbbfeee9712fc2bc0601) change. This was later [fixed](https://github.com/rails/rails/pull/50872) in Rails, but it exposed this fragility.
Thanks for @paracycle for the suggested refactoring.

Use `create_method_from_def` to simplify `CurrentAttributes` compiler

---

.github/workflows/require_label.yml

Fix #1434 
We couldn't use a reusable action in #1435, but I realized that we can put together a quick action based on a bash script and some `gh` wizardry.
No tests

Add PR label action

---

spec/tapioca/cli/gem_spec.rb

CI is currently failing because rack has had a patch release that changes the version on one of the tests.
I updated the gem version in the test.

Fix rack gem version in failing test

---

lib/tapioca/dsl/compilers/config.rb

Solve a problem experienced with a Shopify project.
Just checking for the existence of a `Config` constant does not necessarily guarantee that the `config` gem is loaded, since an application could define their own top-level `Config` constant.
It is better to check for the existence of `Config::VERSION` and `Config.const_name` as well, to be reasonably sure that the constant is coming from the gem.
All existing tests pass

Stronger checks for existence of `config` gem

---

Gemfile.lock
lib/tapioca/version.rb
tapioca.gemspec

Sorbet support for multiple RBI signatures on a same method was added at this version. We need this feature for new work such as https://github.com/Shopify/tapioca/pull/1799 and https://github.com/Shopify/tapioca/tree/uk-rbs-converter.
The v0.5.11087 is ~5 months old, it should be okay.

Bump `sorbet-static-and-runtime` requirement to v0.5.11087

---

lib/tapioca/dsl/compilers/active_record_relations.rb
lib/tapioca/rbi_ext/model.rb
manual/compiler_activerecordrelations.md
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Close #1789
Based on the patch in aforementioned issue.
Updated tests.

Add support for overloaded signatures and add overloaded ActiveRecordRelations sigs

---

lib/tapioca/dsl/compilers/active_record_relations.rb
lib/tapioca/dsl/helpers/active_record_constants_helper.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Currently the calculation methods like `sum` and `count` return `T.untyped`. For some methods we cannot know the type (e.g. `minimum`) but for others we at least know it's numeric (e.g. `sum`) and for `count` we know it's an Integer.
However, I'm assuming these are untyped because if they're used with `group` the return value is actually a hash where the keys cannot be typed but the values will be the types mentioned above. This PR updates the `ActiveRecordRelations` compiler to type these correctly.
I first updated the return values of the calculation methods where possible. Then I largely copied from the code around `PrivateRelationWhereChain` to add a `PrivateRelationGroupChain` module which defines the calculation methods with the hash return values.
Some callouts:
- Unlike …

More accurately type ActiveRecordRelations calculation methods

---

lib/tapioca/commands/abstract_gem.rb

I was encountering a `Parallel::DeadWorker` exception when running `tapioca gem` on a new project:
```
bundler: failed to load command: tapioca (/Users/andyw8/.gem/ruby/3.1.1/bin/tapioca)
/Users/andyw8/.gem/ruby/3.1.1/gems/parallel-1.24.0/lib/parallel.rb:83:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)
from /Users/andyw8/.gem/ruby/3.1.1/gems/parallel-1.24.0/lib/parallel.rb:80:in `work'
from /Users/andyw8/.gem/ruby/3.1.1/gems/parallel-1.24.0/lib/parallel.rb:522:in `block (4 levels) in work_in_processes'
from /Users/andyw8/.gem/ruby/3.1.1/gems/parallel-1.24.0/lib/parallel.rb:637:in `with_instrumentation'
from /Users/andyw8/.gem/ruby/3.1.1/gems/parallel-1.24.0/lib/parallel.rb:521:in `block (3 levels) in work_in_processes'
from …
```

Prevent `abort` call within gem from breaking `tapioca gem` command

---

lib/tapioca/dsl/compilers/protobuf.rb
spec/tapioca/dsl/compilers/protobuf_spec.rb

Optional fields may not be present in the serialized payload. The regular accessors will still return the default value for that field type (e.g. 0 or ""). Sometimes you want to know the difference between "default value" and "present in payload", and the `has_FIELD?` methods are there for that:
https://protobuf.dev/reference/ruby/ruby-generated/#checking-presence
The return type is pretty weird - it's `false` for when the field isn't present, and 0 for when it is.
```
irb(main):015> u = ShopApp::Protobuf::ServiceApi::V1::User.new
=> <ShopApp::Protobuf::ServiceApi::V1::User: id: 0, uuid: "", email_verified: false>
irb(main):016> u.email
=> ""
irb(main):017> u.has_email?
=> false
irb(main):018> u.email = "buffy@example.com"
=> "buffy@example.com"
irb(main):019> u.has_email?
=> 0 …
```

Include the 'has_FIELD?' methods in RBIs generated from protobuf

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

See https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-extract_associated - this returns an array and the return type unknown since it depends on the association passed in.
Override when iterating over QUERY_METHODS to return the right thing seemed like the right place to hook into since it collects methods from the aforementioned Active Record module.
Updated tests.

Fix return type of ActiveRecord::QueryMethods#extract_associated

---

.github/workflows/ci.yml
.rubocop.yml

This repo is well maintained and already follows the standards we set in place. https://github.com/Shopify/tapioca/commit/b164c0bfb759753c9d0c4da8ef8278308e1a1497 added the `.ruby-version` file, a `required_ruby_version` is already set in the `.gemspec`, a `Gemfile.lock` is already built, etc. This PR cleans up the last remaining mentions of Ruby version outside of the `.ruby-version` file (last two bullet points of the list below).
> [!IMPORTANT] 
> Please verify the following before merging:
Verify that the changes in the PR meets the following requirements or adjust manually to make it compliant:
Please merge this PR if it looks good, this PR will be merged if there isn't any activity after 4 weeks.

Complete the `.ruby-version` standardization

---

spec/spec_with_project.rb

When I was working on the ripper compiler, I found it difficult to have to update every single assertion that is assertion against stdout/stderr of tapioca. Because it's not assertion against a subset, any change to the logic will cause the entire test to fail and have to be updated.
These are more like snapshot tests than unit tests. Therefore I built a way to update all of the snapshots in one go. It's not meant to be comprehensive or even tested, but I found it very useful as opposed to trying to update every fixture myself, so I figured I would upstream it in case there was interest.
You trigger it by running the test suite with `TAPIOCA_ASSERTIONS_UPDATE=1`. You can see how it works by — for example — changing `"Loading DSL extension classes... "` to something else, running …

Automatic stdout/stderr assertion updates

---

lib/tapioca/dsl/compilers/active_record_relations.rb
lib/tapioca/rbi_ext/model.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

While upgrading our app since working on https://github.com/Shopify/tapioca/pull/1799 I came across code that looks like `Model.where(condition: true).find { |m| m.computed_attribute == "foo" }` and this doesn't fit the signatures generated. While replacing `find` with `detect` was an easy enough workaround, here's the proper fix.

Update Active Record find sig to allow a block

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

This PR fixes a bug introduced in https://github.com/Shopify/tapioca/commit/a225ce09a6edf8b557be6c52825c9e780e3ff281#r140951848 where the `ActiveRecord.find` RBI would be invalid Ruby because of an additional `)`.
I've just removed the additional `)`, but I do wonder if there should be a check to ensure the RBI file that's generated is valid Ruby introduced at some point.

Remove extra ) in the ActiveRecord.find output

---

.github/workflows/team_ruby_dx.yml

Reduce the noisiness of the Slack integration.
Removed `synchronize` events.

Do not notify Slack on synchronize

---

lib/tapioca/dsl/compilers/active_record_relations.rb
lib/tapioca/rbi_ext/model.rb
sorbet/rbi/gems/rbi@0.1.10.rbi
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Closes https://github.com/Shopify/tapioca/issues/1822. See discussion there for full context. 
TL;DR: The current sigs are incorrect when given a block.
I believe I updated the spec here correctly.

generate overloaded sigs for active record sum

---

lib/tapioca/dsl/compilers/active_record_fixtures.rb
manual/compiler_activerecordfixtures.md
sorbet/rbi/shims/active_record_fixture_set.rbi
spec/tapioca/dsl/compilers/active_record_fixtures_spec.rb

It has been bugging me some time that fixtures are T.untyped.
After a conversation today with @vinistock we realized that method overloading might work - and lo and behold - it does work.
The generated signatures return `Model` for `models(:one)` and `T::Array[Model]` for `models(:one, :two)` by overloading it with nil as the rest arg type, hat tip to @vinistock for the idea.
The signature of the fixture methods changed from `users(*fixture_names)` to `users(fixture_name, *other_fixutres)` in order to allow overloading based on the type of the rest args (e.g. `nil` or `T.any(String, Symbol`).
The mapping for fixture method (e.g. `users`) to model name (e.g. `User`) happens by creating a lookup table (once) for a mapping from underscore name to name. All descendants of `ActiveRecord::Base` …

Infer types for active record fixtures

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Use `T.any(Integer, Float, BigDecimal)` as the return type for ActiveRecord calculation methods.
Closes #1850.
See discussion in #1850.
Updated `ActiveRecordRelations` compiler to use `T.any(Integer, Float, BigDecimal)` instead of `Numeric` as the return type for `sum` methods.
Some notes/thoughts:
- Should other calculation methods be updated accordingly? E.g. `average`, `minimum`, `maximum`, `calculate`
- Yes ➡️  Done!
- `BigDecimal` is only available after `require "bigdecimal"` (and, in a future Ruby version, bigdecimal will switch from a default gem to a bundled gem). That's probably fine since bigdecimal is a dependency of activesupport, so presumably any Rails / ActiveRecord user already has the gem in their app.
Updated existing tests in …

Use `T.any(Integer, Float, BigDecimal)` as the return type for ActiveRecord calculation methods

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

We tried to use this in a way (passing a column name as argument) that [doesn't work](https://api.rubyonrails.org/v7.1.3.2/classes/ActiveRecord/QueryMethods.html#method-i-distinct), and were caught off guard that Sorbet didn't warn us about it. This fixes that :) 
Updated tests.

Improve ActiveRecord::QueryMethods#distinct

---

.github/workflows/ci.yml

Github uses commit status to set the status for the branch so we need this to run on pushes.

Trigger matrix status check for push and PR events

---

README.md
lib/tapioca/cli.rb
lib/tapioca/commands/abstract_dsl.rb
lib/tapioca/dsl/pipeline.rb
spec/tapioca/cli/dsl_spec.rb

There might be need for an escape hatch that will prevent tapioca from generation DSL RBIs for specific constants.
Remove specified constants from the list of processable constants coming from DSL compilers
Included

Introduce `skip_constants` flag to `dsl`

---

.github/workflows/ci.yml
tapioca.gemspec

Ruby 3.0 is EOL since 2024-04-23.
See https://www.ruby-lang.org/en/downloads/branches/.

Remove Ruby 3.0 from CI matrix

---

lib/tapioca/dsl/compilers/active_record_fixtures.rb
manual/compiler_activerecordfixtures.md
spec/tapioca/dsl/compilers/active_record_fixtures_spec.rb

Resolves https://github.com/Shopify/tapioca/issues/1893

ActiveRecordFixtures compiler should support passing no args

---

lib/tapioca/dsl/extensions/kredis.rb

The arguments for many attributes in `Tapioca::Dsl::Compilers::Extensions::Kredis` are missing the `default:` keyword argument defined in the kredis gem [here](https://github.com/rails/kredis/blob/main/lib/kredis/attributes.rb). This is causing the following error whenever you generate the DSLs for an application that uses the `default:` argument on a kredis attribute.
```
lib/tapioca/dsl/extensions/kredis.rb:27:in `kredis_integer`: unknown keyword: :default (ArgumentError)
```
Added the `default:` keyword argument to all of the following kredis attribute methods:
- `kredis_string`
- `kredis_integer`
- `kredis_decimal`
- `kredis_datetime`
- `kredis_flag`
- `kredis_float`
- `kredis_json`
- `kredis_list`
- `kredis_unique_list`
- `kredis_set`
- `kredis_counter`
- `kredis_hash`
- …

fix: add default keyword argument to kredis extension attributes

---

lib/tapioca/commands/abstract_dsl.rb

This feature is useful for cases where certain constants aren't available in all environments. We shouldn't error if that's the case

Ignore missing constants for `--skip-constant` option

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
spec/tapioca/dsl/compilers/active_record_columns_spec.rb

We have a custom type inheriting from `ActiveRecord::Encryption::EncryptedAttributeType` with a `deserialize` method that has a `sig` specifying the return type. 
Previously the column type would hit the `ActiveRecord::Type::String` branch of `type_for_activerecord_value` and return `::String` because `ActiveRecord::Encryption::EncryptedAttributeType` inherits from `ActiveRecord::Type::String`.
I added a case statement for `ActiveRecord::Encryption::EncryptedAttributeType` to `type_for_activerecord_value`.
I have.

Handle ActiveRecord attributes inheriting from `EncryptedAttributeType` with custom `sigs`

---

lib/tapioca/helpers/rbi_files_helper.rb
spec/tapioca/cli/check_shims_spec.rb

Sometimes we want to use shims to define the parent class that Tapioca may have missed. (Example [1](https://github.com/Shopify/shop-server/pull/77554/files#r1588551662), [2](https://github.com/Shopify/shopify/pull/509499/files#diff-e252f62eeb853d302e699ae346524b6bc2f94ed73d1e9677d639e9f014328265R81-R84))
Consider this file generated by Tapioca for a gem:
```rb
class Foo
end
```
The user knows that `Foo` actually inherits from `Baz` and wants to fix this in a shim:
```rb
class Foo < Bar
end
```
Tapioca `check-shims` command will report a useless duplicated shims, yet this redefinition should be allowed:
```
Duplicated RBI for ::Foo:
* sorbet/rbi/shims/foo.rbi:1:0-2:3
* sorbet/rbi/gems/foo@1.0.0.rbi:1:0-2:3
```
Before reporting a shim class as a duplicate, we should check if it redefines …

Do not report duplicate for shim or annotations classes redefining the superclass

---

.github/workflows/ci.yml

Resolves strange CI failures on main https://github.com/Shopify/tapioca/actions/runs/9519041069
2.5.11 is the previous version. I updated RubyGems version too thinking maybe they need to be compatible since they are released from the same repo.

Downgrade bundler in CI

---

lib/tapioca/dsl/compilers/active_record_typed_store.rb
spec/tapioca/dsl/compilers/active_record_typed_store_spec.rb

Closes #1910
Decide to refactor the `#type_for` method to take the whole `ActiveRecord::TypedStore::Field` object, instead of just its `type_sym`, because I would have needed to also pass in `field.array`. This way it can just access what it needs.
This has the nice benefit of moving the `if field.null` responsibility out of the `decorate` method.
I added tests for both `array: true, null: true` and `array: true, null: false`. I didn't assert the type of _all_ the methods (since they're mostly the same), just the getter/setter (just like how other tests check them).

Support array types in `typed_store` compiler

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb

Closes https://github.com/Shopify/tapioca/issues/1913

Check for constant definition before invoking

---

README.md
lib/tapioca/cli.rb
lib/tapioca/dsl/compilers/active_record_columns.rb
lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
lib/tapioca/dsl/pipeline.rb
lib/tapioca/helpers/config_helper.rb
manual/compiler_activerecordcolumns.md
spec/tapioca/cli/dsl_spec.rb
spec/tapioca/dsl/compilers/active_record_columns_spec.rb

I've been thinking about this for a while, and I think namespacing compiler options was a little heavy handed. I've been thinking about cases where a single option might need to be consumed by multiple Active Record compilers, so I think it makes more sense to have a flat hash of options that can be consumed by any compiler.
This makes the code simpler and makes it easier to pass these options on the command line interface, as well.
I've also used this opportunity to improve the documentation, as promised

Refactor DSL compiler options to be a flat namespaced hash and document them

---

lib/tapioca/dsl/compilers/active_support_concern.rb
spec/tapioca/dsl/compilers/active_support_concern_spec.rb

`ActiveSupportConcern` uses [`const_defined?`](https://apidock.com/ruby/Module/const_defined%3f) to check if `ClassMethods` exists on a module. By default, `const_defined?` checks the module and its ancestors for the existence of the constant. This means that `const_defined?` will return `true` when a module does not have `ClassMethods` defined, but one of its ancestors does. This can result in `ActiveSupportConcern` generating `mixes_in_class_methods.*ClassMethods` lines for invalid `.*ClassMethods` modules.
`const_defined?` takes a second parameter that controls whether to include ancestors in the check. Setting this parameter to `false` to exclude ancestors.
The first commit in this PR adds a negative test case that should fail with the existing code and pass with the fix from the …

fix: `ActiveSupportConcern` recursively checks for `ClassMethod`

---

lib/tapioca/commands/annotations.rb
lib/tapioca/gem_info.rb
lib/tapioca/internal.rb
spec/tapioca/cli/annotations_spec.rb
spec/tapioca/commands/annotations_spec.rb

This PR aims to solve the problem of versioning RBIs. Up until now, there is no default way to write RBI for different versions of the same gem. This can lead to confusing issues for Sorbet users where RBIs don't match the version of a gem they're using, and they have to spend time figuring out whether their gem is out of date, whether the RBI is wrong, or if it's even both! Having a way to specify RBI for multiple versions of the same gem would allow people to adopt and use Sorbet without having to go through this hassle.
The actual RBI filtering behavior is implemented in [the RBI repo](https://github.com/Shopify/rbi/pull/180). This uses the `FilterVersions` rewriter during the annotations command to remove parts of the annotation RBI that aren't relevant to a certain gem version.
I …

Filter gem RBIs by version during `annotations` command

---

lib/tapioca/dsl/compilers/active_record_relations.rb

Rails head has been updated to include `#all` under `ActiveRecord::QueryMethods` ([source](https://github.com/rails/rails/commit/fd5bd98b34774ec8ccb0fc649d5325b9ac9a875e#diff-79b53b2602bf702bdd8ce677e096be6a6923a54236e17237c16068a510078683R258-R261)).
I had tried to update the `QUERY_METHODS` constant to remove the intersection with `ActiveRecord::AssociationRelation.instance_methods` as that is where all is originally coming from, but this was over zealous causing a bunch of errors.
The option I've gone with is to update the ones removed as "private api" since they overlap with what is [done in Rails](https://github.com/rails/rails/commit/fd5bd98b34774ec8ccb0fc649d5325b9ac9a875e#diff-2d6b8d6b15542ae5c458ef5663a0e5f1a0178ec66455571839256d8b75d4939dR65): …

Fix ActiveRecordRelations compiler to dedup #all

---

lib/tapioca/dsl/compilers/aasm.rb
spec/tapioca/dsl/compilers/aasm_spec.rb

AASM global callbacks takes splat argument as first argument instead of a nilable symbol: https://github.com/aasm/aasm/blob/0e03746a2b86558ee1bf7bd7db873938cbb3b29b/lib/aasm/base.rb#L145-L171
Change AASM compiler to use correct params definition.
Added accordingly.

Fix AASM compiler's global callback method signatures

---

lib/tapioca/loaders/loader.rb
spec/tapioca/cli/dsl_spec.rb

There are sometimes Rails-lookalike applications that might have defined a `config/application.rb` file but don't actually have Rails loaded.
This change short circuits the Rails app loading if the `Rails` constant isn't defined after loading the `config/environment.rb` file or the `config/application.rb` file.
Added a new test that exercises the new code path.

Short circuit Rails app loading if Rails constant isn't defined

---

lib/tapioca/dsl/compilers/url_helpers.rb

Profiling `tapioca DSL SomeConst` identified this method as a hot spot, taking roughly 1 out of the 6 total second spent by Tapioca (not including application load time).
The changes in this PR speed up running `tapioca dsl` against Shopify core by **1 entire second!**
| run   | gather_constants | User time | Syscall time | Total |
|-------|------------------|-----------|--------------|-------|
| Master          | 2s 350ms | 37s 383ms | 6s 760ms | 33s 10ms  |
| [Original improvements](https://github.com/Shopify/tapioca/commit/2344fdf731b73ad01fd6be71317e57e46518790e)        | 1s 333ms | 36s 383ms | 6s 970ms | 32s 216ms |
| [Ufuk suggestion](https://github.com/Shopify/tapioca/pull/1935/commits/70d7fb5491fe655715da1e7f52dbd8ac1085418e) | 1s 473ms | 36s 593ms | 6s 750ms | 32s 313ms |
| …

Optimize `URLHelpers.gather_constants`

---

lib/tapioca/helpers/test/dsl_compiler.rb

Currently Tapioca exports a DSL compiler test helper that is used by other app or gems to test their DSL compilers. However, the helper requires a lot of Tapioca DSL classes to be defined before it can be used. This is a problem because it means that the helper can't be used in isolation, without the rest of Tapioca. A common workaround for this is to start requiring "tapioca/internal" in the test file that uses the helper, but that ends up causing Sorbet runtime related behaviour changes due to the Sorbet runtime patches that that require pulls in.
In order to fix this, all we need to do is to require "tapioca/dsl" which brings in only the DSL classes that the helper needs. This way, the helper can be used in isolation without needing to require "tapioca/internal" and without causing any …

Make DSL compiler test helper work without needing an extra require

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

During `ActiveRecordRelation` compiler's decorate it generates the wrong method signature of the `#find` method for records with composite keys. The signature for the method appears to have been updated when multiple values are passed (i.e. array of arrays), but the singular value still shows as `T.any(....)` when it should be wrapped in an array.
I've updated the handling so if `#composite_primary_key?` is present and returns a truthy value then the value of ids will be updated to be an array of instead. This then works forward so that the value for an array of composite keys is correct too.
Updated tests to reflect changes.

Fix ActiveRecordRelation compiler's handling of composite primary keys

---

lib/tapioca/dsl/compilers/state_machines.rb
spec/tapioca/dsl/compilers/state_machines_spec.rb

When using the state machine gem it is encouraged to use either `String` or `Symbol` for state types, but this isn't strictly enforced. 
```ruby
class Vehicle
ACTIVE = 1
OFF = 0
state_machine :alarm_state, initial: ACTIVE do
before_transition any => ACTIVE do |unit|
unit.some_cool_method_at = Time.now.utc
end
event :enable do
transition all => ACTIVE
end
event :disable do
transition all => OFF
end
state ACTIVE
state OFF
end
end
```
If someone were to use a different type like in this example, the type generated for `alarm_state=` would still be `T.any(String, Symbol)` despite actually wanting `Integer`. There are a few other methods that suffer this as well.
This stems from using `State#value` to determine the states to use. This value is set as a `to_s` version of the name unless …

Fix the types for state-machine states

---

lib/tapioca/dsl/compilers/active_support_time_ext.rb
manual/compiler_activesupporttimeext.md
manual/compilers.md
spec/tapioca/dsl/compilers/active_support_time_ext_spec.rb

This compiler generates an RBI file for Active Support's Time extensions. Currently this is limited to the return type of the `Time.current` method which changes its return type depending on if `Time.zone` is set or not.
https://github.com/Shopify/rbi-central/pull/262#issuecomment-2230885870
Add a new compiler that only handles `Time` constant and is only loaded if `Time.current` method is defined.
Added tests for the new compiler.

Add `ActiveSupportTimeExt` compiler

---

lib/tapioca/dsl/compilers/active_model_validations_confirmation.rb
lib/tapioca/dsl/compilers/active_support_concern.rb
lib/tapioca/dsl/compilers/graphql_input_object.rb
lib/tapioca/dsl/compilers/graphql_mutation.rb
lib/tapioca/dsl/compilers/identity_cache.rb
lib/tapioca/dsl/compilers/json_api_client_resource.rb
lib/tapioca/dsl/compilers/sidekiq_worker.rb
lib/tapioca/dsl/compilers/smart_properties.rb
lib/tapioca/dsl/compilers/state_machines.rb

In my work on #1935, I discovered that `<` wasn't behaving as expected for some modules, which needs special handling like in #677
e.g.
```ruby
require "xpath"
class DefinitelyNotXPath; end
if XPath < DefinitelyNotXPath
puts "This shouldn't be called, but it is"
end
XPath < DefinitelyNotXPath
```
Just flip the operators around, so the receiver is always the known-good classes which don't override the `Module#>`.
I haven't detected any concrete problems caused by this (other than the one already solved in #1935, so I haven't added any test cases.
It would really be nice to have an automated way of detecting and preventing such cases, but. I can't think of a way to do so without too many false positives. E.g. blanket banning `<` with a RuboCop rule would be too aggressive.

Flip subtype checks (`<` → `>`)

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

When a model's builder methods are called with no arguments it will default to the first signature that is now `T::Array` param and return. This is obviously incorrect as it will only be instantiating one object. 
I've added a new sig for these methods that omits the `attributes` param, handling this first.
As `#create!` is a part of the builders this will also create the sig for that method. I'm _sure_ there is a way to have a valid call to `#create!` with no params, but even if not I think that it's fine to keep generating this sig for the method.
Updated existing tests to reflect changes.

Add a sig with no args for ActiveRecordRelations builder methods

---

lib/tapioca/commands/abstract_gem.rb
lib/tapioca/gem/listeners/methods.rb
lib/tapioca/gem/pipeline.rb
lib/tapioca/loaders/loader.rb
lib/tapioca/runtime/reflection.rb
lib/tapioca/static/symbol_loader.rb
spec/tapioca/gem/pipeline_spec.rb
spec/tapioca/runtime/reflection_spec.rb

When a sorbet signature block ends up throwing an exception, it gets swallowed up by the `signature_for(method)` in the `Tapioca::Runtime::Reflection` utilities, and an incorrect signature is generated. This has created some confusion for my team when the sorbet type checking failed, even though it appeared as if the signature was implemented correctly.
**Example**
_Sorbet Interface in upstream gem_
NOTE: the dependency/require statements on the `ExampleContracts::WidgetDto` had a simple bug that led to it being defined in most scenarios, but was not happing in the tapioca run downstream from these packages.
```ruby
module Example::WidgetAdapter
extend T::Sig
extend T::Helpers
interface!
sig do 
abstract
.params(widget: ExampleContracts::WidgetDto)
.returns(T::Boolean)
end
def …
```

Log Sorbet signature block errors that lead to misleading RBI signatures generated

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

As pointed out in this issue: https://github.com/Shopify/tapioca/issues/1981
The typing for `Model.new` accepts an `T::Array` which it never actually does. The original discussion was around this being acceptable, but after trying to fix issues from this change to the compiler I'm now thinking that it is better to type this appropriately.
Consider:
```ruby
def some_untyped_method
{
a: 1,
b: 1,
c: 1,
}
end
SomeModel.new(some_untyped_method)
```
Because of how Sorbet selects the signature in the case of `T.untyped` and overloaded signatures, it will tend to pick the first viable, which in the case of `#new` will be `T::Array`. This then implicitly means that any arguments to `SomeModel.new` will have to be typed otherwise it picks a type that is never possible for this method.
I'm aware …

Fix ActiveRecordRelations Model.new typing

---

lib/tapioca/dsl/compiler.rb
lib/tapioca/dsl/pipeline.rb

Speedup gather_constants performance when a constant is supplied by not iterating over the ObjectSpace. This PR shouldn't change the functionality because we intersect the constants received from the ObjectSpace iteration with the requested ones https://github.com/Shopify/tapioca/blob/df6e272f4b4dcab5d1a21b2f9aabab1741743603/lib/tapioca/dsl/pipeline.rb#L156
Running `tapioca dsl Constant` before and after in the monolith:
Most of the tests in the dsl_spec supply arguments to `tapioca dsl` command.

Iterate over requested_constants in DSL helpers

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
spec/tapioca/dsl/compilers/active_record_columns_spec.rb

Types were being computed incorrectly. In the spec I added previously it was computed as `sig { returns([::String, ::String]) }`
Fixed the implementation.
I've added tests.

Fix types for composite primary keys

---

Gemfile.lock
sorbet/rbi/gems/yard@0.9.37.rbi
spec/helpers/mock_project.rb
spec/tapioca/cli/check_shims_spec.rb
spec/tapioca/cli/config_spec.rb
spec/tapioca/cli/configure_spec.rb
spec/tapioca/cli/dsl_spec.rb
spec/tapioca/cli/gem_spec.rb
spec/tapioca/cli/help_spec.rb
spec/tapioca/cli/require_spec.rb
spec/tapioca/cli/todo_spec.rb
spec/tapioca/cli/version_spec.rb

Some changes to Ruby 3.3.5 have broken Tapioca CI. This PR fixes these issues to make our CI green again. See commit messages for more information.
See included automated tests.

Fix CI on Ruby 3.3.5

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb

ActiveRecordColumnTypeHelper's `@constant.primary_key` can be `nil` for models that don't have a primary key.
Closes #1997
This is a change to the type annotation, so not test is necessary.

Correct type annotation in `ActiveRecordColumnTypeHelper's`

---

lib/tapioca/dsl/helpers/active_record_column_type_helper.rb
sorbet/rbi/shims/activerecord_postgresql.rbi

Adds support for this column type.
I followed the other implementations of the postgres column types.
No tests since there's not an established way of doing that in the repo for this type of feature.

Support Postgres Interval, Range, Bit, and BitVarying

---

lib/tapioca/helpers/source_uri.rb

Avoid a deprecation warning on ruby 3.4 with the uri gem.
> /home/user/code/tapioca/lib/tapioca/helpers/source_uri.rb:50: warning: URI::RFC3986_PARSER.escape is obsoleted. Use URI::RFC2396_PARSER.escape explicitly.
`uri` for Ruby 3.4 switched the default parser from RFC2396 to RFC3986. The new parser emits a deprecation
warning on a few methods and delegates them to RFC2396, namely `extract`/`make_regexp`/`escape`/`unescape`.
On earlier versions of the uri gem, the RFC2396_PARSER constant doesn't exist, so it needs some special
handling to select a parser that doesn't emit deprecations. While it was backported to Ruby 3.1, users may
have the uri gem in their own bundle and thus not use a compatible version.
Additional info:
* https://github.com/ruby/uri/pull/107
* …

Avoid a deprecation warning on Ruby 3.4 with the uri gem

---

.github/workflows/ci.yml
spec/tapioca/cli/gem_spec.rb

We have a test that was pointing to rails#main; however, main / Rails 8 has dropped support for Ruby 3.1 so the test started failing. The test does seem valuable so we're pointing to rails#7-2-stable instead.
~This won't solve _everything_ though: the CI matrix combination of ruby 3.1 + rails main will be broken.~
~Another option here could be to remove 3.1 from CI; this might be OK given we no longer support that version at Shopify.~
https://github.com/Shopify/tapioca/pull/2029#issuecomment-2389487729

Fix broken CI on Ruby 3.1

---

lib/ruby_lsp/tapioca/addon.rb

While troubleshooting, it was difficult to determine if the Tapioca add-on was activated or not. Displaying this information will aid with debugging.
Followed the Ruby LSP Rails implementation by adding a notification to the `outgoing_queue`.
Manually tested the change to ensure the notification displays correctly.
<details><summary>Toggle Image</summary>
</details>

Log Tapioca Add-on Activation

---

spec/tapioca/cli/gem_spec.rb

Fixes a CI failure https://github.com/Shopify/tapioca/actions/runs/11338670378/job/31571952145?pr=2043#step:6:71

Bump expected rack version in tests

---

lib/tapioca/dsl/compilers/aasm.rb
spec/tapioca/dsl/compilers/aasm_spec.rb

1. Transition methods (after, guard, on_transition, success) were not found and would result in a failed type check if used.
2. Events can support arguments when being fired, and those arguments are passed to the PrivateAASMEvent method blocks. If we don't have any params arguments for the block, the default behavior of that block argument is not T.untyped, but rather NilClass, which will cause a type error if we try to reference those arguments. So as a result we need to change the proc signature to show one argument of T.untyped rather than no arguments. 
Added transition callbacks similar to how the events are added. PrivateAASMTransition class is used as the allowed methods are distinct from the allowed methods in the parent PrivateAASMEvent context.
Yes

Fixes for AASM compiler

---

spec/spec_with_project.rb
spec/tapioca/cli/gem_spec.rb

Came up in https://github.com/Shopify/tapioca/pull/2046
Use the built in pattern support for `Dir[]`

Assert project file existence using patterns

---

lib/ruby_lsp/tapioca/addon.rb

Currently, each file save triggers DSL generation, even when there are no code changes. This leads to unnecessary processing. This PR addresses the issue by optimizing the save handling process.
Implemented a checksum-based approach using `Zlib.crc32`. By calculating and storing file checksums, we can skip DSL generation for unchanged files, reducing redundant processing.

[Tapioca Add-on] Optimize File Save Handling

---

Gemfile
Gemfile.lock
sorbet/rbi/gems/sqlite3@2.2.0.rbi
spec/tapioca/cli/dsl_spec.rb
spec/tapioca/cli/gem_spec.rb

Various CI fixes

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

`ActiveRecord::QueryMethods#where` returns a `ActiveRecord::QueryMethods::WhereChain` instance only when it is called with no arguments. When called with arguments, it returns the same `ActiveRecord::Relation` instance.
Previously, we didn't have proper overloading support in RBI files, so the best thing we could do was act like `ActiveRecord::QueryMethods::WhereChain` was a subclass of the related relation class. This was not ideal because it would allow users to call methods on `WhereChain` that were not actually defined on it. For example, one could do `User.all.where(name: "John").not` which is not valid.
Now that we have support for overloading, we can define `where` to return a `WhereChain` instance only when called with no arguments, and in all other cases, we can say that it …

Use method overloading to improve WhereChain definition

---

lib/tapioca/dsl/compiler.rb

Based on the existence of the `@@requested_contants` code path, it seems safe for this method to return an `Array` in some cases, so simply caching the array of all `Modules` rather than the enumerator should be safe. Also, I have included the recommended optimization to derive `all_classes` from `all_modules`, which both simplifies things (no need for the `@@requested_constants` code path in both methods), as well as improves performance by skipping a full ObjectSpace traversal again.
Closes #1974
This is simply an optimization to an existing tested behavior.

Call `to_a` on cached `ObjectSpace` enumerator

---

lib/tapioca/helpers/git_attributes.rb

When studying the memory bloat for the Tapioca add-on, `ObjectSpace.dump_all` consistently reports the `File.write` line for writing the git attributes file as the place in the code retaining the most memory.
I did a few tests and it's something to do with the content. If I get rid of the content variable and just use an empty string, then this line no longer appears in the dump as the top retained memory.
I cannot explain why this is the case given that the heredocs used for the content are frozen strings. I honestly have no idea what's happening here. But avoiding writing the file if it's already there removes this line from the top offenders and no longer retains memory.
Started checking if the file exists before writing it.

Avoid writing gitattributes file unless necessary

---

exe/tapioca

Addresses the finding in https://github.com/Shopify/tapioca/issues/1934#event-15304946498
Print a warning as early as possible. Looking at various env variables `BUNDLER_VERSION` felt like a safe bet.
Tested manually. I can add it if wanted.

Warn when Tapioca is executed without Bundler

---

lib/ruby_lsp/tapioca/addon.rb

The Tapioca add-on was requiring the entire `ruby-lsp-rails` gem, which in turns requires `rails`. As @st0012 identified, this caused a change to the behaviour of `.to_json` which resulted in the Dependencies view not being displayed correctly.
Closes https://github.com/Shopify/team-ruby-dx/issues/1317
cc @KaanOzkan

[Tapioca Add-on] Limit what we require from the Rails add-on

---

README.md
lib/tapioca/cli.rb

I want `tapioca dsl` to infer the appropriate number of workers automatically.
I noticed the CLI is setting `default: 2` for the DSL command, but the other commands don't provide a default. The inference defined [here](https://github.com/Shopify/tapioca/blob/5434fa6a65d5111b2a7e0adf581a9a43ab6e1da9/lib/tapioca/executor.rb#L18) never runs.
I'm assuming this is a mistake, but there could be a good reason for this hardcoded default that I'm not aware of.
It would be difficult to write a test for this functionality because we'd need to assert on the assumed number of workers in a test for the CLI. The worker count determination happens deep in the stack.

Infer the worker count for `tapioca dsl`

---

Gemfile.lock
sorbet/rbi/gems/minitest@5.25.2.rbi

In combination with https://github.com/Shopify/ruby-lsp/pull/2706, this will allow Ruby LSP's test runner code lenses to work with minitest/spec.
Thanks goes to @thomasmarshall, who also fixed https://github.com/minitest/minitest/pull/1017 in minitest.

Update Minitest for improved test running experience

---

lib/ruby_lsp/tapioca/addon.rb
lib/ruby_lsp/tapioca/server_addon.rb
lib/tapioca/commands/abstract_dsl.rb
lib/tapioca/dsl/compiler.rb
sorbet/rbi/shims/uri.rbi

Extracting from https://github.com/Shopify/tapioca/compare/main...tapioca-addon-feature-branch.
Will be added later.

[Tapioca Add-on] Generate DSL RBIs in add-on mode

---

lib/tapioca/cli.rb

We were not actually passing down the option for the LSP add-on, which means it was always false everywhere.
Started passing it down.

Pass LSP add-on option to DSL

---

lib/tapioca/commands/abstract_dsl.rb

We weren't passing this to the loader, which makes it reload the Rails app multiple times.

Pass lsp addon option to DSL loader

---

lib/tapioca/commands/abstract_gem.rb
lib/tapioca/gemfile.rb
spec/spec_with_project.rb
spec/tapioca/cli/gem_spec.rb

Given this gemfile:
```ruby
source 'https://rubygems.org'
gem 'rspec'
```
The following configuration should not generate any RBI files, but it does.
```yaml
gem:
exclude:
- rspec
```
This would generate RBI files for all of RSpec's transitive dependencies (e.g. `rspec-core`, `rspec-support`, `rspec-mocks`, `rspec-expectations`, `diff-lcs`).
I just dropped all of the excluded gems from `definition.locked_gems.dependencies`.
I'm not sure if this is actually the right solution, because there's something going on with `BundlerExt::AutoRequireHook.override_require_false(exclude: @excluded_gems)` that I don't fully understand.
I updated the existing CLI test for the `--exclude` option. I've also test this against a real project, and it seems to work.

`--exclude` should also exclude transitive dependencies

---

lib/tapioca/loaders/dsl.rb

Reverts Shopify/tapioca#2069, makes it explicit in the comment

Revert "Don't attempt to load built-in compilers multiple times"

---

lib/tapioca/dsl/helpers/active_model_type_helper.rb
spec/tapioca/dsl/compilers/active_model_attributes_spec.rb
spec/tapioca/dsl/helpers/active_model_type_helper_spec.rb

We use `ActiveModel::Attributes` extensively. In many cases, we're passing complex values to these models, such as a `User`. It wouldn't be practical in our situation to define an `ActiveModel::Type` class for each and every possible value that gets passed into a model.
Any of the following solutions would solve my issue:
1. Explicitly tell Tapioca the type of a given attribute.
2. Explicitly tell Tapioca to skip type generation for a given attribute, which would allow me to write my own compiler for these specific attributes.
3. Allow compilers to override the types defined by other compilers (similar to #1965).
This PR allows instances of `ActiveModel::Type::Value` to define an optional method `#__tapioca_type`. It returns a type.
For example, you could use this hook to implement an …

Provide a hook for custom `ActiveModel` types

---

lib/tapioca/dsl/compilers/json_api_client_resource.rb
spec/tapioca/dsl/compilers/json_api_client_resource_spec.rb

Rename the `#sorbet_type` method called by the `JsonApiClient::Resource` compiler, to match our naming decision in #2112:
1. Prefixed with `__` to discourage the method from being called from regular user code (i.e. only Tapioca should be calling it).
2. Renamed to emphasize Tapioca over Sorbet, to clarify how this ends up being used. Should hopefully be an easier term to search for, with fewer false matches.
Print a warning when we find `#sorbet_type`, while still honouring it. If there's only a definition for `#__tapioca_type`, we'll use that instead.
After some migration time, we can drop support for `#sorbet_type`.

Rename `#sorbet_type` → `#__tapioca_type`

---

lib/tapioca/cli.rb
lib/tapioca/commands/abstract_gem.rb
lib/tapioca/commands/gem_generate.rb
spec/tapioca/cli/gem_spec.rb

Currently, when a gem specified in the `tapioca gem` command isn't found by bundler, the process fails with a `Thor::Error`. This creates a poor user experience on the rare instances when the Tapioca LSP Addon runs the command with multiple gems where some might not be available.
With this change, when the `--lsp_addon` flag is used, the command will now output a warning when a gem isn't found and continue processing other gems instead of crashing the process. This allows the Tapioca LSP Addon to handle missing gems gracefully while still generating RBIs for the available ones.
Without `--lsp_addon`, the command maintains its existing behaviour of failing with an error when a gem cannot be found.

[Tapioca Addon] Handle missing gems gracefully in tapioca gem command

---

spec/tapioca/cli/annotations_spec.rb
spec/tapioca/cli/check_shims_spec.rb
spec/tapioca/cli/gem_spec.rb

CI is currently failing https://github.com/Shopify/tapioca/actions/runs/12560449920/job/35017790286?pr=2135#step:6:1152. I assume it's due to the new prism minor version release.

Update test expectations for parse errors

---

.github/workflows/ci.yml
Gemfile.lock
lib/tapioca/gemfile.rb
spec/tapioca/gem/pipeline_spec.rb

Bundler 2.6 has just been released and unfortunately I noticed that it does not play well with tapioca.
The main incompatibility I noticed was introduced at https://github.com/rubygems/rubygems/pull/8251.
In that PR, missing specs were moved from the spec set of materialized specifications to the spec set holding the original resolution.
Unfortunately, that's necessary to fix the issue I wanted to solve, and I'm not sure how to fix the original issue while making the change backwards compatible with what tapioca was doing here. So I'm trying to change tapioca instead to play nice with Bundler 2.6.
I also found another test only incompatibility introduced by https://github.com/rubygems/rubygems/pull/8165 in Bundler 2.5.23. That's because `Gem::Specification.stubs` would hold a …

Support Bundler 2.6

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

This change matches the block return value to that of the [sig](https://github.com/sorbet/sorbet/blob/104d0cee5299e5cb19c731945f5a52634b78951b/rbi/core/array.rbi#L2304) on `Array#select`.
In practice, updating our large Rails app surfaced many violations of this sig that would cause (in my opinion) undesirable code changes in order to satisfy the `T::Boolean` return type. It does seem quite historically idiomatic for Ruby code to rely on the implicit truthiness/falsiness check, rather than coerce it explicitly.
Continuing the original [implementation](https://github.com/Shopify/tapioca/pull/2103), this is just a change to the return type of the block sig.
Existing tests are updated to reflect this change and seem to have sufficient coverage.

ActiveRecord `select` block returns `BasicObject`

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Follow up to the comment https://github.com/Shopify/tapioca/pull/2044#discussion_r1828255379 on #2044.
Handle the `size` method separately and make it not take any parameters and return an `Integer`.
Updated tests

Fix signature of `GroupChain#size` method

---

Gemfile.lock
sorbet/rbi/gems/ruby-lsp-rails@0.3.31.rbi

Upgrade to the latest Rails add-on so that we can get the fixture watching registration. 
There's no need to bump our minimum requirement though. If watching fixtures is not registered, we will simply not receive any notifications for it.
`bundle update ruby-lsp-rails && bin/tapioca gem`

Upgrade Rails add-on to v0.3.31

---

lib/tapioca/gem/listeners/source_location.rb
lib/tapioca/helpers/source_uri.rb

The implementation of `URI::Source` is shared between Tapioca and the Ruby LSP, but using the exact same name leads to weird conflicts and unnecessary warnings.
I propose we rename the class to `Tapioca::SourceURI`, just to avoid the conflict.
Rename the class and occurrences.
There are no functional changes. Current tests should cover it.

Avoid naming conflict for `URI::Source`

---

lib/ruby_lsp/tapioca/addon.rb
lib/ruby_lsp/tapioca/server_addon.rb
spec/tapioca/addon_spec.rb

Start generating URL helper DSLs upon route modifications. This is one of the compiler cases where there's not a constant, but rather a file pattern that triggers generation.
1. Started noticing modifications to any `routes.rb` file and then triggering a delegate notification
2. The server add-on side will collect relevant constants and then pass those to the DSL method. Note that the constants collected by the compiler are a mix of application constants and artificial ones created by Tapioca itself for the URL helper modules
Added tests and made some adjustments to make them more deterministic and avoid sleeping.
EDIT: couldn't avoid sleeping for some reason. Tests could use some future improvement.

Run URL helpers compiler when routes are modified

---

Gemfile
Gemfile.lock
lib/ruby_lsp/tapioca/addon.rb
lib/ruby_lsp/tapioca/server_addon.rb
spec/dummy/app/models/user.rb
spec/dummy/config/application.rb
spec/dummy/config/database.yml
spec/tapioca/addon_spec.rb

Addresses https://github.com/Shopify/team-ruby-dx/issues/1305
TODO:
Note: This doesn't work on Core because the fixtures is compiler is disabled and Core uses a custom compiler.

[Tapioca Add-on] Trigger `ActiveSupport::TestCase` DSL compiler on fixture changes

---

.github/workflows/ci.yml

Duplicate CI runs waste resources
Push events will only be triggered on `main`. As a result pushes to your branches without a PR will not trigger a build.

Prevent CI from running on both `push` and `pull_request` events

---

lib/ruby_lsp/tapioca/addon.rb
lib/ruby_lsp/tapioca/run_gem_rbi_check.rb
spec/tapioca/ruby_lsp/run_gem_rbi_check_spec.rb

After https://github.com/Shopify/tapioca/pull/2081, we began so to see an `Error loading add-ons: RuboCop: conflicting chdir during another chdir block`.
We don't want to run `chdir` since it may impact other things Ruby LSP is doing, since the path will be wrong.
Updated.
@alexcrocha has verified on Core.

Fix `chdir` issue for LSP

---

lib/ruby_lsp/tapioca/server_addon.rb

Sometimes RBI generation can take a while and the user has no hints that anything is happening. This PR adds progress notifications, so that the user has visual hints that Tapioca is running when a file is saved.
There's not much, I just wrapped our execution in the progress block.

Add progress indication for DSL operations

---

lib/ruby_lsp/tapioca/addon.rb

When we fail to boot the Rails runtime server, the runner client becomes an instance of `NullClient`, in which all operations are no-op.
There's no point in trying to run any DSL generation in that case because every notification will do nothing.
Started returning early if the client is not an instance of the concrete runner client.

No-op if runner client is null

---

lib/ruby_lsp/tapioca/server_addon.rb
lib/tapioca/cli.rb

`exit_on_failure?` is used by [Thor](https://github.com/rails/thor/blob/3178667e1727504bf4fb693bf4ac74a5ca6c691e/lib/thor/base.rb#L587C24-L587C39) to exit the process upon observing a `Thor::Error`. Tapioca does raise `Thor::Error`, most notably when we can't find a specified constant during DSL generation. Killing the process prevents the [notification wrapper](https://github.com/Shopify/tapioca/blob/055d7a0ef9d595e7b117f507d982533ccf343079/lib/ruby_lsp/tapioca/server_addon.rb#L56-L60) from completing and users are stuck with a "Generating DSL RBIs" editor notification . 
Introduce a new class instance variable that can be controlled by the tapioca add-on that'll determine the `exit_on_failure?` behaviour. This also means we can get rid of the CLI option on `dsl` method.
Tested manually

Introduce `addon_mode` ivar to Tapioca::Cli

---

lib/tapioca/commands/abstract_dsl.rb
lib/tapioca/dsl/pipeline.rb
spec/tapioca/cli/dsl_spec.rb

Exiting in add-on mode causes progress notifications to not be cleaned up
Raise a `Thor::Error` instead. It's rescued by thor and we control its behaviour using `exit_on_failure?` [here](https://github.com/Shopify/tapioca/blob/73381f35d990302e61822a32b709e598912d29db/lib/tapioca/cli.rb#L392)

Raise `Thor::Error` instead of `exit`

---

lib/tapioca/commands/annotations.rb

This code works by miracle.
We call `fetch_annotation` within a `select` but the method return `void`. It only works because the `T::Private::Types::Void::VOID` used by `sorbet-runtime` to replace the actual value is truthy.

Fix `fetch_annotation` signature

---

.github/workflows/ci.yml
spec/tapioca/dsl/compilers/action_mailer_spec.rb
spec/tapioca/gem/pipeline_spec.rb
tapioca.gemspec

Ruby 3.1 is EOL since 2025-03-26. See: https://www.ruby-lang.org/en/downloads/branches/.

Drop support for EOL Ruby 3.1 

---

spec/tapioca/cli/check_shims_spec.rb

This should reduce the flakiness of the test by avoiding matching the duplication from Sorbet's payload.

Make check-shims test more robust

---

lib/tapioca/helpers/test/isolation.rb

Moved the file to `typed: strict` and fixed type errors.

Move `isolation` helper to `typed: strict`

---

lib/tapioca/internal.rb

We need these to be loaded before, if not generating the RBI for `Spoom` won't contain generics.

Load the runtime patches before Spoom

---

lib/tapioca/gem/listeners/yard_doc.rb
spec/tapioca/gem/pipeline_spec.rb

It's an RBS comment that will be translated in gem RBIs into a `requires_ancestor` call. We don't need it as part of documentation and it results in type checking errors.
Add it to the existing ignored comments list

Ignore `@requires_ancestor` in `YardDoc` listener

---

lib/tapioca/internal.rb
lib/tapioca/rbs/rewriter.rb
lib/tapioca/runtime/trackers/autoload.rb

We need to eager load all the autoloads registered before we load the RBS rewriter, since we might enter into a weird loop when those constants are used for rewriting, which triggers their autoloads which tries to require their file, which we will try to rewrite, but fail since we need the constant to do the rewriting in the first place.
This is especially important since Prism has a few autoloaded constants whose associated file should NOT be rewritten (since they are needed for the rewriting itself), so should be loaded as early as possible.
Using the `AutoloadTracker` like this is appropriate since we continue to register autoloads even after the `eager_load_all!` is triggered, which makes calling `eager_load_all!` multiple times a safe operation.

Eager load autoloads that are registered before the RBS rewriter is loaded

---

lib/ruby_lsp/tapioca/server_addon.rb

Extensions may override DSL compilers and should be loaded before so that abstract methods such as `gather_constants` and `decorate` of the original compilers take precedence
These `require` calls were loading the compilers before the extensions which isn't the case for using tapioca from the CLI.
Without the requires the code should still work since `addon.rb` will dispatch `load_compilers_and_extensions` request before `route_dsl` or `fixtures_dsl`.

Do not load DSL compilers before extensions in add-on mode

---

lib/tapioca/dsl/compilers/active_record_relations.rb
spec/tapioca/dsl/compilers/active_record_relations_spec.rb

Support the parameter added in https://github.com/rails/rails/pull/52384
I started by refactoring the code to be DRYer because it was starting to be pretty long.
Updated the tests to check for 8.0
🎩 in a different repo that it generates updated signatures and calling `find_each(cursor:)` that it passes type checking.

Add support for cursor parameter on ActiveRecord's batch methods in Rails 8.0

---

lib/ruby_lsp/tapioca/addon.rb

The breaking change we will include as part of v0.25 is dropping `sorbet-runtime`, which Tapioca is already ready for. Let's just relax the constraint so that the add-on can activate.
**Note**: we are due a discussion about whether these soft version requirements are working as well as we'd like and we might move Tapioca to a hard dependency strategy, but for now let's just make sure we don't disable the add-on.

Relax Ruby LSP constraints to allow for v0.25

---

lib/ruby_lsp/tapioca/server_addon.rb

Loading DSL compilers can also fail and we just had a case of this which was tricky to debug. Let's wrap this operation in our standard handler, so that errors are reported in the output tab.
Wrapped the load of compilers in the notification handler.

Wrap loading DSL compilers in notification handler

---

lib/tapioca/dsl/compilers/active_record_delegated_types.rb
spec/tapioca/dsl/compilers/active_record_delegated_types_spec.rb

When `delegated_type` only has one type, `T.any` is used will error since there's only one type.
Don't use `T.any` when there's only one type.
Added a test case.

Fix single delegated_type

---

lib/tapioca/sorbet_ext/name_patch.rb
spec/tapioca/gem/pipeline_spec.rb

If the argument to a generic type was an anonymous type, the name of the type as returned by our `T::Types::Simple#name` patch was `nil`. But that meant that Tapioca was generating a type that was broken, like `T::Array[]`.
Fixes #2341 
The right thing to do is to return `T.untyped` for anonymous types, and not `nil`. So that we at least have a valid type, like `T::Array[::T.untyped]`, if not the original type.
Added a test case exhibiting the problem.

Fix handling of anonymous types in generic arguments

---

exe/tapioca
lib/tapioca/cli.rb
lib/tapioca/commands/abstract_dsl.rb
lib/tapioca/commands/abstract_gem.rb
lib/tapioca/commands/annotations.rb
lib/tapioca/commands/check_shims.rb
lib/tapioca/commands/gem_generate.rb
lib/tapioca/dsl/pipeline.rb
lib/tapioca/helpers/config_helper.rb
lib/tapioca/helpers/rbi_files_helper.rb
spec/tapioca/dsl/compilers/protobuf_spec.rb

This PR addresses #2208 which suggested replacing `Thor::Error` with a custom `Tapioca::Error`. 
- I feel my implementation may be naive in thinking that I would simply need to rename `Thor::Error`s to `Tapioca::Error` and am wondering if instead `exit_on_failure?` should be replaced or defined elsewhere.
- I’m still getting familiar with Tapioca and Thor and I’m not yet confident that my approach fully captures what’s intended around the replacement of `exit_on_failure?`. I’d really appreciate any feedback or pointers on what is expected here.
- Replaced usage of `Thor::Error` with `Tapioca::Error` (which was already defined) across codebase.
- In `CLI` mode we should be exiting (used `exit_on_failure?`)
- In `addon_mode` we should be silently terminating RBI Generation (again using …

Replace Instances of Thor::Error with Tapioca::Error

---

lib/ruby_lsp/tapioca/server_addon.rb

More context in #2349
Currently, any custom DSL compiler that uses `type_member` without extending `T::Generic` crashes in the add-on because the base `Tapioca::Dsl::Compiler` class no longer extends it and so the method doesn't exist.
This doesn't happen when running Tapioca through the CLI thanks to the rewriting done by Spoom, which adds back those extends. I don't yet understand why the rewriting doesn't happen as expected in add-on mode. It seems like it might be an ordering issue because when trying to print from the rewriter logic, I can't see the prints before DSL compilers are loaded.
Let's add an extend for `T::Generic` temporarily to bring the add-on back to a working state while we dig deeper.
Started extending `T::Generic` before loading DSL compilers, which fixes the issue.

Ensure Dsl::Compiler extends T::Generic in server add-on

---

lib/tapioca/dsl/compilers/active_model_attributes.rb
manual/compiler_activemodelattributes.md
spec/tapioca/dsl/compilers/active_model_attributes_spec.rb

Consumers that define Active Model classes which override any of the attribute models cannot override the signature of the generated attribute methods since we are making it look like the methods are defined on the model class, and not on an included module.
Start generating all attribute methods on a `GeneratedAttributeMethods` module that gets included into the model class.
Update the existing tests to match

Generate Active Model attributes in an included `GeneratedAttributeMethods` module

---

lib/tapioca/gem/listeners/yard_doc.rb

Resolves https://github.com/Shopify/tapioca/issues/2361

Fix RBS comment prefix in YardDoc listener

---

lib/tapioca/commands/annotations.rb
lib/tapioca/gem_info.rb
spec/tapioca/cli/annotations_spec.rb

Resolves https://github.com/Shopify/tapioca/issues/2355
`annotations` command parses the lockfile to get a list of gem names, we can get it from `Bundler.definition` instead.

Use `Bundler.load.specs` instead of reading `Gemfile.lock`

---

lib/tapioca/dsl/compilers/active_record_relations.rb

I couldn't find an existing issue for this, but I noticed while upgrading from 16 to 17, the ids method was generating as `Array[T.untyped]` for our UUID primary keys, while other similar UUID returning methods were generating as `String`
I don't know intention behind `ActiveModelTypeHelper` vs `ActiveRecordColumnHelper`, but since these are primary keys and tables exist, it seemed fine to use `ActiveRecordColumnHelper`? That seemed preferable compared to changing `ActiveModelTypeHelper` at all. Also, there is some other code using the Model Helper for `:find` and also seems to care about primary keys, but I don't know if that should also use `ActiveRecordColumnHelper` too.
I wasn't sure the best way to test this, given it seems pretty postgres specific, but happy to add some! Seems like …

use ActiveRecordColumnTypeHelper for primary key types

---

lib/tapioca/gem/listeners/mixins.rb
spec/tapioca/gem/pipeline_spec.rb

Part of https://github.com/Shopify/tapioca/issues/2393.
Fixes `Kernel` is already included errors by not generating `include ::Kernel` calls in RBIs.
If a module includes Kernel it's to have access to Kernel methods in it's implementation. But in RBIs we don't generate the method bodies so we shouldn't run into isssues.

Do not mixin Kernel for modules
